// Generated by NextFs. Do not edit by hand.
import { Layout as __nextFsDefault } from '../.fable/App/Layout.js'
export default __nextFsDefault
export { metadata, viewport } from '../.fable/App/Layout.js'
