namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk14 =
    type GoogleFont with
        [<Import("Hi_Melody", "next/font/google")>]
        static member Hi_Melody(options: obj) : LoadedFont = jsNative

        [<Import("Hina_Mincho", "next/font/google")>]
        static member Hina_Mincho(options: obj) : LoadedFont = jsNative

        [<Import("Hind", "next/font/google")>]
        static member Hind(options: obj) : LoadedFont = jsNative

        [<Import("Hind_Guntur", "next/font/google")>]
        static member Hind_Guntur(options: obj) : LoadedFont = jsNative

        [<Import("Hind_Madurai", "next/font/google")>]
        static member Hind_Madurai(options: obj) : LoadedFont = jsNative

        [<Import("Hind_Mysuru", "next/font/google")>]
        static member Hind_Mysuru(options: obj) : LoadedFont = jsNative

        [<Import("Hind_Siliguri", "next/font/google")>]
        static member Hind_Siliguri(options: obj) : LoadedFont = jsNative

        [<Import("Hind_Vadodara", "next/font/google")>]
        static member Hind_Vadodara(options: obj) : LoadedFont = jsNative

        [<Import("Holtwood_One_SC", "next/font/google")>]
        static member Holtwood_One_SC(options: obj) : LoadedFont = jsNative

        [<Import("Homemade_Apple", "next/font/google")>]
        static member Homemade_Apple(options: obj) : LoadedFont = jsNative

        [<Import("Homenaje", "next/font/google")>]
        static member Homenaje(options: obj) : LoadedFont = jsNative

        [<Import("Honk", "next/font/google")>]
        static member Honk(options: obj) : LoadedFont = jsNative

        [<Import("Host_Grotesk", "next/font/google")>]
        static member Host_Grotesk(options: obj) : LoadedFont = jsNative

        [<Import("Hubballi", "next/font/google")>]
        static member Hubballi(options: obj) : LoadedFont = jsNative

        [<Import("Hubot_Sans", "next/font/google")>]
        static member Hubot_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Huninn", "next/font/google")>]
        static member Huninn(options: obj) : LoadedFont = jsNative

        [<Import("Hurricane", "next/font/google")>]
        static member Hurricane(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Mono", "next/font/google")>]
        static member IBM_Plex_Mono(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans", "next/font/google")>]
        static member IBM_Plex_Sans(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_Arabic", "next/font/google")>]
        static member IBM_Plex_Sans_Arabic(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_Condensed", "next/font/google")>]
        static member IBM_Plex_Sans_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_Devanagari", "next/font/google")>]
        static member IBM_Plex_Sans_Devanagari(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_Hebrew", "next/font/google")>]
        static member IBM_Plex_Sans_Hebrew(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_JP", "next/font/google")>]
        static member IBM_Plex_Sans_JP(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_KR", "next/font/google")>]
        static member IBM_Plex_Sans_KR(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_Thai", "next/font/google")>]
        static member IBM_Plex_Sans_Thai(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Sans_Thai_Looped", "next/font/google")>]
        static member IBM_Plex_Sans_Thai_Looped(options: obj) : LoadedFont = jsNative

        [<Import("IBM_Plex_Serif", "next/font/google")>]
        static member IBM_Plex_Serif(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_DW_Pica", "next/font/google")>]
        static member IM_Fell_DW_Pica(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_DW_Pica_SC", "next/font/google")>]
        static member IM_Fell_DW_Pica_SC(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_Double_Pica", "next/font/google")>]
        static member IM_Fell_Double_Pica(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_Double_Pica_SC", "next/font/google")>]
        static member IM_Fell_Double_Pica_SC(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_English", "next/font/google")>]
        static member IM_Fell_English(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_English_SC", "next/font/google")>]
        static member IM_Fell_English_SC(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_French_Canon", "next/font/google")>]
        static member IM_Fell_French_Canon(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_French_Canon_SC", "next/font/google")>]
        static member IM_Fell_French_Canon_SC(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_Great_Primer", "next/font/google")>]
        static member IM_Fell_Great_Primer(options: obj) : LoadedFont = jsNative

        [<Import("IM_Fell_Great_Primer_SC", "next/font/google")>]
        static member IM_Fell_Great_Primer_SC(options: obj) : LoadedFont = jsNative

        [<Import("Iansui", "next/font/google")>]
        static member Iansui(options: obj) : LoadedFont = jsNative

        [<Import("Ibarra_Real_Nova", "next/font/google")>]
        static member Ibarra_Real_Nova(options: obj) : LoadedFont = jsNative

        [<Import("Iceberg", "next/font/google")>]
        static member Iceberg(options: obj) : LoadedFont = jsNative

        [<Import("Iceland", "next/font/google")>]
        static member Iceland(options: obj) : LoadedFont = jsNative

        [<Import("Imbue", "next/font/google")>]
        static member Imbue(options: obj) : LoadedFont = jsNative

        [<Import("Imperial_Script", "next/font/google")>]
        static member Imperial_Script(options: obj) : LoadedFont = jsNative

        [<Import("Imprima", "next/font/google")>]
        static member Imprima(options: obj) : LoadedFont = jsNative

        [<Import("Inclusive_Sans", "next/font/google")>]
        static member Inclusive_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Inconsolata", "next/font/google")>]
        static member Inconsolata(options: obj) : LoadedFont = jsNative

        [<Import("Inder", "next/font/google")>]
        static member Inder(options: obj) : LoadedFont = jsNative

