namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk35 =
    type GoogleFont with
        [<Import("Shadows_Into_Light_Two", "next/font/google")>]
        static member Shadows_Into_Light_Two(options: obj) : LoadedFont = jsNative

        [<Import("Shafarik", "next/font/google")>]
        static member Shafarik(options: obj) : LoadedFont = jsNative

        [<Import("Shalimar", "next/font/google")>]
        static member Shalimar(options: obj) : LoadedFont = jsNative

        [<Import("Shantell_Sans", "next/font/google")>]
        static member Shantell_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Shanti", "next/font/google")>]
        static member Shanti(options: obj) : LoadedFont = jsNative

        [<Import("Share", "next/font/google")>]
        static member Share(options: obj) : LoadedFont = jsNative

        [<Import("Share_Tech", "next/font/google")>]
        static member Share_Tech(options: obj) : LoadedFont = jsNative

        [<Import("Share_Tech_Mono", "next/font/google")>]
        static member Share_Tech_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Shippori_Antique", "next/font/google")>]
        static member Shippori_Antique(options: obj) : LoadedFont = jsNative

        [<Import("Shippori_Antique_B1", "next/font/google")>]
        static member Shippori_Antique_B1(options: obj) : LoadedFont = jsNative

        [<Import("Shippori_Mincho", "next/font/google")>]
        static member Shippori_Mincho(options: obj) : LoadedFont = jsNative

        [<Import("Shippori_Mincho_B1", "next/font/google")>]
        static member Shippori_Mincho_B1(options: obj) : LoadedFont = jsNative

        [<Import("Shizuru", "next/font/google")>]
        static member Shizuru(options: obj) : LoadedFont = jsNative

        [<Import("Shojumaru", "next/font/google")>]
        static member Shojumaru(options: obj) : LoadedFont = jsNative

        [<Import("Short_Stack", "next/font/google")>]
        static member Short_Stack(options: obj) : LoadedFont = jsNative

        [<Import("Shrikhand", "next/font/google")>]
        static member Shrikhand(options: obj) : LoadedFont = jsNative

        [<Import("Siemreap", "next/font/google")>]
        static member Siemreap(options: obj) : LoadedFont = jsNative

        [<Import("Sigmar", "next/font/google")>]
        static member Sigmar(options: obj) : LoadedFont = jsNative

        [<Import("Sigmar_One", "next/font/google")>]
        static member Sigmar_One(options: obj) : LoadedFont = jsNative

        [<Import("Signika", "next/font/google")>]
        static member Signika(options: obj) : LoadedFont = jsNative

        [<Import("Signika_Negative", "next/font/google")>]
        static member Signika_Negative(options: obj) : LoadedFont = jsNative

        [<Import("Silkscreen", "next/font/google")>]
        static member Silkscreen(options: obj) : LoadedFont = jsNative

        [<Import("Simonetta", "next/font/google")>]
        static member Simonetta(options: obj) : LoadedFont = jsNative

        [<Import("Single_Day", "next/font/google")>]
        static member Single_Day(options: obj) : LoadedFont = jsNative

        [<Import("Sintony", "next/font/google")>]
        static member Sintony(options: obj) : LoadedFont = jsNative

        [<Import("Sirin_Stencil", "next/font/google")>]
        static member Sirin_Stencil(options: obj) : LoadedFont = jsNative

        [<Import("Sirivennela", "next/font/google")>]
        static member Sirivennela(options: obj) : LoadedFont = jsNative

        [<Import("Six_Caps", "next/font/google")>]
        static member Six_Caps(options: obj) : LoadedFont = jsNative

        [<Import("Sixtyfour", "next/font/google")>]
        static member Sixtyfour(options: obj) : LoadedFont = jsNative

        [<Import("Sixtyfour_Convergence", "next/font/google")>]
        static member Sixtyfour_Convergence(options: obj) : LoadedFont = jsNative

        [<Import("Skranji", "next/font/google")>]
        static member Skranji(options: obj) : LoadedFont = jsNative

        [<Import("Slabo_13px", "next/font/google")>]
        static member Slabo_13px(options: obj) : LoadedFont = jsNative

        [<Import("Slabo_27px", "next/font/google")>]
        static member Slabo_27px(options: obj) : LoadedFont = jsNative

        [<Import("Slackey", "next/font/google")>]
        static member Slackey(options: obj) : LoadedFont = jsNative

        [<Import("Slackside_One", "next/font/google")>]
        static member Slackside_One(options: obj) : LoadedFont = jsNative

        [<Import("Smokum", "next/font/google")>]
        static member Smokum(options: obj) : LoadedFont = jsNative

        [<Import("Smooch", "next/font/google")>]
        static member Smooch(options: obj) : LoadedFont = jsNative

        [<Import("Smooch_Sans", "next/font/google")>]
        static member Smooch_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Smythe", "next/font/google")>]
        static member Smythe(options: obj) : LoadedFont = jsNative

        [<Import("Sniglet", "next/font/google")>]
        static member Sniglet(options: obj) : LoadedFont = jsNative

        [<Import("Snippet", "next/font/google")>]
        static member Snippet(options: obj) : LoadedFont = jsNative

        [<Import("Snowburst_One", "next/font/google")>]
        static member Snowburst_One(options: obj) : LoadedFont = jsNative

        [<Import("Sofadi_One", "next/font/google")>]
        static member Sofadi_One(options: obj) : LoadedFont = jsNative

        [<Import("Sofia", "next/font/google")>]
        static member Sofia(options: obj) : LoadedFont = jsNative

        [<Import("Sofia_Sans", "next/font/google")>]
        static member Sofia_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Sofia_Sans_Condensed", "next/font/google")>]
        static member Sofia_Sans_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Sofia_Sans_Extra_Condensed", "next/font/google")>]
        static member Sofia_Sans_Extra_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Sofia_Sans_Semi_Condensed", "next/font/google")>]
        static member Sofia_Sans_Semi_Condensed(options: obj) : LoadedFont = jsNative

