namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk34 =
    type GoogleFont with
        [<Import("Ruwudu", "next/font/google")>]
        static member Ruwudu(options: obj) : LoadedFont = jsNative

        [<Import("Rye", "next/font/google")>]
        static member Rye(options: obj) : LoadedFont = jsNative

        [<Import("SN_Pro", "next/font/google")>]
        static member SN_Pro(options: obj) : LoadedFont = jsNative

        [<Import("STIX_Two_Text", "next/font/google")>]
        static member STIX_Two_Text(options: obj) : LoadedFont = jsNative

        [<Import("SUSE", "next/font/google")>]
        static member SUSE(options: obj) : LoadedFont = jsNative

        [<Import("SUSE_Mono", "next/font/google")>]
        static member SUSE_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Sacramento", "next/font/google")>]
        static member Sacramento(options: obj) : LoadedFont = jsNative

        [<Import("Sahitya", "next/font/google")>]
        static member Sahitya(options: obj) : LoadedFont = jsNative

        [<Import("Sail", "next/font/google")>]
        static member Sail(options: obj) : LoadedFont = jsNative

        [<Import("Saira", "next/font/google")>]
        static member Saira(options: obj) : LoadedFont = jsNative

        [<Import("Saira_Condensed", "next/font/google")>]
        static member Saira_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Saira_Extra_Condensed", "next/font/google")>]
        static member Saira_Extra_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Saira_Semi_Condensed", "next/font/google")>]
        static member Saira_Semi_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Saira_Stencil_One", "next/font/google")>]
        static member Saira_Stencil_One(options: obj) : LoadedFont = jsNative

        [<Import("Salsa", "next/font/google")>]
        static member Salsa(options: obj) : LoadedFont = jsNative

        [<Import("Sanchez", "next/font/google")>]
        static member Sanchez(options: obj) : LoadedFont = jsNative

        [<Import("Sancreek", "next/font/google")>]
        static member Sancreek(options: obj) : LoadedFont = jsNative

        [<Import("Sankofa_Display", "next/font/google")>]
        static member Sankofa_Display(options: obj) : LoadedFont = jsNative

        [<Import("Sansation", "next/font/google")>]
        static member Sansation(options: obj) : LoadedFont = jsNative

        [<Import("Sansita", "next/font/google")>]
        static member Sansita(options: obj) : LoadedFont = jsNative

        [<Import("Sansita_Swashed", "next/font/google")>]
        static member Sansita_Swashed(options: obj) : LoadedFont = jsNative

        [<Import("Sarabun", "next/font/google")>]
        static member Sarabun(options: obj) : LoadedFont = jsNative

        [<Import("Sarala", "next/font/google")>]
        static member Sarala(options: obj) : LoadedFont = jsNative

        [<Import("Sarina", "next/font/google")>]
        static member Sarina(options: obj) : LoadedFont = jsNative

        [<Import("Sarpanch", "next/font/google")>]
        static member Sarpanch(options: obj) : LoadedFont = jsNative

        [<Import("Sassy_Frass", "next/font/google")>]
        static member Sassy_Frass(options: obj) : LoadedFont = jsNative

        [<Import("Satisfy", "next/font/google")>]
        static member Satisfy(options: obj) : LoadedFont = jsNative

        [<Import("Savate", "next/font/google")>]
        static member Savate(options: obj) : LoadedFont = jsNative

        [<Import("Sawarabi_Gothic", "next/font/google")>]
        static member Sawarabi_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Sawarabi_Mincho", "next/font/google")>]
        static member Sawarabi_Mincho(options: obj) : LoadedFont = jsNative

        [<Import("Scada", "next/font/google")>]
        static member Scada(options: obj) : LoadedFont = jsNative

        [<Import("Scheherazade_New", "next/font/google")>]
        static member Scheherazade_New(options: obj) : LoadedFont = jsNative

        [<Import("Schibsted_Grotesk", "next/font/google")>]
        static member Schibsted_Grotesk(options: obj) : LoadedFont = jsNative

        [<Import("Schoolbell", "next/font/google")>]
        static member Schoolbell(options: obj) : LoadedFont = jsNative

        [<Import("Science_Gothic", "next/font/google")>]
        static member Science_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Scope_One", "next/font/google")>]
        static member Scope_One(options: obj) : LoadedFont = jsNative

        [<Import("Seaweed_Script", "next/font/google")>]
        static member Seaweed_Script(options: obj) : LoadedFont = jsNative

        [<Import("Secular_One", "next/font/google")>]
        static member Secular_One(options: obj) : LoadedFont = jsNative

        [<Import("Sedan", "next/font/google")>]
        static member Sedan(options: obj) : LoadedFont = jsNative

        [<Import("Sedan_SC", "next/font/google")>]
        static member Sedan_SC(options: obj) : LoadedFont = jsNative

        [<Import("Sedgwick_Ave", "next/font/google")>]
        static member Sedgwick_Ave(options: obj) : LoadedFont = jsNative

        [<Import("Sedgwick_Ave_Display", "next/font/google")>]
        static member Sedgwick_Ave_Display(options: obj) : LoadedFont = jsNative

        [<Import("Sekuya", "next/font/google")>]
        static member Sekuya(options: obj) : LoadedFont = jsNative

        [<Import("Sen", "next/font/google")>]
        static member Sen(options: obj) : LoadedFont = jsNative

        [<Import("Send_Flowers", "next/font/google")>]
        static member Send_Flowers(options: obj) : LoadedFont = jsNative

        [<Import("Sevillana", "next/font/google")>]
        static member Sevillana(options: obj) : LoadedFont = jsNative

        [<Import("Seymour_One", "next/font/google")>]
        static member Seymour_One(options: obj) : LoadedFont = jsNative

        [<Import("Shadows_Into_Light", "next/font/google")>]
        static member Shadows_Into_Light(options: obj) : LoadedFont = jsNative

