namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk16 =
    type GoogleFont with
        [<Import("Joti_One", "next/font/google")>]
        static member Joti_One(options: obj) : LoadedFont = jsNative

        [<Import("Jua", "next/font/google")>]
        static member Jua(options: obj) : LoadedFont = jsNative

        [<Import("Judson", "next/font/google")>]
        static member Judson(options: obj) : LoadedFont = jsNative

        [<Import("Julee", "next/font/google")>]
        static member Julee(options: obj) : LoadedFont = jsNative

        [<Import("Julius_Sans_One", "next/font/google")>]
        static member Julius_Sans_One(options: obj) : LoadedFont = jsNative

        [<Import("Junge", "next/font/google")>]
        static member Junge(options: obj) : LoadedFont = jsNative

        [<Import("Jura", "next/font/google")>]
        static member Jura(options: obj) : LoadedFont = jsNative

        [<Import("Just_Another_Hand", "next/font/google")>]
        static member Just_Another_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Just_Me_Again_Down_Here", "next/font/google")>]
        static member Just_Me_Again_Down_Here(options: obj) : LoadedFont = jsNative

        [<Import("K2D", "next/font/google")>]
        static member K2D(options: obj) : LoadedFont = jsNative

        [<Import("Kablammo", "next/font/google")>]
        static member Kablammo(options: obj) : LoadedFont = jsNative

        [<Import("Kadwa", "next/font/google")>]
        static member Kadwa(options: obj) : LoadedFont = jsNative

        [<Import("Kaisei_Decol", "next/font/google")>]
        static member Kaisei_Decol(options: obj) : LoadedFont = jsNative

        [<Import("Kaisei_HarunoUmi", "next/font/google")>]
        static member Kaisei_HarunoUmi(options: obj) : LoadedFont = jsNative

        [<Import("Kaisei_Opti", "next/font/google")>]
        static member Kaisei_Opti(options: obj) : LoadedFont = jsNative

        [<Import("Kaisei_Tokumin", "next/font/google")>]
        static member Kaisei_Tokumin(options: obj) : LoadedFont = jsNative

        [<Import("Kalam", "next/font/google")>]
        static member Kalam(options: obj) : LoadedFont = jsNative

        [<Import("Kalnia", "next/font/google")>]
        static member Kalnia(options: obj) : LoadedFont = jsNative

        [<Import("Kalnia_Glaze", "next/font/google")>]
        static member Kalnia_Glaze(options: obj) : LoadedFont = jsNative

        [<Import("Kameron", "next/font/google")>]
        static member Kameron(options: obj) : LoadedFont = jsNative

        [<Import("Kanchenjunga", "next/font/google")>]
        static member Kanchenjunga(options: obj) : LoadedFont = jsNative

        [<Import("Kanit", "next/font/google")>]
        static member Kanit(options: obj) : LoadedFont = jsNative

        [<Import("Kantumruy_Pro", "next/font/google")>]
        static member Kantumruy_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Kapakana", "next/font/google")>]
        static member Kapakana(options: obj) : LoadedFont = jsNative

        [<Import("Karantina", "next/font/google")>]
        static member Karantina(options: obj) : LoadedFont = jsNative

        [<Import("Karla", "next/font/google")>]
        static member Karla(options: obj) : LoadedFont = jsNative

        [<Import("Karla_Tamil_Inclined", "next/font/google")>]
        static member Karla_Tamil_Inclined(options: obj) : LoadedFont = jsNative

        [<Import("Karla_Tamil_Upright", "next/font/google")>]
        static member Karla_Tamil_Upright(options: obj) : LoadedFont = jsNative

        [<Import("Karma", "next/font/google")>]
        static member Karma(options: obj) : LoadedFont = jsNative

        [<Import("Katibeh", "next/font/google")>]
        static member Katibeh(options: obj) : LoadedFont = jsNative

        [<Import("Kaushan_Script", "next/font/google")>]
        static member Kaushan_Script(options: obj) : LoadedFont = jsNative

        [<Import("Kavivanar", "next/font/google")>]
        static member Kavivanar(options: obj) : LoadedFont = jsNative

        [<Import("Kavoon", "next/font/google")>]
        static member Kavoon(options: obj) : LoadedFont = jsNative

        [<Import("Kay_Pho_Du", "next/font/google")>]
        static member Kay_Pho_Du(options: obj) : LoadedFont = jsNative

        [<Import("Kdam_Thmor_Pro", "next/font/google")>]
        static member Kdam_Thmor_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Keania_One", "next/font/google")>]
        static member Keania_One(options: obj) : LoadedFont = jsNative

        [<Import("Kedebideri", "next/font/google")>]
        static member Kedebideri(options: obj) : LoadedFont = jsNative

        [<Import("Kelly_Slab", "next/font/google")>]
        static member Kelly_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Kenia", "next/font/google")>]
        static member Kenia(options: obj) : LoadedFont = jsNative

        [<Import("Khand", "next/font/google")>]
        static member Khand(options: obj) : LoadedFont = jsNative

        [<Import("Khmer", "next/font/google")>]
        static member Khmer(options: obj) : LoadedFont = jsNative

        [<Import("Khula", "next/font/google")>]
        static member Khula(options: obj) : LoadedFont = jsNative

        [<Import("Kings", "next/font/google")>]
        static member Kings(options: obj) : LoadedFont = jsNative

        [<Import("Kirang_Haerang", "next/font/google")>]
        static member Kirang_Haerang(options: obj) : LoadedFont = jsNative

        [<Import("Kite_One", "next/font/google")>]
        static member Kite_One(options: obj) : LoadedFont = jsNative

        [<Import("Kiwi_Maru", "next/font/google")>]
        static member Kiwi_Maru(options: obj) : LoadedFont = jsNative

        [<Import("Klee_One", "next/font/google")>]
        static member Klee_One(options: obj) : LoadedFont = jsNative

        [<Import("Knewave", "next/font/google")>]
        static member Knewave(options: obj) : LoadedFont = jsNative

