namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk21 =
    type GoogleFont with
        [<Import("Monomaniac_One", "next/font/google")>]
        static member Monomaniac_One(options: obj) : LoadedFont = jsNative

        [<Import("Monoton", "next/font/google")>]
        static member Monoton(options: obj) : LoadedFont = jsNative

        [<Import("Monsieur_La_Doulaise", "next/font/google")>]
        static member Monsieur_La_Doulaise(options: obj) : LoadedFont = jsNative

        [<Import("Montaga", "next/font/google")>]
        static member Montaga(options: obj) : LoadedFont = jsNative

        [<Import("Montagu_Slab", "next/font/google")>]
        static member Montagu_Slab(options: obj) : LoadedFont = jsNative

        [<Import("MonteCarlo", "next/font/google")>]
        static member MonteCarlo(options: obj) : LoadedFont = jsNative

        [<Import("Montez", "next/font/google")>]
        static member Montez(options: obj) : LoadedFont = jsNative

        [<Import("Montserrat", "next/font/google")>]
        static member Montserrat(options: obj) : LoadedFont = jsNative

        [<Import("Montserrat_Alternates", "next/font/google")>]
        static member Montserrat_Alternates(options: obj) : LoadedFont = jsNative

        [<Import("Montserrat_Underline", "next/font/google")>]
        static member Montserrat_Underline(options: obj) : LoadedFont = jsNative

        [<Import("Moo_Lah_Lah", "next/font/google")>]
        static member Moo_Lah_Lah(options: obj) : LoadedFont = jsNative

        [<Import("Mooli", "next/font/google")>]
        static member Mooli(options: obj) : LoadedFont = jsNative

        [<Import("Moon_Dance", "next/font/google")>]
        static member Moon_Dance(options: obj) : LoadedFont = jsNative

        [<Import("Moul", "next/font/google")>]
        static member Moul(options: obj) : LoadedFont = jsNative

        [<Import("Moulpali", "next/font/google")>]
        static member Moulpali(options: obj) : LoadedFont = jsNative

        [<Import("Mountains_of_Christmas", "next/font/google")>]
        static member Mountains_of_Christmas(options: obj) : LoadedFont = jsNative

        [<Import("Mouse_Memoirs", "next/font/google")>]
        static member Mouse_Memoirs(options: obj) : LoadedFont = jsNative

        [<Import("Mozilla_Headline", "next/font/google")>]
        static member Mozilla_Headline(options: obj) : LoadedFont = jsNative

        [<Import("Mozilla_Text", "next/font/google")>]
        static member Mozilla_Text(options: obj) : LoadedFont = jsNative

        [<Import("Mr_Bedfort", "next/font/google")>]
        static member Mr_Bedfort(options: obj) : LoadedFont = jsNative

        [<Import("Mr_Dafoe", "next/font/google")>]
        static member Mr_Dafoe(options: obj) : LoadedFont = jsNative

        [<Import("Mr_De_Haviland", "next/font/google")>]
        static member Mr_De_Haviland(options: obj) : LoadedFont = jsNative

        [<Import("Mrs_Saint_Delafield", "next/font/google")>]
        static member Mrs_Saint_Delafield(options: obj) : LoadedFont = jsNative

        [<Import("Mrs_Sheppards", "next/font/google")>]
        static member Mrs_Sheppards(options: obj) : LoadedFont = jsNative

        [<Import("Ms_Madi", "next/font/google")>]
        static member Ms_Madi(options: obj) : LoadedFont = jsNative

        [<Import("Mukta", "next/font/google")>]
        static member Mukta(options: obj) : LoadedFont = jsNative

        [<Import("Mukta_Mahee", "next/font/google")>]
        static member Mukta_Mahee(options: obj) : LoadedFont = jsNative

        [<Import("Mukta_Malar", "next/font/google")>]
        static member Mukta_Malar(options: obj) : LoadedFont = jsNative

        [<Import("Mukta_Vaani", "next/font/google")>]
        static member Mukta_Vaani(options: obj) : LoadedFont = jsNative

        [<Import("Mulish", "next/font/google")>]
        static member Mulish(options: obj) : LoadedFont = jsNative

        [<Import("Murecho", "next/font/google")>]
        static member Murecho(options: obj) : LoadedFont = jsNative

        [<Import("MuseoModerno", "next/font/google")>]
        static member MuseoModerno(options: obj) : LoadedFont = jsNative

        [<Import("My_Soul", "next/font/google")>]
        static member My_Soul(options: obj) : LoadedFont = jsNative

        [<Import("Mynerve", "next/font/google")>]
        static member Mynerve(options: obj) : LoadedFont = jsNative

        [<Import("Mystery_Quest", "next/font/google")>]
        static member Mystery_Quest(options: obj) : LoadedFont = jsNative

        [<Import("NTR", "next/font/google")>]
        static member NTR(options: obj) : LoadedFont = jsNative

        [<Import("Nabla", "next/font/google")>]
        static member Nabla(options: obj) : LoadedFont = jsNative

        [<Import("Namdhinggo", "next/font/google")>]
        static member Namdhinggo(options: obj) : LoadedFont = jsNative

        [<Import("Nanum_Brush_Script", "next/font/google")>]
        static member Nanum_Brush_Script(options: obj) : LoadedFont = jsNative

        [<Import("Nanum_Gothic", "next/font/google")>]
        static member Nanum_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Nanum_Gothic_Coding", "next/font/google")>]
        static member Nanum_Gothic_Coding(options: obj) : LoadedFont = jsNative

        [<Import("Nanum_Myeongjo", "next/font/google")>]
        static member Nanum_Myeongjo(options: obj) : LoadedFont = jsNative

        [<Import("Nanum_Pen_Script", "next/font/google")>]
        static member Nanum_Pen_Script(options: obj) : LoadedFont = jsNative

        [<Import("Narnoor", "next/font/google")>]
        static member Narnoor(options: obj) : LoadedFont = jsNative

        [<Import("Nata_Sans", "next/font/google")>]
        static member Nata_Sans(options: obj) : LoadedFont = jsNative

        [<Import("National_Park", "next/font/google")>]
        static member National_Park(options: obj) : LoadedFont = jsNative

        [<Import("Neonderthaw", "next/font/google")>]
        static member Neonderthaw(options: obj) : LoadedFont = jsNative

        [<Import("Nerko_One", "next/font/google")>]
        static member Nerko_One(options: obj) : LoadedFont = jsNative

