namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk25 =
    type GoogleFont with
        [<Import("Noto_Sans_Samaritan", "next/font/google")>]
        static member Noto_Sans_Samaritan(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Saurashtra", "next/font/google")>]
        static member Noto_Sans_Saurashtra(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Sharada", "next/font/google")>]
        static member Noto_Sans_Sharada(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Shavian", "next/font/google")>]
        static member Noto_Sans_Shavian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Siddham", "next/font/google")>]
        static member Noto_Sans_Siddham(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_SignWriting", "next/font/google")>]
        static member Noto_Sans_SignWriting(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Sinhala", "next/font/google")>]
        static member Noto_Sans_Sinhala(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Sogdian", "next/font/google")>]
        static member Noto_Sans_Sogdian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Sora_Sompeng", "next/font/google")>]
        static member Noto_Sans_Sora_Sompeng(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Soyombo", "next/font/google")>]
        static member Noto_Sans_Soyombo(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Sundanese", "next/font/google")>]
        static member Noto_Sans_Sundanese(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Sunuwar", "next/font/google")>]
        static member Noto_Sans_Sunuwar(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Syloti_Nagri", "next/font/google")>]
        static member Noto_Sans_Syloti_Nagri(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Symbols", "next/font/google")>]
        static member Noto_Sans_Symbols(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Symbols_2", "next/font/google")>]
        static member Noto_Sans_Symbols_2(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Syriac", "next/font/google")>]
        static member Noto_Sans_Syriac(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Syriac_Eastern", "next/font/google")>]
        static member Noto_Sans_Syriac_Eastern(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Syriac_Western", "next/font/google")>]
        static member Noto_Sans_Syriac_Western(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_TC", "next/font/google")>]
        static member Noto_Sans_TC(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tagalog", "next/font/google")>]
        static member Noto_Sans_Tagalog(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tagbanwa", "next/font/google")>]
        static member Noto_Sans_Tagbanwa(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tai_Le", "next/font/google")>]
        static member Noto_Sans_Tai_Le(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tai_Tham", "next/font/google")>]
        static member Noto_Sans_Tai_Tham(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tai_Viet", "next/font/google")>]
        static member Noto_Sans_Tai_Viet(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Takri", "next/font/google")>]
        static member Noto_Sans_Takri(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tamil", "next/font/google")>]
        static member Noto_Sans_Tamil(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tamil_Supplement", "next/font/google")>]
        static member Noto_Sans_Tamil_Supplement(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tangsa", "next/font/google")>]
        static member Noto_Sans_Tangsa(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Telugu", "next/font/google")>]
        static member Noto_Sans_Telugu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Thaana", "next/font/google")>]
        static member Noto_Sans_Thaana(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Thai", "next/font/google")>]
        static member Noto_Sans_Thai(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Thai_Looped", "next/font/google")>]
        static member Noto_Sans_Thai_Looped(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tifinagh", "next/font/google")>]
        static member Noto_Sans_Tifinagh(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Tirhuta", "next/font/google")>]
        static member Noto_Sans_Tirhuta(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Ugaritic", "next/font/google")>]
        static member Noto_Sans_Ugaritic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Vai", "next/font/google")>]
        static member Noto_Sans_Vai(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Vithkuqi", "next/font/google")>]
        static member Noto_Sans_Vithkuqi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Wancho", "next/font/google")>]
        static member Noto_Sans_Wancho(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Warang_Citi", "next/font/google")>]
        static member Noto_Sans_Warang_Citi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Yi", "next/font/google")>]
        static member Noto_Sans_Yi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Zanabazar_Square", "next/font/google")>]
        static member Noto_Sans_Zanabazar_Square(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif", "next/font/google")>]
        static member Noto_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Ahom", "next/font/google")>]
        static member Noto_Serif_Ahom(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Armenian", "next/font/google")>]
        static member Noto_Serif_Armenian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Balinese", "next/font/google")>]
        static member Noto_Serif_Balinese(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Bengali", "next/font/google")>]
        static member Noto_Serif_Bengali(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Devanagari", "next/font/google")>]
        static member Noto_Serif_Devanagari(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Display", "next/font/google")>]
        static member Noto_Serif_Display(options: obj) : LoadedFont = jsNative

