namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk10 =
    type GoogleFont with
        [<Import("Edu_AU_VIC_WA_NT_Guides", "next/font/google")>]
        static member Edu_AU_VIC_WA_NT_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Edu_AU_VIC_WA_NT_Hand", "next/font/google")>]
        static member Edu_AU_VIC_WA_NT_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Edu_AU_VIC_WA_NT_Pre", "next/font/google")>]
        static member Edu_AU_VIC_WA_NT_Pre(options: obj) : LoadedFont = jsNative

        [<Import("Edu_NSW_ACT_Cursive", "next/font/google")>]
        static member Edu_NSW_ACT_Cursive(options: obj) : LoadedFont = jsNative

        [<Import("Edu_NSW_ACT_Foundation", "next/font/google")>]
        static member Edu_NSW_ACT_Foundation(options: obj) : LoadedFont = jsNative

        [<Import("Edu_NSW_ACT_Hand_Pre", "next/font/google")>]
        static member Edu_NSW_ACT_Hand_Pre(options: obj) : LoadedFont = jsNative

        [<Import("Edu_QLD_Beginner", "next/font/google")>]
        static member Edu_QLD_Beginner(options: obj) : LoadedFont = jsNative

        [<Import("Edu_QLD_Hand", "next/font/google")>]
        static member Edu_QLD_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Edu_SA_Beginner", "next/font/google")>]
        static member Edu_SA_Beginner(options: obj) : LoadedFont = jsNative

        [<Import("Edu_SA_Hand", "next/font/google")>]
        static member Edu_SA_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Edu_TAS_Beginner", "next/font/google")>]
        static member Edu_TAS_Beginner(options: obj) : LoadedFont = jsNative

        [<Import("Edu_VIC_WA_NT_Beginner", "next/font/google")>]
        static member Edu_VIC_WA_NT_Beginner(options: obj) : LoadedFont = jsNative

        [<Import("Edu_VIC_WA_NT_Hand", "next/font/google")>]
        static member Edu_VIC_WA_NT_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Edu_VIC_WA_NT_Hand_Pre", "next/font/google")>]
        static member Edu_VIC_WA_NT_Hand_Pre(options: obj) : LoadedFont = jsNative

        [<Import("El_Messiri", "next/font/google")>]
        static member El_Messiri(options: obj) : LoadedFont = jsNative

        [<Import("Electrolize", "next/font/google")>]
        static member Electrolize(options: obj) : LoadedFont = jsNative

        [<Import("Elms_Sans", "next/font/google")>]
        static member Elms_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Elsie", "next/font/google")>]
        static member Elsie(options: obj) : LoadedFont = jsNative

        [<Import("Elsie_Swash_Caps", "next/font/google")>]
        static member Elsie_Swash_Caps(options: obj) : LoadedFont = jsNative

        [<Import("Emblema_One", "next/font/google")>]
        static member Emblema_One(options: obj) : LoadedFont = jsNative

        [<Import("Emilys_Candy", "next/font/google")>]
        static member Emilys_Candy(options: obj) : LoadedFont = jsNative

        [<Import("Encode_Sans", "next/font/google")>]
        static member Encode_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Encode_Sans_Condensed", "next/font/google")>]
        static member Encode_Sans_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Encode_Sans_Expanded", "next/font/google")>]
        static member Encode_Sans_Expanded(options: obj) : LoadedFont = jsNative

        [<Import("Encode_Sans_SC", "next/font/google")>]
        static member Encode_Sans_SC(options: obj) : LoadedFont = jsNative

        [<Import("Encode_Sans_Semi_Condensed", "next/font/google")>]
        static member Encode_Sans_Semi_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Encode_Sans_Semi_Expanded", "next/font/google")>]
        static member Encode_Sans_Semi_Expanded(options: obj) : LoadedFont = jsNative

        [<Import("Engagement", "next/font/google")>]
        static member Engagement(options: obj) : LoadedFont = jsNative

        [<Import("Englebert", "next/font/google")>]
        static member Englebert(options: obj) : LoadedFont = jsNative

        [<Import("Enriqueta", "next/font/google")>]
        static member Enriqueta(options: obj) : LoadedFont = jsNative

        [<Import("Ephesis", "next/font/google")>]
        static member Ephesis(options: obj) : LoadedFont = jsNative

        [<Import("Epilogue", "next/font/google")>]
        static member Epilogue(options: obj) : LoadedFont = jsNative

        [<Import("Epunda_Sans", "next/font/google")>]
        static member Epunda_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Epunda_Slab", "next/font/google")>]
        static member Epunda_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Erica_One", "next/font/google")>]
        static member Erica_One(options: obj) : LoadedFont = jsNative

        [<Import("Esteban", "next/font/google")>]
        static member Esteban(options: obj) : LoadedFont = jsNative

        [<Import("Estonia", "next/font/google")>]
        static member Estonia(options: obj) : LoadedFont = jsNative

        [<Import("Euphoria_Script", "next/font/google")>]
        static member Euphoria_Script(options: obj) : LoadedFont = jsNative

        [<Import("Ewert", "next/font/google")>]
        static member Ewert(options: obj) : LoadedFont = jsNative

        [<Import("Exile", "next/font/google")>]
        static member Exile(options: obj) : LoadedFont = jsNative

        [<Import("Exo", "next/font/google")>]
        static member Exo(options: obj) : LoadedFont = jsNative

        [<Import("Exo_2", "next/font/google")>]
        static member Exo_2(options: obj) : LoadedFont = jsNative

        [<Import("Expletus_Sans", "next/font/google")>]
        static member Expletus_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Explora", "next/font/google")>]
        static member Explora(options: obj) : LoadedFont = jsNative

        [<Import("Faculty_Glyphic", "next/font/google")>]
        static member Faculty_Glyphic(options: obj) : LoadedFont = jsNative

        [<Import("Fahkwang", "next/font/google")>]
        static member Fahkwang(options: obj) : LoadedFont = jsNative

        [<Import("Familjen_Grotesk", "next/font/google")>]
        static member Familjen_Grotesk(options: obj) : LoadedFont = jsNative

        [<Import("Fanwood_Text", "next/font/google")>]
        static member Fanwood_Text(options: obj) : LoadedFont = jsNative

