namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk29 =
    type GoogleFont with
        [<Import("Playwrite_AU_SA_Guides", "next/font/google")>]
        static member Playwrite_AU_SA_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_TAS", "next/font/google")>]
        static member Playwrite_AU_TAS(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_TAS_Guides", "next/font/google")>]
        static member Playwrite_AU_TAS_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_VIC", "next/font/google")>]
        static member Playwrite_AU_VIC(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_VIC_Guides", "next/font/google")>]
        static member Playwrite_AU_VIC_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_BE_VLG", "next/font/google")>]
        static member Playwrite_BE_VLG(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_BE_VLG_Guides", "next/font/google")>]
        static member Playwrite_BE_VLG_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_BE_WAL", "next/font/google")>]
        static member Playwrite_BE_WAL(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_BE_WAL_Guides", "next/font/google")>]
        static member Playwrite_BE_WAL_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_BR", "next/font/google")>]
        static member Playwrite_BR(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_BR_Guides", "next/font/google")>]
        static member Playwrite_BR_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CA", "next/font/google")>]
        static member Playwrite_CA(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CA_Guides", "next/font/google")>]
        static member Playwrite_CA_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CL", "next/font/google")>]
        static member Playwrite_CL(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CL_Guides", "next/font/google")>]
        static member Playwrite_CL_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CO", "next/font/google")>]
        static member Playwrite_CO(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CO_Guides", "next/font/google")>]
        static member Playwrite_CO_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CU", "next/font/google")>]
        static member Playwrite_CU(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CU_Guides", "next/font/google")>]
        static member Playwrite_CU_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CZ", "next/font/google")>]
        static member Playwrite_CZ(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_CZ_Guides", "next/font/google")>]
        static member Playwrite_CZ_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_Grund", "next/font/google")>]
        static member Playwrite_DE_Grund(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_Grund_Guides", "next/font/google")>]
        static member Playwrite_DE_Grund_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_LA", "next/font/google")>]
        static member Playwrite_DE_LA(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_LA_Guides", "next/font/google")>]
        static member Playwrite_DE_LA_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_SAS", "next/font/google")>]
        static member Playwrite_DE_SAS(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_SAS_Guides", "next/font/google")>]
        static member Playwrite_DE_SAS_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_VA", "next/font/google")>]
        static member Playwrite_DE_VA(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DE_VA_Guides", "next/font/google")>]
        static member Playwrite_DE_VA_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DK_Loopet", "next/font/google")>]
        static member Playwrite_DK_Loopet(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DK_Loopet_Guides", "next/font/google")>]
        static member Playwrite_DK_Loopet_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DK_Uloopet", "next/font/google")>]
        static member Playwrite_DK_Uloopet(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_DK_Uloopet_Guides", "next/font/google")>]
        static member Playwrite_DK_Uloopet_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ES", "next/font/google")>]
        static member Playwrite_ES(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ES_Deco", "next/font/google")>]
        static member Playwrite_ES_Deco(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ES_Deco_Guides", "next/font/google")>]
        static member Playwrite_ES_Deco_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ES_Guides", "next/font/google")>]
        static member Playwrite_ES_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_FR_Moderne", "next/font/google")>]
        static member Playwrite_FR_Moderne(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_FR_Moderne_Guides", "next/font/google")>]
        static member Playwrite_FR_Moderne_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_FR_Trad", "next/font/google")>]
        static member Playwrite_FR_Trad(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_FR_Trad_Guides", "next/font/google")>]
        static member Playwrite_FR_Trad_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_GB_J", "next/font/google")>]
        static member Playwrite_GB_J(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_GB_J_Guides", "next/font/google")>]
        static member Playwrite_GB_J_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_GB_S", "next/font/google")>]
        static member Playwrite_GB_S(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_GB_S_Guides", "next/font/google")>]
        static member Playwrite_GB_S_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_HR", "next/font/google")>]
        static member Playwrite_HR(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_HR_Guides", "next/font/google")>]
        static member Playwrite_HR_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_HR_Lijeva", "next/font/google")>]
        static member Playwrite_HR_Lijeva(options: obj) : LoadedFont = jsNative

