namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk08 =
    type GoogleFont with
        [<Import("Coda", "next/font/google")>]
        static member Coda(options: obj) : LoadedFont = jsNative

        [<Import("Codystar", "next/font/google")>]
        static member Codystar(options: obj) : LoadedFont = jsNative

        [<Import("Coiny", "next/font/google")>]
        static member Coiny(options: obj) : LoadedFont = jsNative

        [<Import("Combo", "next/font/google")>]
        static member Combo(options: obj) : LoadedFont = jsNative

        [<Import("Comfortaa", "next/font/google")>]
        static member Comfortaa(options: obj) : LoadedFont = jsNative

        [<Import("Comforter", "next/font/google")>]
        static member Comforter(options: obj) : LoadedFont = jsNative

        [<Import("Comforter_Brush", "next/font/google")>]
        static member Comforter_Brush(options: obj) : LoadedFont = jsNative

        [<Import("Comic_Neue", "next/font/google")>]
        static member Comic_Neue(options: obj) : LoadedFont = jsNative

        [<Import("Comic_Relief", "next/font/google")>]
        static member Comic_Relief(options: obj) : LoadedFont = jsNative

        [<Import("Coming_Soon", "next/font/google")>]
        static member Coming_Soon(options: obj) : LoadedFont = jsNative

        [<Import("Comme", "next/font/google")>]
        static member Comme(options: obj) : LoadedFont = jsNative

        [<Import("Commissioner", "next/font/google")>]
        static member Commissioner(options: obj) : LoadedFont = jsNative

        [<Import("Concert_One", "next/font/google")>]
        static member Concert_One(options: obj) : LoadedFont = jsNative

        [<Import("Condiment", "next/font/google")>]
        static member Condiment(options: obj) : LoadedFont = jsNative

        [<Import("Content", "next/font/google")>]
        static member Content(options: obj) : LoadedFont = jsNative

        [<Import("Contrail_One", "next/font/google")>]
        static member Contrail_One(options: obj) : LoadedFont = jsNative

        [<Import("Convergence", "next/font/google")>]
        static member Convergence(options: obj) : LoadedFont = jsNative

        [<Import("Cookie", "next/font/google")>]
        static member Cookie(options: obj) : LoadedFont = jsNative

        [<Import("Copse", "next/font/google")>]
        static member Copse(options: obj) : LoadedFont = jsNative

        [<Import("Coral_Pixels", "next/font/google")>]
        static member Coral_Pixels(options: obj) : LoadedFont = jsNative

        [<Import("Corben", "next/font/google")>]
        static member Corben(options: obj) : LoadedFont = jsNative

        [<Import("Corinthia", "next/font/google")>]
        static member Corinthia(options: obj) : LoadedFont = jsNative

        [<Import("Cormorant", "next/font/google")>]
        static member Cormorant(options: obj) : LoadedFont = jsNative

        [<Import("Cormorant_Garamond", "next/font/google")>]
        static member Cormorant_Garamond(options: obj) : LoadedFont = jsNative

        [<Import("Cormorant_Infant", "next/font/google")>]
        static member Cormorant_Infant(options: obj) : LoadedFont = jsNative

        [<Import("Cormorant_SC", "next/font/google")>]
        static member Cormorant_SC(options: obj) : LoadedFont = jsNative

        [<Import("Cormorant_Unicase", "next/font/google")>]
        static member Cormorant_Unicase(options: obj) : LoadedFont = jsNative

        [<Import("Cormorant_Upright", "next/font/google")>]
        static member Cormorant_Upright(options: obj) : LoadedFont = jsNative

        [<Import("Cossette_Texte", "next/font/google")>]
        static member Cossette_Texte(options: obj) : LoadedFont = jsNative

        [<Import("Cossette_Titre", "next/font/google")>]
        static member Cossette_Titre(options: obj) : LoadedFont = jsNative

        [<Import("Courgette", "next/font/google")>]
        static member Courgette(options: obj) : LoadedFont = jsNative

        [<Import("Courier_Prime", "next/font/google")>]
        static member Courier_Prime(options: obj) : LoadedFont = jsNative

        [<Import("Cousine", "next/font/google")>]
        static member Cousine(options: obj) : LoadedFont = jsNative

        [<Import("Coustard", "next/font/google")>]
        static member Coustard(options: obj) : LoadedFont = jsNative

        [<Import("Covered_By_Your_Grace", "next/font/google")>]
        static member Covered_By_Your_Grace(options: obj) : LoadedFont = jsNative

        [<Import("Crafty_Girls", "next/font/google")>]
        static member Crafty_Girls(options: obj) : LoadedFont = jsNative

        [<Import("Creepster", "next/font/google")>]
        static member Creepster(options: obj) : LoadedFont = jsNative

        [<Import("Crete_Round", "next/font/google")>]
        static member Crete_Round(options: obj) : LoadedFont = jsNative

        [<Import("Crimson_Pro", "next/font/google")>]
        static member Crimson_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Crimson_Text", "next/font/google")>]
        static member Crimson_Text(options: obj) : LoadedFont = jsNative

        [<Import("Croissant_One", "next/font/google")>]
        static member Croissant_One(options: obj) : LoadedFont = jsNative

        [<Import("Crushed", "next/font/google")>]
        static member Crushed(options: obj) : LoadedFont = jsNative

        [<Import("Cuprum", "next/font/google")>]
        static member Cuprum(options: obj) : LoadedFont = jsNative

        [<Import("Cute_Font", "next/font/google")>]
        static member Cute_Font(options: obj) : LoadedFont = jsNative

        [<Import("Cutive", "next/font/google")>]
        static member Cutive(options: obj) : LoadedFont = jsNative

        [<Import("Cutive_Mono", "next/font/google")>]
        static member Cutive_Mono(options: obj) : LoadedFont = jsNative

        [<Import("DM_Mono", "next/font/google")>]
        static member DM_Mono(options: obj) : LoadedFont = jsNative

        [<Import("DM_Sans", "next/font/google")>]
        static member DM_Sans(options: obj) : LoadedFont = jsNative

