namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk17 =
    type GoogleFont with
        [<Import("KoHo", "next/font/google")>]
        static member KoHo(options: obj) : LoadedFont = jsNative

        [<Import("Kodchasan", "next/font/google")>]
        static member Kodchasan(options: obj) : LoadedFont = jsNative

        [<Import("Kode_Mono", "next/font/google")>]
        static member Kode_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Koh_Santepheap", "next/font/google")>]
        static member Koh_Santepheap(options: obj) : LoadedFont = jsNative

        [<Import("Kolker_Brush", "next/font/google")>]
        static member Kolker_Brush(options: obj) : LoadedFont = jsNative

        [<Import("Konkhmer_Sleokchher", "next/font/google")>]
        static member Konkhmer_Sleokchher(options: obj) : LoadedFont = jsNative

        [<Import("Kosugi", "next/font/google")>]
        static member Kosugi(options: obj) : LoadedFont = jsNative

        [<Import("Kosugi_Maru", "next/font/google")>]
        static member Kosugi_Maru(options: obj) : LoadedFont = jsNative

        [<Import("Kotta_One", "next/font/google")>]
        static member Kotta_One(options: obj) : LoadedFont = jsNative

        [<Import("Koulen", "next/font/google")>]
        static member Koulen(options: obj) : LoadedFont = jsNative

        [<Import("Kranky", "next/font/google")>]
        static member Kranky(options: obj) : LoadedFont = jsNative

        [<Import("Kreon", "next/font/google")>]
        static member Kreon(options: obj) : LoadedFont = jsNative

        [<Import("Kristi", "next/font/google")>]
        static member Kristi(options: obj) : LoadedFont = jsNative

        [<Import("Krona_One", "next/font/google")>]
        static member Krona_One(options: obj) : LoadedFont = jsNative

        [<Import("Krub", "next/font/google")>]
        static member Krub(options: obj) : LoadedFont = jsNative

        [<Import("Kufam", "next/font/google")>]
        static member Kufam(options: obj) : LoadedFont = jsNative

        [<Import("Kulim_Park", "next/font/google")>]
        static member Kulim_Park(options: obj) : LoadedFont = jsNative

        [<Import("Kumar_One", "next/font/google")>]
        static member Kumar_One(options: obj) : LoadedFont = jsNative

        [<Import("Kumar_One_Outline", "next/font/google")>]
        static member Kumar_One_Outline(options: obj) : LoadedFont = jsNative

        [<Import("Kumbh_Sans", "next/font/google")>]
        static member Kumbh_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Kurale", "next/font/google")>]
        static member Kurale(options: obj) : LoadedFont = jsNative

        [<Import("LINE_Seed_JP", "next/font/google")>]
        static member LINE_Seed_JP(options: obj) : LoadedFont = jsNative

        [<Import("LXGW_Marker_Gothic", "next/font/google")>]
        static member LXGW_Marker_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("LXGW_WenKai_Mono_TC", "next/font/google")>]
        static member LXGW_WenKai_Mono_TC(options: obj) : LoadedFont = jsNative

        [<Import("LXGW_WenKai_TC", "next/font/google")>]
        static member LXGW_WenKai_TC(options: obj) : LoadedFont = jsNative

        [<Import("La_Belle_Aurore", "next/font/google")>]
        static member La_Belle_Aurore(options: obj) : LoadedFont = jsNative

        [<Import("Labrada", "next/font/google")>]
        static member Labrada(options: obj) : LoadedFont = jsNative

        [<Import("Lacquer", "next/font/google")>]
        static member Lacquer(options: obj) : LoadedFont = jsNative

        [<Import("Laila", "next/font/google")>]
        static member Laila(options: obj) : LoadedFont = jsNative

        [<Import("Lakki_Reddy", "next/font/google")>]
        static member Lakki_Reddy(options: obj) : LoadedFont = jsNative

        [<Import("Lalezar", "next/font/google")>]
        static member Lalezar(options: obj) : LoadedFont = jsNative

        [<Import("Lancelot", "next/font/google")>]
        static member Lancelot(options: obj) : LoadedFont = jsNative

        [<Import("Langar", "next/font/google")>]
        static member Langar(options: obj) : LoadedFont = jsNative

        [<Import("Lateef", "next/font/google")>]
        static member Lateef(options: obj) : LoadedFont = jsNative

        [<Import("Lato", "next/font/google")>]
        static member Lato(options: obj) : LoadedFont = jsNative

        [<Import("Lavishly_Yours", "next/font/google")>]
        static member Lavishly_Yours(options: obj) : LoadedFont = jsNative

        [<Import("League_Gothic", "next/font/google")>]
        static member League_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("League_Script", "next/font/google")>]
        static member League_Script(options: obj) : LoadedFont = jsNative

        [<Import("League_Spartan", "next/font/google")>]
        static member League_Spartan(options: obj) : LoadedFont = jsNative

        [<Import("Leckerli_One", "next/font/google")>]
        static member Leckerli_One(options: obj) : LoadedFont = jsNative

        [<Import("Ledger", "next/font/google")>]
        static member Ledger(options: obj) : LoadedFont = jsNative

        [<Import("Lekton", "next/font/google")>]
        static member Lekton(options: obj) : LoadedFont = jsNative

        [<Import("Lemon", "next/font/google")>]
        static member Lemon(options: obj) : LoadedFont = jsNative

        [<Import("Lemonada", "next/font/google")>]
        static member Lemonada(options: obj) : LoadedFont = jsNative

        [<Import("Lexend", "next/font/google")>]
        static member Lexend(options: obj) : LoadedFont = jsNative

        [<Import("Lexend_Deca", "next/font/google")>]
        static member Lexend_Deca(options: obj) : LoadedFont = jsNative

        [<Import("Lexend_Exa", "next/font/google")>]
        static member Lexend_Exa(options: obj) : LoadedFont = jsNative

        [<Import("Lexend_Giga", "next/font/google")>]
        static member Lexend_Giga(options: obj) : LoadedFont = jsNative

