namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk11 =
    type GoogleFont with
        [<Import("Farro", "next/font/google")>]
        static member Farro(options: obj) : LoadedFont = jsNative

        [<Import("Farsan", "next/font/google")>]
        static member Farsan(options: obj) : LoadedFont = jsNative

        [<Import("Fascinate", "next/font/google")>]
        static member Fascinate(options: obj) : LoadedFont = jsNative

        [<Import("Fascinate_Inline", "next/font/google")>]
        static member Fascinate_Inline(options: obj) : LoadedFont = jsNative

        [<Import("Faster_One", "next/font/google")>]
        static member Faster_One(options: obj) : LoadedFont = jsNative

        [<Import("Fasthand", "next/font/google")>]
        static member Fasthand(options: obj) : LoadedFont = jsNative

        [<Import("Fauna_One", "next/font/google")>]
        static member Fauna_One(options: obj) : LoadedFont = jsNative

        [<Import("Faustina", "next/font/google")>]
        static member Faustina(options: obj) : LoadedFont = jsNative

        [<Import("Federant", "next/font/google")>]
        static member Federant(options: obj) : LoadedFont = jsNative

        [<Import("Federo", "next/font/google")>]
        static member Federo(options: obj) : LoadedFont = jsNative

        [<Import("Felipa", "next/font/google")>]
        static member Felipa(options: obj) : LoadedFont = jsNative

        [<Import("Fenix", "next/font/google")>]
        static member Fenix(options: obj) : LoadedFont = jsNative

        [<Import("Festive", "next/font/google")>]
        static member Festive(options: obj) : LoadedFont = jsNative

        [<Import("Figtree", "next/font/google")>]
        static member Figtree(options: obj) : LoadedFont = jsNative

        [<Import("Finger_Paint", "next/font/google")>]
        static member Finger_Paint(options: obj) : LoadedFont = jsNative

        [<Import("Finlandica", "next/font/google")>]
        static member Finlandica(options: obj) : LoadedFont = jsNative

        [<Import("Fira_Code", "next/font/google")>]
        static member Fira_Code(options: obj) : LoadedFont = jsNative

        [<Import("Fira_Mono", "next/font/google")>]
        static member Fira_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Fira_Sans", "next/font/google")>]
        static member Fira_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Fira_Sans_Condensed", "next/font/google")>]
        static member Fira_Sans_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Fira_Sans_Extra_Condensed", "next/font/google")>]
        static member Fira_Sans_Extra_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Fjalla_One", "next/font/google")>]
        static member Fjalla_One(options: obj) : LoadedFont = jsNative

        [<Import("Fjord_One", "next/font/google")>]
        static member Fjord_One(options: obj) : LoadedFont = jsNative

        [<Import("Flamenco", "next/font/google")>]
        static member Flamenco(options: obj) : LoadedFont = jsNative

        [<Import("Flavors", "next/font/google")>]
        static member Flavors(options: obj) : LoadedFont = jsNative

        [<Import("Fleur_De_Leah", "next/font/google")>]
        static member Fleur_De_Leah(options: obj) : LoadedFont = jsNative

        [<Import("Flow_Block", "next/font/google")>]
        static member Flow_Block(options: obj) : LoadedFont = jsNative

        [<Import("Flow_Circular", "next/font/google")>]
        static member Flow_Circular(options: obj) : LoadedFont = jsNative

        [<Import("Flow_Rounded", "next/font/google")>]
        static member Flow_Rounded(options: obj) : LoadedFont = jsNative

        [<Import("Foldit", "next/font/google")>]
        static member Foldit(options: obj) : LoadedFont = jsNative

        [<Import("Fondamento", "next/font/google")>]
        static member Fondamento(options: obj) : LoadedFont = jsNative

        [<Import("Fontdiner_Swanky", "next/font/google")>]
        static member Fontdiner_Swanky(options: obj) : LoadedFont = jsNative

        [<Import("Forum", "next/font/google")>]
        static member Forum(options: obj) : LoadedFont = jsNative

        [<Import("Fragment_Mono", "next/font/google")>]
        static member Fragment_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Francois_One", "next/font/google")>]
        static member Francois_One(options: obj) : LoadedFont = jsNative

        [<Import("Frank_Ruhl_Libre", "next/font/google")>]
        static member Frank_Ruhl_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Fraunces", "next/font/google")>]
        static member Fraunces(options: obj) : LoadedFont = jsNative

        [<Import("Freckle_Face", "next/font/google")>]
        static member Freckle_Face(options: obj) : LoadedFont = jsNative

        [<Import("Fredericka_the_Great", "next/font/google")>]
        static member Fredericka_the_Great(options: obj) : LoadedFont = jsNative

        [<Import("Fredoka", "next/font/google")>]
        static member Fredoka(options: obj) : LoadedFont = jsNative

        [<Import("Freehand", "next/font/google")>]
        static member Freehand(options: obj) : LoadedFont = jsNative

        [<Import("Freeman", "next/font/google")>]
        static member Freeman(options: obj) : LoadedFont = jsNative

        [<Import("Fresca", "next/font/google")>]
        static member Fresca(options: obj) : LoadedFont = jsNative

        [<Import("Frijole", "next/font/google")>]
        static member Frijole(options: obj) : LoadedFont = jsNative

        [<Import("Fruktur", "next/font/google")>]
        static member Fruktur(options: obj) : LoadedFont = jsNative

        [<Import("Fugaz_One", "next/font/google")>]
        static member Fugaz_One(options: obj) : LoadedFont = jsNative

        [<Import("Fuggles", "next/font/google")>]
        static member Fuggles(options: obj) : LoadedFont = jsNative

        [<Import("Funnel_Display", "next/font/google")>]
        static member Funnel_Display(options: obj) : LoadedFont = jsNative

