namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk20 =
    type GoogleFont with
        [<Import("Maven_Pro", "next/font/google")>]
        static member Maven_Pro(options: obj) : LoadedFont = jsNative

        [<Import("McLaren", "next/font/google")>]
        static member McLaren(options: obj) : LoadedFont = jsNative

        [<Import("Mea_Culpa", "next/font/google")>]
        static member Mea_Culpa(options: obj) : LoadedFont = jsNative

        [<Import("Meddon", "next/font/google")>]
        static member Meddon(options: obj) : LoadedFont = jsNative

        [<Import("MedievalSharp", "next/font/google")>]
        static member MedievalSharp(options: obj) : LoadedFont = jsNative

        [<Import("Medula_One", "next/font/google")>]
        static member Medula_One(options: obj) : LoadedFont = jsNative

        [<Import("Meera_Inimai", "next/font/google")>]
        static member Meera_Inimai(options: obj) : LoadedFont = jsNative

        [<Import("Megrim", "next/font/google")>]
        static member Megrim(options: obj) : LoadedFont = jsNative

        [<Import("Meie_Script", "next/font/google")>]
        static member Meie_Script(options: obj) : LoadedFont = jsNative

        [<Import("Menbere", "next/font/google")>]
        static member Menbere(options: obj) : LoadedFont = jsNative

        [<Import("Meow_Script", "next/font/google")>]
        static member Meow_Script(options: obj) : LoadedFont = jsNative

        [<Import("Merienda", "next/font/google")>]
        static member Merienda(options: obj) : LoadedFont = jsNative

        [<Import("Merriweather", "next/font/google")>]
        static member Merriweather(options: obj) : LoadedFont = jsNative

        [<Import("Merriweather_Sans", "next/font/google")>]
        static member Merriweather_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Metal", "next/font/google")>]
        static member Metal(options: obj) : LoadedFont = jsNative

        [<Import("Metal_Mania", "next/font/google")>]
        static member Metal_Mania(options: obj) : LoadedFont = jsNative

        [<Import("Metamorphous", "next/font/google")>]
        static member Metamorphous(options: obj) : LoadedFont = jsNative

        [<Import("Metrophobic", "next/font/google")>]
        static member Metrophobic(options: obj) : LoadedFont = jsNative

        [<Import("Michroma", "next/font/google")>]
        static member Michroma(options: obj) : LoadedFont = jsNative

        [<Import("Micro_5", "next/font/google")>]
        static member Micro_5(options: obj) : LoadedFont = jsNative

        [<Import("Micro_5_Charted", "next/font/google")>]
        static member Micro_5_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Milonga", "next/font/google")>]
        static member Milonga(options: obj) : LoadedFont = jsNative

        [<Import("Miltonian", "next/font/google")>]
        static member Miltonian(options: obj) : LoadedFont = jsNative

        [<Import("Miltonian_Tattoo", "next/font/google")>]
        static member Miltonian_Tattoo(options: obj) : LoadedFont = jsNative

        [<Import("Mina", "next/font/google")>]
        static member Mina(options: obj) : LoadedFont = jsNative

        [<Import("Mingzat", "next/font/google")>]
        static member Mingzat(options: obj) : LoadedFont = jsNative

        [<Import("Miniver", "next/font/google")>]
        static member Miniver(options: obj) : LoadedFont = jsNative

        [<Import("Miriam_Libre", "next/font/google")>]
        static member Miriam_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Mirza", "next/font/google")>]
        static member Mirza(options: obj) : LoadedFont = jsNative

        [<Import("Miss_Fajardose", "next/font/google")>]
        static member Miss_Fajardose(options: obj) : LoadedFont = jsNative

        [<Import("Mitr", "next/font/google")>]
        static member Mitr(options: obj) : LoadedFont = jsNative

        [<Import("Mochiy_Pop_One", "next/font/google")>]
        static member Mochiy_Pop_One(options: obj) : LoadedFont = jsNative

        [<Import("Mochiy_Pop_P_One", "next/font/google")>]
        static member Mochiy_Pop_P_One(options: obj) : LoadedFont = jsNative

        [<Import("Modak", "next/font/google")>]
        static member Modak(options: obj) : LoadedFont = jsNative

        [<Import("Modern_Antiqua", "next/font/google")>]
        static member Modern_Antiqua(options: obj) : LoadedFont = jsNative

        [<Import("Moderustic", "next/font/google")>]
        static member Moderustic(options: obj) : LoadedFont = jsNative

        [<Import("Mogra", "next/font/google")>]
        static member Mogra(options: obj) : LoadedFont = jsNative

        [<Import("Mohave", "next/font/google")>]
        static member Mohave(options: obj) : LoadedFont = jsNative

        [<Import("Moirai_One", "next/font/google")>]
        static member Moirai_One(options: obj) : LoadedFont = jsNative

        [<Import("Molengo", "next/font/google")>]
        static member Molengo(options: obj) : LoadedFont = jsNative

        [<Import("Molle", "next/font/google")>]
        static member Molle(options: obj) : LoadedFont = jsNative

        [<Import("Momo_Signature", "next/font/google")>]
        static member Momo_Signature(options: obj) : LoadedFont = jsNative

        [<Import("Momo_Trust_Display", "next/font/google")>]
        static member Momo_Trust_Display(options: obj) : LoadedFont = jsNative

        [<Import("Momo_Trust_Sans", "next/font/google")>]
        static member Momo_Trust_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Mona_Sans", "next/font/google")>]
        static member Mona_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Monda", "next/font/google")>]
        static member Monda(options: obj) : LoadedFont = jsNative

        [<Import("Monofett", "next/font/google")>]
        static member Monofett(options: obj) : LoadedFont = jsNative

        [<Import("Monomakh", "next/font/google")>]
        static member Monomakh(options: obj) : LoadedFont = jsNative

