namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk26 =
    type GoogleFont with
        [<Import("Noto_Serif_Dives_Akuru", "next/font/google")>]
        static member Noto_Serif_Dives_Akuru(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Dogra", "next/font/google")>]
        static member Noto_Serif_Dogra(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Ethiopic", "next/font/google")>]
        static member Noto_Serif_Ethiopic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Georgian", "next/font/google")>]
        static member Noto_Serif_Georgian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Grantha", "next/font/google")>]
        static member Noto_Serif_Grantha(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Gujarati", "next/font/google")>]
        static member Noto_Serif_Gujarati(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Gurmukhi", "next/font/google")>]
        static member Noto_Serif_Gurmukhi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_HK", "next/font/google")>]
        static member Noto_Serif_HK(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Hebrew", "next/font/google")>]
        static member Noto_Serif_Hebrew(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Hentaigana", "next/font/google")>]
        static member Noto_Serif_Hentaigana(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_JP", "next/font/google")>]
        static member Noto_Serif_JP(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_KR", "next/font/google")>]
        static member Noto_Serif_KR(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Kannada", "next/font/google")>]
        static member Noto_Serif_Kannada(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Khitan_Small_Script", "next/font/google")>]
        static member Noto_Serif_Khitan_Small_Script(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Khmer", "next/font/google")>]
        static member Noto_Serif_Khmer(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Khojki", "next/font/google")>]
        static member Noto_Serif_Khojki(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Lao", "next/font/google")>]
        static member Noto_Serif_Lao(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Makasar", "next/font/google")>]
        static member Noto_Serif_Makasar(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Malayalam", "next/font/google")>]
        static member Noto_Serif_Malayalam(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Myanmar", "next/font/google")>]
        static member Noto_Serif_Myanmar(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_NP_Hmong", "next/font/google")>]
        static member Noto_Serif_NP_Hmong(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Old_Uyghur", "next/font/google")>]
        static member Noto_Serif_Old_Uyghur(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Oriya", "next/font/google")>]
        static member Noto_Serif_Oriya(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Ottoman_Siyaq", "next/font/google")>]
        static member Noto_Serif_Ottoman_Siyaq(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_SC", "next/font/google")>]
        static member Noto_Serif_SC(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Sinhala", "next/font/google")>]
        static member Noto_Serif_Sinhala(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_TC", "next/font/google")>]
        static member Noto_Serif_TC(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Tamil", "next/font/google")>]
        static member Noto_Serif_Tamil(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Tangut", "next/font/google")>]
        static member Noto_Serif_Tangut(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Telugu", "next/font/google")>]
        static member Noto_Serif_Telugu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Thai", "next/font/google")>]
        static member Noto_Serif_Thai(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Tibetan", "next/font/google")>]
        static member Noto_Serif_Tibetan(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Todhri", "next/font/google")>]
        static member Noto_Serif_Todhri(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Toto", "next/font/google")>]
        static member Noto_Serif_Toto(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Vithkuqi", "next/font/google")>]
        static member Noto_Serif_Vithkuqi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Serif_Yezidi", "next/font/google")>]
        static member Noto_Serif_Yezidi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Traditional_Nushu", "next/font/google")>]
        static member Noto_Traditional_Nushu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Znamenny_Musical_Notation", "next/font/google")>]
        static member Noto_Znamenny_Musical_Notation(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Cut", "next/font/google")>]
        static member Nova_Cut(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Flat", "next/font/google")>]
        static member Nova_Flat(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Mono", "next/font/google")>]
        static member Nova_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Oval", "next/font/google")>]
        static member Nova_Oval(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Round", "next/font/google")>]
        static member Nova_Round(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Script", "next/font/google")>]
        static member Nova_Script(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Slim", "next/font/google")>]
        static member Nova_Slim(options: obj) : LoadedFont = jsNative

        [<Import("Nova_Square", "next/font/google")>]
        static member Nova_Square(options: obj) : LoadedFont = jsNative

        [<Import("Numans", "next/font/google")>]
        static member Numans(options: obj) : LoadedFont = jsNative

        [<Import("Nunito", "next/font/google")>]
        static member Nunito(options: obj) : LoadedFont = jsNative

