namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk24 =
    type GoogleFont with
        [<Import("Noto_Sans_Malayalam", "next/font/google")>]
        static member Noto_Sans_Malayalam(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mandaic", "next/font/google")>]
        static member Noto_Sans_Mandaic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Manichaean", "next/font/google")>]
        static member Noto_Sans_Manichaean(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Marchen", "next/font/google")>]
        static member Noto_Sans_Marchen(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Masaram_Gondi", "next/font/google")>]
        static member Noto_Sans_Masaram_Gondi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Math", "next/font/google")>]
        static member Noto_Sans_Math(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mayan_Numerals", "next/font/google")>]
        static member Noto_Sans_Mayan_Numerals(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Medefaidrin", "next/font/google")>]
        static member Noto_Sans_Medefaidrin(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Meetei_Mayek", "next/font/google")>]
        static member Noto_Sans_Meetei_Mayek(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mende_Kikakui", "next/font/google")>]
        static member Noto_Sans_Mende_Kikakui(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Meroitic", "next/font/google")>]
        static member Noto_Sans_Meroitic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Miao", "next/font/google")>]
        static member Noto_Sans_Miao(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Modi", "next/font/google")>]
        static member Noto_Sans_Modi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mongolian", "next/font/google")>]
        static member Noto_Sans_Mongolian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mono", "next/font/google")>]
        static member Noto_Sans_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mro", "next/font/google")>]
        static member Noto_Sans_Mro(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Multani", "next/font/google")>]
        static member Noto_Sans_Multani(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Myanmar", "next/font/google")>]
        static member Noto_Sans_Myanmar(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_NKo", "next/font/google")>]
        static member Noto_Sans_NKo(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_NKo_Unjoined", "next/font/google")>]
        static member Noto_Sans_NKo_Unjoined(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Nabataean", "next/font/google")>]
        static member Noto_Sans_Nabataean(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Nag_Mundari", "next/font/google")>]
        static member Noto_Sans_Nag_Mundari(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Nandinagari", "next/font/google")>]
        static member Noto_Sans_Nandinagari(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_New_Tai_Lue", "next/font/google")>]
        static member Noto_Sans_New_Tai_Lue(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Newa", "next/font/google")>]
        static member Noto_Sans_Newa(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Nushu", "next/font/google")>]
        static member Noto_Sans_Nushu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Ogham", "next/font/google")>]
        static member Noto_Sans_Ogham(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Ol_Chiki", "next/font/google")>]
        static member Noto_Sans_Ol_Chiki(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_Hungarian", "next/font/google")>]
        static member Noto_Sans_Old_Hungarian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_Italic", "next/font/google")>]
        static member Noto_Sans_Old_Italic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_North_Arabian", "next/font/google")>]
        static member Noto_Sans_Old_North_Arabian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_Permic", "next/font/google")>]
        static member Noto_Sans_Old_Permic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_Persian", "next/font/google")>]
        static member Noto_Sans_Old_Persian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_Sogdian", "next/font/google")>]
        static member Noto_Sans_Old_Sogdian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_South_Arabian", "next/font/google")>]
        static member Noto_Sans_Old_South_Arabian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Old_Turkic", "next/font/google")>]
        static member Noto_Sans_Old_Turkic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Oriya", "next/font/google")>]
        static member Noto_Sans_Oriya(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Osage", "next/font/google")>]
        static member Noto_Sans_Osage(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Osmanya", "next/font/google")>]
        static member Noto_Sans_Osmanya(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Pahawh_Hmong", "next/font/google")>]
        static member Noto_Sans_Pahawh_Hmong(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Palmyrene", "next/font/google")>]
        static member Noto_Sans_Palmyrene(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Pau_Cin_Hau", "next/font/google")>]
        static member Noto_Sans_Pau_Cin_Hau(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_PhagsPa", "next/font/google")>]
        static member Noto_Sans_PhagsPa(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Phoenician", "next/font/google")>]
        static member Noto_Sans_Phoenician(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Psalter_Pahlavi", "next/font/google")>]
        static member Noto_Sans_Psalter_Pahlavi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Rejang", "next/font/google")>]
        static member Noto_Sans_Rejang(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Runic", "next/font/google")>]
        static member Noto_Sans_Runic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_SC", "next/font/google")>]
        static member Noto_Sans_SC(options: obj) : LoadedFont = jsNative

