namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk09 =
    type GoogleFont with
        [<Import("DM_Serif_Display", "next/font/google")>]
        static member DM_Serif_Display(options: obj) : LoadedFont = jsNative

        [<Import("DM_Serif_Text", "next/font/google")>]
        static member DM_Serif_Text(options: obj) : LoadedFont = jsNative

        [<Import("Dai_Banna_SIL", "next/font/google")>]
        static member Dai_Banna_SIL(options: obj) : LoadedFont = jsNative

        [<Import("Damion", "next/font/google")>]
        static member Damion(options: obj) : LoadedFont = jsNative

        [<Import("Dancing_Script", "next/font/google")>]
        static member Dancing_Script(options: obj) : LoadedFont = jsNative

        [<Import("Danfo", "next/font/google")>]
        static member Danfo(options: obj) : LoadedFont = jsNative

        [<Import("Dangrek", "next/font/google")>]
        static member Dangrek(options: obj) : LoadedFont = jsNative

        [<Import("Darker_Grotesque", "next/font/google")>]
        static member Darker_Grotesque(options: obj) : LoadedFont = jsNative

        [<Import("Darumadrop_One", "next/font/google")>]
        static member Darumadrop_One(options: obj) : LoadedFont = jsNative

        [<Import("David_Libre", "next/font/google")>]
        static member David_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Dawning_of_a_New_Day", "next/font/google")>]
        static member Dawning_of_a_New_Day(options: obj) : LoadedFont = jsNative

        [<Import("Days_One", "next/font/google")>]
        static member Days_One(options: obj) : LoadedFont = jsNative

        [<Import("Dekko", "next/font/google")>]
        static member Dekko(options: obj) : LoadedFont = jsNative

        [<Import("Dela_Gothic_One", "next/font/google")>]
        static member Dela_Gothic_One(options: obj) : LoadedFont = jsNative

        [<Import("Delicious_Handrawn", "next/font/google")>]
        static member Delicious_Handrawn(options: obj) : LoadedFont = jsNative

        [<Import("Delius", "next/font/google")>]
        static member Delius(options: obj) : LoadedFont = jsNative

        [<Import("Delius_Swash_Caps", "next/font/google")>]
        static member Delius_Swash_Caps(options: obj) : LoadedFont = jsNative

        [<Import("Delius_Unicase", "next/font/google")>]
        static member Delius_Unicase(options: obj) : LoadedFont = jsNative

        [<Import("Della_Respira", "next/font/google")>]
        static member Della_Respira(options: obj) : LoadedFont = jsNative

        [<Import("Denk_One", "next/font/google")>]
        static member Denk_One(options: obj) : LoadedFont = jsNative

        [<Import("Devonshire", "next/font/google")>]
        static member Devonshire(options: obj) : LoadedFont = jsNative

        [<Import("Dhurjati", "next/font/google")>]
        static member Dhurjati(options: obj) : LoadedFont = jsNative

        [<Import("Didact_Gothic", "next/font/google")>]
        static member Didact_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Diphylleia", "next/font/google")>]
        static member Diphylleia(options: obj) : LoadedFont = jsNative

        [<Import("Diplomata", "next/font/google")>]
        static member Diplomata(options: obj) : LoadedFont = jsNative

        [<Import("Diplomata_SC", "next/font/google")>]
        static member Diplomata_SC(options: obj) : LoadedFont = jsNative

        [<Import("Do_Hyeon", "next/font/google")>]
        static member Do_Hyeon(options: obj) : LoadedFont = jsNative

        [<Import("Dokdo", "next/font/google")>]
        static member Dokdo(options: obj) : LoadedFont = jsNative

        [<Import("Domine", "next/font/google")>]
        static member Domine(options: obj) : LoadedFont = jsNative

        [<Import("Donegal_One", "next/font/google")>]
        static member Donegal_One(options: obj) : LoadedFont = jsNative

        [<Import("Dongle", "next/font/google")>]
        static member Dongle(options: obj) : LoadedFont = jsNative

        [<Import("Doppio_One", "next/font/google")>]
        static member Doppio_One(options: obj) : LoadedFont = jsNative

        [<Import("Dorsa", "next/font/google")>]
        static member Dorsa(options: obj) : LoadedFont = jsNative

        [<Import("Dosis", "next/font/google")>]
        static member Dosis(options: obj) : LoadedFont = jsNative

        [<Import("DotGothic16", "next/font/google")>]
        static member DotGothic16(options: obj) : LoadedFont = jsNative

        [<Import("Doto", "next/font/google")>]
        static member Doto(options: obj) : LoadedFont = jsNative

        [<Import("Dr_Sugiyama", "next/font/google")>]
        static member Dr_Sugiyama(options: obj) : LoadedFont = jsNative

        [<Import("Duru_Sans", "next/font/google")>]
        static member Duru_Sans(options: obj) : LoadedFont = jsNative

        [<Import("DynaPuff", "next/font/google")>]
        static member DynaPuff(options: obj) : LoadedFont = jsNative

        [<Import("Dynalight", "next/font/google")>]
        static member Dynalight(options: obj) : LoadedFont = jsNative

        [<Import("EB_Garamond", "next/font/google")>]
        static member EB_Garamond(options: obj) : LoadedFont = jsNative

        [<Import("Eagle_Lake", "next/font/google")>]
        static member Eagle_Lake(options: obj) : LoadedFont = jsNative

        [<Import("East_Sea_Dokdo", "next/font/google")>]
        static member East_Sea_Dokdo(options: obj) : LoadedFont = jsNative

        [<Import("Eater", "next/font/google")>]
        static member Eater(options: obj) : LoadedFont = jsNative

        [<Import("Economica", "next/font/google")>]
        static member Economica(options: obj) : LoadedFont = jsNative

        [<Import("Eczar", "next/font/google")>]
        static member Eczar(options: obj) : LoadedFont = jsNative

        [<Import("Edu_AU_VIC_WA_NT_Arrows", "next/font/google")>]
        static member Edu_AU_VIC_WA_NT_Arrows(options: obj) : LoadedFont = jsNative

        [<Import("Edu_AU_VIC_WA_NT_Dots", "next/font/google")>]
        static member Edu_AU_VIC_WA_NT_Dots(options: obj) : LoadedFont = jsNative

