namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk22 =
    type GoogleFont with
        [<Import("Neucha", "next/font/google")>]
        static member Neucha(options: obj) : LoadedFont = jsNative

        [<Import("Neuton", "next/font/google")>]
        static member Neuton(options: obj) : LoadedFont = jsNative

        [<Import("New_Amsterdam", "next/font/google")>]
        static member New_Amsterdam(options: obj) : LoadedFont = jsNative

        [<Import("New_Rocker", "next/font/google")>]
        static member New_Rocker(options: obj) : LoadedFont = jsNative

        [<Import("New_Tegomin", "next/font/google")>]
        static member New_Tegomin(options: obj) : LoadedFont = jsNative

        [<Import("News_Cycle", "next/font/google")>]
        static member News_Cycle(options: obj) : LoadedFont = jsNative

        [<Import("Newsreader", "next/font/google")>]
        static member Newsreader(options: obj) : LoadedFont = jsNative

        [<Import("Niconne", "next/font/google")>]
        static member Niconne(options: obj) : LoadedFont = jsNative

        [<Import("Niramit", "next/font/google")>]
        static member Niramit(options: obj) : LoadedFont = jsNative

        [<Import("Nixie_One", "next/font/google")>]
        static member Nixie_One(options: obj) : LoadedFont = jsNative

        [<Import("Nobile", "next/font/google")>]
        static member Nobile(options: obj) : LoadedFont = jsNative

        [<Import("Nokora", "next/font/google")>]
        static member Nokora(options: obj) : LoadedFont = jsNative

        [<Import("Norican", "next/font/google")>]
        static member Norican(options: obj) : LoadedFont = jsNative

        [<Import("Nosifer", "next/font/google")>]
        static member Nosifer(options: obj) : LoadedFont = jsNative

        [<Import("Notable", "next/font/google")>]
        static member Notable(options: obj) : LoadedFont = jsNative

        [<Import("Nothing_You_Could_Do", "next/font/google")>]
        static member Nothing_You_Could_Do(options: obj) : LoadedFont = jsNative

        [<Import("Noticia_Text", "next/font/google")>]
        static member Noticia_Text(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Color_Emoji", "next/font/google")>]
        static member Noto_Color_Emoji(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Emoji", "next/font/google")>]
        static member Noto_Emoji(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Kufi_Arabic", "next/font/google")>]
        static member Noto_Kufi_Arabic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Music", "next/font/google")>]
        static member Noto_Music(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Naskh_Arabic", "next/font/google")>]
        static member Noto_Naskh_Arabic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Nastaliq_Urdu", "next/font/google")>]
        static member Noto_Nastaliq_Urdu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Rashi_Hebrew", "next/font/google")>]
        static member Noto_Rashi_Hebrew(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans", "next/font/google")>]
        static member Noto_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Adlam", "next/font/google")>]
        static member Noto_Sans_Adlam(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Adlam_Unjoined", "next/font/google")>]
        static member Noto_Sans_Adlam_Unjoined(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Anatolian_Hieroglyphs", "next/font/google")>]
        static member Noto_Sans_Anatolian_Hieroglyphs(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Arabic", "next/font/google")>]
        static member Noto_Sans_Arabic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Armenian", "next/font/google")>]
        static member Noto_Sans_Armenian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Avestan", "next/font/google")>]
        static member Noto_Sans_Avestan(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Balinese", "next/font/google")>]
        static member Noto_Sans_Balinese(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Bamum", "next/font/google")>]
        static member Noto_Sans_Bamum(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Bassa_Vah", "next/font/google")>]
        static member Noto_Sans_Bassa_Vah(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Batak", "next/font/google")>]
        static member Noto_Sans_Batak(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Bengali", "next/font/google")>]
        static member Noto_Sans_Bengali(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Bhaiksuki", "next/font/google")>]
        static member Noto_Sans_Bhaiksuki(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Brahmi", "next/font/google")>]
        static member Noto_Sans_Brahmi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Buginese", "next/font/google")>]
        static member Noto_Sans_Buginese(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Buhid", "next/font/google")>]
        static member Noto_Sans_Buhid(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Canadian_Aboriginal", "next/font/google")>]
        static member Noto_Sans_Canadian_Aboriginal(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Carian", "next/font/google")>]
        static member Noto_Sans_Carian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Caucasian_Albanian", "next/font/google")>]
        static member Noto_Sans_Caucasian_Albanian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Chakma", "next/font/google")>]
        static member Noto_Sans_Chakma(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Cham", "next/font/google")>]
        static member Noto_Sans_Cham(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Cherokee", "next/font/google")>]
        static member Noto_Sans_Cherokee(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Chorasmian", "next/font/google")>]
        static member Noto_Sans_Chorasmian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Coptic", "next/font/google")>]
        static member Noto_Sans_Coptic(options: obj) : LoadedFont = jsNative

