namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk12 =
    type GoogleFont with
        [<Import("Funnel_Sans", "next/font/google")>]
        static member Funnel_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Fustat", "next/font/google")>]
        static member Fustat(options: obj) : LoadedFont = jsNative

        [<Import("Fuzzy_Bubbles", "next/font/google")>]
        static member Fuzzy_Bubbles(options: obj) : LoadedFont = jsNative

        [<Import("GFS_Didot", "next/font/google")>]
        static member GFS_Didot(options: obj) : LoadedFont = jsNative

        [<Import("GFS_Neohellenic", "next/font/google")>]
        static member GFS_Neohellenic(options: obj) : LoadedFont = jsNative

        [<Import("Ga_Maamli", "next/font/google")>]
        static member Ga_Maamli(options: obj) : LoadedFont = jsNative

        [<Import("Gabarito", "next/font/google")>]
        static member Gabarito(options: obj) : LoadedFont = jsNative

        [<Import("Gabriela", "next/font/google")>]
        static member Gabriela(options: obj) : LoadedFont = jsNative

        [<Import("Gaegu", "next/font/google")>]
        static member Gaegu(options: obj) : LoadedFont = jsNative

        [<Import("Gafata", "next/font/google")>]
        static member Gafata(options: obj) : LoadedFont = jsNative

        [<Import("Gajraj_One", "next/font/google")>]
        static member Gajraj_One(options: obj) : LoadedFont = jsNative

        [<Import("Galada", "next/font/google")>]
        static member Galada(options: obj) : LoadedFont = jsNative

        [<Import("Galdeano", "next/font/google")>]
        static member Galdeano(options: obj) : LoadedFont = jsNative

        [<Import("Galindo", "next/font/google")>]
        static member Galindo(options: obj) : LoadedFont = jsNative

        [<Import("Gamja_Flower", "next/font/google")>]
        static member Gamja_Flower(options: obj) : LoadedFont = jsNative

        [<Import("Gantari", "next/font/google")>]
        static member Gantari(options: obj) : LoadedFont = jsNative

        [<Import("Gasoek_One", "next/font/google")>]
        static member Gasoek_One(options: obj) : LoadedFont = jsNative

        [<Import("Gayathri", "next/font/google")>]
        static member Gayathri(options: obj) : LoadedFont = jsNative

        [<Import("Geist", "next/font/google")>]
        static member Geist(options: obj) : LoadedFont = jsNative

        [<Import("Geist_Mono", "next/font/google")>]
        static member Geist_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Gelasio", "next/font/google")>]
        static member Gelasio(options: obj) : LoadedFont = jsNative

        [<Import("Gemunu_Libre", "next/font/google")>]
        static member Gemunu_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Genos", "next/font/google")>]
        static member Genos(options: obj) : LoadedFont = jsNative

        [<Import("Gentium_Book_Plus", "next/font/google")>]
        static member Gentium_Book_Plus(options: obj) : LoadedFont = jsNative

        [<Import("Gentium_Plus", "next/font/google")>]
        static member Gentium_Plus(options: obj) : LoadedFont = jsNative

        [<Import("Geo", "next/font/google")>]
        static member Geo(options: obj) : LoadedFont = jsNative

        [<Import("Geologica", "next/font/google")>]
        static member Geologica(options: obj) : LoadedFont = jsNative

        [<Import("Geom", "next/font/google")>]
        static member Geom(options: obj) : LoadedFont = jsNative

        [<Import("Georama", "next/font/google")>]
        static member Georama(options: obj) : LoadedFont = jsNative

        [<Import("Geostar", "next/font/google")>]
        static member Geostar(options: obj) : LoadedFont = jsNative

        [<Import("Geostar_Fill", "next/font/google")>]
        static member Geostar_Fill(options: obj) : LoadedFont = jsNative

        [<Import("Germania_One", "next/font/google")>]
        static member Germania_One(options: obj) : LoadedFont = jsNative

        [<Import("Gideon_Roman", "next/font/google")>]
        static member Gideon_Roman(options: obj) : LoadedFont = jsNative

        [<Import("Gidole", "next/font/google")>]
        static member Gidole(options: obj) : LoadedFont = jsNative

        [<Import("Gidugu", "next/font/google")>]
        static member Gidugu(options: obj) : LoadedFont = jsNative

        [<Import("Gilda_Display", "next/font/google")>]
        static member Gilda_Display(options: obj) : LoadedFont = jsNative

        [<Import("Girassol", "next/font/google")>]
        static member Girassol(options: obj) : LoadedFont = jsNative

        [<Import("Give_You_Glory", "next/font/google")>]
        static member Give_You_Glory(options: obj) : LoadedFont = jsNative

        [<Import("Glass_Antiqua", "next/font/google")>]
        static member Glass_Antiqua(options: obj) : LoadedFont = jsNative

        [<Import("Glegoo", "next/font/google")>]
        static member Glegoo(options: obj) : LoadedFont = jsNative

        [<Import("Gloock", "next/font/google")>]
        static member Gloock(options: obj) : LoadedFont = jsNative

        [<Import("Gloria_Hallelujah", "next/font/google")>]
        static member Gloria_Hallelujah(options: obj) : LoadedFont = jsNative

        [<Import("Glory", "next/font/google")>]
        static member Glory(options: obj) : LoadedFont = jsNative

        [<Import("Gluten", "next/font/google")>]
        static member Gluten(options: obj) : LoadedFont = jsNative

        [<Import("Goblin_One", "next/font/google")>]
        static member Goblin_One(options: obj) : LoadedFont = jsNative

        [<Import("Gochi_Hand", "next/font/google")>]
        static member Gochi_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Goldman", "next/font/google")>]
        static member Goldman(options: obj) : LoadedFont = jsNative

        [<Import("Golos_Text", "next/font/google")>]
        static member Golos_Text(options: obj) : LoadedFont = jsNative

