namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk23 =
    type GoogleFont with
        [<Import("Noto_Sans_Cuneiform", "next/font/google")>]
        static member Noto_Sans_Cuneiform(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Cypriot", "next/font/google")>]
        static member Noto_Sans_Cypriot(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Cypro_Minoan", "next/font/google")>]
        static member Noto_Sans_Cypro_Minoan(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Deseret", "next/font/google")>]
        static member Noto_Sans_Deseret(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Devanagari", "next/font/google")>]
        static member Noto_Sans_Devanagari(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Display", "next/font/google")>]
        static member Noto_Sans_Display(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Duployan", "next/font/google")>]
        static member Noto_Sans_Duployan(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Egyptian_Hieroglyphs", "next/font/google")>]
        static member Noto_Sans_Egyptian_Hieroglyphs(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Elbasan", "next/font/google")>]
        static member Noto_Sans_Elbasan(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Elymaic", "next/font/google")>]
        static member Noto_Sans_Elymaic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Ethiopic", "next/font/google")>]
        static member Noto_Sans_Ethiopic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Georgian", "next/font/google")>]
        static member Noto_Sans_Georgian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Glagolitic", "next/font/google")>]
        static member Noto_Sans_Glagolitic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Gothic", "next/font/google")>]
        static member Noto_Sans_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Grantha", "next/font/google")>]
        static member Noto_Sans_Grantha(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Gujarati", "next/font/google")>]
        static member Noto_Sans_Gujarati(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Gunjala_Gondi", "next/font/google")>]
        static member Noto_Sans_Gunjala_Gondi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Gurmukhi", "next/font/google")>]
        static member Noto_Sans_Gurmukhi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_HK", "next/font/google")>]
        static member Noto_Sans_HK(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Hanifi_Rohingya", "next/font/google")>]
        static member Noto_Sans_Hanifi_Rohingya(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Hanunoo", "next/font/google")>]
        static member Noto_Sans_Hanunoo(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Hatran", "next/font/google")>]
        static member Noto_Sans_Hatran(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Hebrew", "next/font/google")>]
        static member Noto_Sans_Hebrew(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Imperial_Aramaic", "next/font/google")>]
        static member Noto_Sans_Imperial_Aramaic(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Indic_Siyaq_Numbers", "next/font/google")>]
        static member Noto_Sans_Indic_Siyaq_Numbers(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Inscriptional_Pahlavi", "next/font/google")>]
        static member Noto_Sans_Inscriptional_Pahlavi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Inscriptional_Parthian", "next/font/google")>]
        static member Noto_Sans_Inscriptional_Parthian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_JP", "next/font/google")>]
        static member Noto_Sans_JP(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Javanese", "next/font/google")>]
        static member Noto_Sans_Javanese(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_KR", "next/font/google")>]
        static member Noto_Sans_KR(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Kaithi", "next/font/google")>]
        static member Noto_Sans_Kaithi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Kannada", "next/font/google")>]
        static member Noto_Sans_Kannada(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Kawi", "next/font/google")>]
        static member Noto_Sans_Kawi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Kayah_Li", "next/font/google")>]
        static member Noto_Sans_Kayah_Li(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Kharoshthi", "next/font/google")>]
        static member Noto_Sans_Kharoshthi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Khmer", "next/font/google")>]
        static member Noto_Sans_Khmer(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Khojki", "next/font/google")>]
        static member Noto_Sans_Khojki(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Khudawadi", "next/font/google")>]
        static member Noto_Sans_Khudawadi(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Lao", "next/font/google")>]
        static member Noto_Sans_Lao(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Lao_Looped", "next/font/google")>]
        static member Noto_Sans_Lao_Looped(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Lepcha", "next/font/google")>]
        static member Noto_Sans_Lepcha(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Limbu", "next/font/google")>]
        static member Noto_Sans_Limbu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Linear_A", "next/font/google")>]
        static member Noto_Sans_Linear_A(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Linear_B", "next/font/google")>]
        static member Noto_Sans_Linear_B(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Lisu", "next/font/google")>]
        static member Noto_Sans_Lisu(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Lycian", "next/font/google")>]
        static member Noto_Sans_Lycian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Lydian", "next/font/google")>]
        static member Noto_Sans_Lydian(options: obj) : LoadedFont = jsNative

        [<Import("Noto_Sans_Mahajani", "next/font/google")>]
        static member Noto_Sans_Mahajani(options: obj) : LoadedFont = jsNative

