namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk39 =
    type GoogleFont with
        [<Import("Varta", "next/font/google")>]
        static member Varta(options: obj) : LoadedFont = jsNative

        [<Import("Vast_Shadow", "next/font/google")>]
        static member Vast_Shadow(options: obj) : LoadedFont = jsNative

        [<Import("Vazirmatn", "next/font/google")>]
        static member Vazirmatn(options: obj) : LoadedFont = jsNative

        [<Import("Vend_Sans", "next/font/google")>]
        static member Vend_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Vesper_Libre", "next/font/google")>]
        static member Vesper_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Viaoda_Libre", "next/font/google")>]
        static member Viaoda_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Vibes", "next/font/google")>]
        static member Vibes(options: obj) : LoadedFont = jsNative

        [<Import("Vibur", "next/font/google")>]
        static member Vibur(options: obj) : LoadedFont = jsNative

        [<Import("Victor_Mono", "next/font/google")>]
        static member Victor_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Vidaloka", "next/font/google")>]
        static member Vidaloka(options: obj) : LoadedFont = jsNative

        [<Import("Viga", "next/font/google")>]
        static member Viga(options: obj) : LoadedFont = jsNative

        [<Import("Vina_Sans", "next/font/google")>]
        static member Vina_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Voces", "next/font/google")>]
        static member Voces(options: obj) : LoadedFont = jsNative

        [<Import("Volkhov", "next/font/google")>]
        static member Volkhov(options: obj) : LoadedFont = jsNative

        [<Import("Vollkorn", "next/font/google")>]
        static member Vollkorn(options: obj) : LoadedFont = jsNative

        [<Import("Vollkorn_SC", "next/font/google")>]
        static member Vollkorn_SC(options: obj) : LoadedFont = jsNative

        [<Import("Voltaire", "next/font/google")>]
        static member Voltaire(options: obj) : LoadedFont = jsNative

        [<Import("Vujahday_Script", "next/font/google")>]
        static member Vujahday_Script(options: obj) : LoadedFont = jsNative

        [<Import("WDXL_Lubrifont_JP_N", "next/font/google")>]
        static member WDXL_Lubrifont_JP_N(options: obj) : LoadedFont = jsNative

        [<Import("WDXL_Lubrifont_SC", "next/font/google")>]
        static member WDXL_Lubrifont_SC(options: obj) : LoadedFont = jsNative

        [<Import("WDXL_Lubrifont_TC", "next/font/google")>]
        static member WDXL_Lubrifont_TC(options: obj) : LoadedFont = jsNative

        [<Import("Waiting_for_the_Sunrise", "next/font/google")>]
        static member Waiting_for_the_Sunrise(options: obj) : LoadedFont = jsNative

        [<Import("Wallpoet", "next/font/google")>]
        static member Wallpoet(options: obj) : LoadedFont = jsNative

        [<Import("Walter_Turncoat", "next/font/google")>]
        static member Walter_Turncoat(options: obj) : LoadedFont = jsNative

        [<Import("Warnes", "next/font/google")>]
        static member Warnes(options: obj) : LoadedFont = jsNative

        [<Import("Water_Brush", "next/font/google")>]
        static member Water_Brush(options: obj) : LoadedFont = jsNative

        [<Import("Waterfall", "next/font/google")>]
        static member Waterfall(options: obj) : LoadedFont = jsNative

        [<Import("Wavefont", "next/font/google")>]
        static member Wavefont(options: obj) : LoadedFont = jsNative

        [<Import("Wellfleet", "next/font/google")>]
        static member Wellfleet(options: obj) : LoadedFont = jsNative

        [<Import("Wendy_One", "next/font/google")>]
        static member Wendy_One(options: obj) : LoadedFont = jsNative

        [<Import("Whisper", "next/font/google")>]
        static member Whisper(options: obj) : LoadedFont = jsNative

        [<Import("WindSong", "next/font/google")>]
        static member WindSong(options: obj) : LoadedFont = jsNative

        [<Import("Winky_Rough", "next/font/google")>]
        static member Winky_Rough(options: obj) : LoadedFont = jsNative

        [<Import("Winky_Sans", "next/font/google")>]
        static member Winky_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Wire_One", "next/font/google")>]
        static member Wire_One(options: obj) : LoadedFont = jsNative

        [<Import("Wittgenstein", "next/font/google")>]
        static member Wittgenstein(options: obj) : LoadedFont = jsNative

        [<Import("Wix_Madefor_Display", "next/font/google")>]
        static member Wix_Madefor_Display(options: obj) : LoadedFont = jsNative

        [<Import("Wix_Madefor_Text", "next/font/google")>]
        static member Wix_Madefor_Text(options: obj) : LoadedFont = jsNative

        [<Import("Work_Sans", "next/font/google")>]
        static member Work_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Workbench", "next/font/google")>]
        static member Workbench(options: obj) : LoadedFont = jsNative

        [<Import("Xanh_Mono", "next/font/google")>]
        static member Xanh_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Yaldevi", "next/font/google")>]
        static member Yaldevi(options: obj) : LoadedFont = jsNative

        [<Import("Yanone_Kaffeesatz", "next/font/google")>]
        static member Yanone_Kaffeesatz(options: obj) : LoadedFont = jsNative

        [<Import("Yantramanav", "next/font/google")>]
        static member Yantramanav(options: obj) : LoadedFont = jsNative

        [<Import("Yarndings_12", "next/font/google")>]
        static member Yarndings_12(options: obj) : LoadedFont = jsNative

        [<Import("Yarndings_12_Charted", "next/font/google")>]
        static member Yarndings_12_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Yarndings_20", "next/font/google")>]
        static member Yarndings_20(options: obj) : LoadedFont = jsNative

        [<Import("Yarndings_20_Charted", "next/font/google")>]
        static member Yarndings_20_Charted(options: obj) : LoadedFont = jsNative

