namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk05 =
    type GoogleFont with
        [<Import("Bellota_Text", "next/font/google")>]
        static member Bellota_Text(options: obj) : LoadedFont = jsNative

        [<Import("BenchNine", "next/font/google")>]
        static member BenchNine(options: obj) : LoadedFont = jsNative

        [<Import("Benne", "next/font/google")>]
        static member Benne(options: obj) : LoadedFont = jsNative

        [<Import("Bentham", "next/font/google")>]
        static member Bentham(options: obj) : LoadedFont = jsNative

        [<Import("Berkshire_Swash", "next/font/google")>]
        static member Berkshire_Swash(options: obj) : LoadedFont = jsNative

        [<Import("Besley", "next/font/google")>]
        static member Besley(options: obj) : LoadedFont = jsNative

        [<Import("Beth_Ellen", "next/font/google")>]
        static member Beth_Ellen(options: obj) : LoadedFont = jsNative

        [<Import("Bevan", "next/font/google")>]
        static member Bevan(options: obj) : LoadedFont = jsNative

        [<Import("BhuTuka_Expanded_One", "next/font/google")>]
        static member BhuTuka_Expanded_One(options: obj) : LoadedFont = jsNative

        [<Import("Big_Shoulders", "next/font/google")>]
        static member Big_Shoulders(options: obj) : LoadedFont = jsNative

        [<Import("Big_Shoulders_Inline", "next/font/google")>]
        static member Big_Shoulders_Inline(options: obj) : LoadedFont = jsNative

        [<Import("Big_Shoulders_Stencil", "next/font/google")>]
        static member Big_Shoulders_Stencil(options: obj) : LoadedFont = jsNative

        [<Import("Bigelow_Rules", "next/font/google")>]
        static member Bigelow_Rules(options: obj) : LoadedFont = jsNative

        [<Import("Bigshot_One", "next/font/google")>]
        static member Bigshot_One(options: obj) : LoadedFont = jsNative

        [<Import("Bilbo", "next/font/google")>]
        static member Bilbo(options: obj) : LoadedFont = jsNative

        [<Import("Bilbo_Swash_Caps", "next/font/google")>]
        static member Bilbo_Swash_Caps(options: obj) : LoadedFont = jsNative

        [<Import("BioRhyme", "next/font/google")>]
        static member BioRhyme(options: obj) : LoadedFont = jsNative

        [<Import("BioRhyme_Expanded", "next/font/google")>]
        static member BioRhyme_Expanded(options: obj) : LoadedFont = jsNative

        [<Import("Birthstone", "next/font/google")>]
        static member Birthstone(options: obj) : LoadedFont = jsNative

        [<Import("Birthstone_Bounce", "next/font/google")>]
        static member Birthstone_Bounce(options: obj) : LoadedFont = jsNative

        [<Import("Biryani", "next/font/google")>]
        static member Biryani(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount", "next/font/google")>]
        static member Bitcount(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Grid_Double", "next/font/google")>]
        static member Bitcount_Grid_Double(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Grid_Double_Ink", "next/font/google")>]
        static member Bitcount_Grid_Double_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Grid_Single", "next/font/google")>]
        static member Bitcount_Grid_Single(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Grid_Single_Ink", "next/font/google")>]
        static member Bitcount_Grid_Single_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Ink", "next/font/google")>]
        static member Bitcount_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Prop_Double", "next/font/google")>]
        static member Bitcount_Prop_Double(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Prop_Double_Ink", "next/font/google")>]
        static member Bitcount_Prop_Double_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Prop_Single", "next/font/google")>]
        static member Bitcount_Prop_Single(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Prop_Single_Ink", "next/font/google")>]
        static member Bitcount_Prop_Single_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Single", "next/font/google")>]
        static member Bitcount_Single(options: obj) : LoadedFont = jsNative

        [<Import("Bitcount_Single_Ink", "next/font/google")>]
        static member Bitcount_Single_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Bitter", "next/font/google")>]
        static member Bitter(options: obj) : LoadedFont = jsNative

        [<Import("Black_And_White_Picture", "next/font/google")>]
        static member Black_And_White_Picture(options: obj) : LoadedFont = jsNative

        [<Import("Black_Han_Sans", "next/font/google")>]
        static member Black_Han_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Black_Ops_One", "next/font/google")>]
        static member Black_Ops_One(options: obj) : LoadedFont = jsNative

        [<Import("Blaka", "next/font/google")>]
        static member Blaka(options: obj) : LoadedFont = jsNative

        [<Import("Blaka_Hollow", "next/font/google")>]
        static member Blaka_Hollow(options: obj) : LoadedFont = jsNative

        [<Import("Blaka_Ink", "next/font/google")>]
        static member Blaka_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Blinker", "next/font/google")>]
        static member Blinker(options: obj) : LoadedFont = jsNative

        [<Import("Bodoni_Moda", "next/font/google")>]
        static member Bodoni_Moda(options: obj) : LoadedFont = jsNative

        [<Import("Bodoni_Moda_SC", "next/font/google")>]
        static member Bodoni_Moda_SC(options: obj) : LoadedFont = jsNative

        [<Import("Bokor", "next/font/google")>]
        static member Bokor(options: obj) : LoadedFont = jsNative

        [<Import("Boldonse", "next/font/google")>]
        static member Boldonse(options: obj) : LoadedFont = jsNative

        [<Import("Bona_Nova", "next/font/google")>]
        static member Bona_Nova(options: obj) : LoadedFont = jsNative

        [<Import("Bona_Nova_SC", "next/font/google")>]
        static member Bona_Nova_SC(options: obj) : LoadedFont = jsNative

        [<Import("Bonbon", "next/font/google")>]
        static member Bonbon(options: obj) : LoadedFont = jsNative

