namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk06 =
    type GoogleFont with
        [<Import("Bonheur_Royale", "next/font/google")>]
        static member Bonheur_Royale(options: obj) : LoadedFont = jsNative

        [<Import("Boogaloo", "next/font/google")>]
        static member Boogaloo(options: obj) : LoadedFont = jsNative

        [<Import("Borel", "next/font/google")>]
        static member Borel(options: obj) : LoadedFont = jsNative

        [<Import("Bowlby_One", "next/font/google")>]
        static member Bowlby_One(options: obj) : LoadedFont = jsNative

        [<Import("Bowlby_One_SC", "next/font/google")>]
        static member Bowlby_One_SC(options: obj) : LoadedFont = jsNative

        [<Import("Braah_One", "next/font/google")>]
        static member Braah_One(options: obj) : LoadedFont = jsNative

        [<Import("Brawler", "next/font/google")>]
        static member Brawler(options: obj) : LoadedFont = jsNative

        [<Import("Bree_Serif", "next/font/google")>]
        static member Bree_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Bricolage_Grotesque", "next/font/google")>]
        static member Bricolage_Grotesque(options: obj) : LoadedFont = jsNative

        [<Import("Bruno_Ace", "next/font/google")>]
        static member Bruno_Ace(options: obj) : LoadedFont = jsNative

        [<Import("Bruno_Ace_SC", "next/font/google")>]
        static member Bruno_Ace_SC(options: obj) : LoadedFont = jsNative

        [<Import("Brygada_1918", "next/font/google")>]
        static member Brygada_1918(options: obj) : LoadedFont = jsNative

        [<Import("Bubblegum_Sans", "next/font/google")>]
        static member Bubblegum_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Bubbler_One", "next/font/google")>]
        static member Bubbler_One(options: obj) : LoadedFont = jsNative

        [<Import("Buda", "next/font/google")>]
        static member Buda(options: obj) : LoadedFont = jsNative

        [<Import("Buenard", "next/font/google")>]
        static member Buenard(options: obj) : LoadedFont = jsNative

        [<Import("Bungee", "next/font/google")>]
        static member Bungee(options: obj) : LoadedFont = jsNative

        [<Import("Bungee_Hairline", "next/font/google")>]
        static member Bungee_Hairline(options: obj) : LoadedFont = jsNative

        [<Import("Bungee_Inline", "next/font/google")>]
        static member Bungee_Inline(options: obj) : LoadedFont = jsNative

        [<Import("Bungee_Outline", "next/font/google")>]
        static member Bungee_Outline(options: obj) : LoadedFont = jsNative

        [<Import("Bungee_Shade", "next/font/google")>]
        static member Bungee_Shade(options: obj) : LoadedFont = jsNative

        [<Import("Bungee_Spice", "next/font/google")>]
        static member Bungee_Spice(options: obj) : LoadedFont = jsNative

        [<Import("Bungee_Tint", "next/font/google")>]
        static member Bungee_Tint(options: obj) : LoadedFont = jsNative

        [<Import("Butcherman", "next/font/google")>]
        static member Butcherman(options: obj) : LoadedFont = jsNative

        [<Import("Butterfly_Kids", "next/font/google")>]
        static member Butterfly_Kids(options: obj) : LoadedFont = jsNative

        [<Import("Bytesized", "next/font/google")>]
        static member Bytesized(options: obj) : LoadedFont = jsNative

        [<Import("Cabin", "next/font/google")>]
        static member Cabin(options: obj) : LoadedFont = jsNative

        [<Import("Cabin_Condensed", "next/font/google")>]
        static member Cabin_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Cabin_Sketch", "next/font/google")>]
        static member Cabin_Sketch(options: obj) : LoadedFont = jsNative

        [<Import("Cactus_Classical_Serif", "next/font/google")>]
        static member Cactus_Classical_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Caesar_Dressing", "next/font/google")>]
        static member Caesar_Dressing(options: obj) : LoadedFont = jsNative

        [<Import("Cagliostro", "next/font/google")>]
        static member Cagliostro(options: obj) : LoadedFont = jsNative

        [<Import("Cairo", "next/font/google")>]
        static member Cairo(options: obj) : LoadedFont = jsNative

        [<Import("Cairo_Play", "next/font/google")>]
        static member Cairo_Play(options: obj) : LoadedFont = jsNative

        [<Import("Cal_Sans", "next/font/google")>]
        static member Cal_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Caladea", "next/font/google")>]
        static member Caladea(options: obj) : LoadedFont = jsNative

        [<Import("Calistoga", "next/font/google")>]
        static member Calistoga(options: obj) : LoadedFont = jsNative

        [<Import("Calligraffitti", "next/font/google")>]
        static member Calligraffitti(options: obj) : LoadedFont = jsNative

        [<Import("Cambay", "next/font/google")>]
        static member Cambay(options: obj) : LoadedFont = jsNative

        [<Import("Cambo", "next/font/google")>]
        static member Cambo(options: obj) : LoadedFont = jsNative

        [<Import("Candal", "next/font/google")>]
        static member Candal(options: obj) : LoadedFont = jsNative

        [<Import("Cantarell", "next/font/google")>]
        static member Cantarell(options: obj) : LoadedFont = jsNative

        [<Import("Cantata_One", "next/font/google")>]
        static member Cantata_One(options: obj) : LoadedFont = jsNative

        [<Import("Cantora_One", "next/font/google")>]
        static member Cantora_One(options: obj) : LoadedFont = jsNative

        [<Import("Caprasimo", "next/font/google")>]
        static member Caprasimo(options: obj) : LoadedFont = jsNative

        [<Import("Capriola", "next/font/google")>]
        static member Capriola(options: obj) : LoadedFont = jsNative

        [<Import("Caramel", "next/font/google")>]
        static member Caramel(options: obj) : LoadedFont = jsNative

        [<Import("Carattere", "next/font/google")>]
        static member Carattere(options: obj) : LoadedFont = jsNative

