namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk15 =
    type GoogleFont with
        [<Import("Indie_Flower", "next/font/google")>]
        static member Indie_Flower(options: obj) : LoadedFont = jsNative

        [<Import("Ingrid_Darling", "next/font/google")>]
        static member Ingrid_Darling(options: obj) : LoadedFont = jsNative

        [<Import("Inika", "next/font/google")>]
        static member Inika(options: obj) : LoadedFont = jsNative

        [<Import("Inknut_Antiqua", "next/font/google")>]
        static member Inknut_Antiqua(options: obj) : LoadedFont = jsNative

        [<Import("Inria_Sans", "next/font/google")>]
        static member Inria_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Inria_Serif", "next/font/google")>]
        static member Inria_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Inspiration", "next/font/google")>]
        static member Inspiration(options: obj) : LoadedFont = jsNative

        [<Import("Instrument_Sans", "next/font/google")>]
        static member Instrument_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Instrument_Serif", "next/font/google")>]
        static member Instrument_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Intel_One_Mono", "next/font/google")>]
        static member Intel_One_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Inter", "next/font/google")>]
        static member Inter(options: obj) : LoadedFont = jsNative

        [<Import("Inter_Tight", "next/font/google")>]
        static member Inter_Tight(options: obj) : LoadedFont = jsNative

        [<Import("Irish_Grover", "next/font/google")>]
        static member Irish_Grover(options: obj) : LoadedFont = jsNative

        [<Import("Island_Moments", "next/font/google")>]
        static member Island_Moments(options: obj) : LoadedFont = jsNative

        [<Import("Istok_Web", "next/font/google")>]
        static member Istok_Web(options: obj) : LoadedFont = jsNative

        [<Import("Italiana", "next/font/google")>]
        static member Italiana(options: obj) : LoadedFont = jsNative

        [<Import("Italianno", "next/font/google")>]
        static member Italianno(options: obj) : LoadedFont = jsNative

        [<Import("Itim", "next/font/google")>]
        static member Itim(options: obj) : LoadedFont = jsNative

        [<Import("Jacquard_12", "next/font/google")>]
        static member Jacquard_12(options: obj) : LoadedFont = jsNative

        [<Import("Jacquard_12_Charted", "next/font/google")>]
        static member Jacquard_12_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Jacquard_24", "next/font/google")>]
        static member Jacquard_24(options: obj) : LoadedFont = jsNative

        [<Import("Jacquard_24_Charted", "next/font/google")>]
        static member Jacquard_24_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Jacquarda_Bastarda_9", "next/font/google")>]
        static member Jacquarda_Bastarda_9(options: obj) : LoadedFont = jsNative

        [<Import("Jacquarda_Bastarda_9_Charted", "next/font/google")>]
        static member Jacquarda_Bastarda_9_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Jacques_Francois", "next/font/google")>]
        static member Jacques_Francois(options: obj) : LoadedFont = jsNative

        [<Import("Jacques_Francois_Shadow", "next/font/google")>]
        static member Jacques_Francois_Shadow(options: obj) : LoadedFont = jsNative

        [<Import("Jaini", "next/font/google")>]
        static member Jaini(options: obj) : LoadedFont = jsNative

        [<Import("Jaini_Purva", "next/font/google")>]
        static member Jaini_Purva(options: obj) : LoadedFont = jsNative

        [<Import("Jaldi", "next/font/google")>]
        static member Jaldi(options: obj) : LoadedFont = jsNative

        [<Import("Jaro", "next/font/google")>]
        static member Jaro(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_10", "next/font/google")>]
        static member Jersey_10(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_10_Charted", "next/font/google")>]
        static member Jersey_10_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_15", "next/font/google")>]
        static member Jersey_15(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_15_Charted", "next/font/google")>]
        static member Jersey_15_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_20", "next/font/google")>]
        static member Jersey_20(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_20_Charted", "next/font/google")>]
        static member Jersey_20_Charted(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_25", "next/font/google")>]
        static member Jersey_25(options: obj) : LoadedFont = jsNative

        [<Import("Jersey_25_Charted", "next/font/google")>]
        static member Jersey_25_Charted(options: obj) : LoadedFont = jsNative

        [<Import("JetBrains_Mono", "next/font/google")>]
        static member JetBrains_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Jim_Nightshade", "next/font/google")>]
        static member Jim_Nightshade(options: obj) : LoadedFont = jsNative

        [<Import("Joan", "next/font/google")>]
        static member Joan(options: obj) : LoadedFont = jsNative

        [<Import("Jockey_One", "next/font/google")>]
        static member Jockey_One(options: obj) : LoadedFont = jsNative

        [<Import("Jolly_Lodger", "next/font/google")>]
        static member Jolly_Lodger(options: obj) : LoadedFont = jsNative

        [<Import("Jomhuria", "next/font/google")>]
        static member Jomhuria(options: obj) : LoadedFont = jsNative

        [<Import("Jomolhari", "next/font/google")>]
        static member Jomolhari(options: obj) : LoadedFont = jsNative

        [<Import("Josefin_Sans", "next/font/google")>]
        static member Josefin_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Josefin_Slab", "next/font/google")>]
        static member Josefin_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Jost", "next/font/google")>]
        static member Jost(options: obj) : LoadedFont = jsNative

