namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk32 =
    type GoogleFont with
        [<Import("Radio_Canada_Big", "next/font/google")>]
        static member Radio_Canada_Big(options: obj) : LoadedFont = jsNative

        [<Import("Radley", "next/font/google")>]
        static member Radley(options: obj) : LoadedFont = jsNative

        [<Import("Rajdhani", "next/font/google")>]
        static member Rajdhani(options: obj) : LoadedFont = jsNative

        [<Import("Rakkas", "next/font/google")>]
        static member Rakkas(options: obj) : LoadedFont = jsNative

        [<Import("Raleway", "next/font/google")>]
        static member Raleway(options: obj) : LoadedFont = jsNative

        [<Import("Raleway_Dots", "next/font/google")>]
        static member Raleway_Dots(options: obj) : LoadedFont = jsNative

        [<Import("Ramabhadra", "next/font/google")>]
        static member Ramabhadra(options: obj) : LoadedFont = jsNative

        [<Import("Ramaraja", "next/font/google")>]
        static member Ramaraja(options: obj) : LoadedFont = jsNative

        [<Import("Rambla", "next/font/google")>]
        static member Rambla(options: obj) : LoadedFont = jsNative

        [<Import("Rammetto_One", "next/font/google")>]
        static member Rammetto_One(options: obj) : LoadedFont = jsNative

        [<Import("Rampart_One", "next/font/google")>]
        static member Rampart_One(options: obj) : LoadedFont = jsNative

        [<Import("Ranchers", "next/font/google")>]
        static member Ranchers(options: obj) : LoadedFont = jsNative

        [<Import("Rancho", "next/font/google")>]
        static member Rancho(options: obj) : LoadedFont = jsNative

        [<Import("Ranga", "next/font/google")>]
        static member Ranga(options: obj) : LoadedFont = jsNative

        [<Import("Rasa", "next/font/google")>]
        static member Rasa(options: obj) : LoadedFont = jsNative

        [<Import("Rationale", "next/font/google")>]
        static member Rationale(options: obj) : LoadedFont = jsNative

        [<Import("Ravi_Prakash", "next/font/google")>]
        static member Ravi_Prakash(options: obj) : LoadedFont = jsNative

        [<Import("Readex_Pro", "next/font/google")>]
        static member Readex_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Recursive", "next/font/google")>]
        static member Recursive(options: obj) : LoadedFont = jsNative

        [<Import("Red_Hat_Display", "next/font/google")>]
        static member Red_Hat_Display(options: obj) : LoadedFont = jsNative

        [<Import("Red_Hat_Mono", "next/font/google")>]
        static member Red_Hat_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Red_Hat_Text", "next/font/google")>]
        static member Red_Hat_Text(options: obj) : LoadedFont = jsNative

        [<Import("Red_Rose", "next/font/google")>]
        static member Red_Rose(options: obj) : LoadedFont = jsNative

        [<Import("Redacted", "next/font/google")>]
        static member Redacted(options: obj) : LoadedFont = jsNative

        [<Import("Redacted_Script", "next/font/google")>]
        static member Redacted_Script(options: obj) : LoadedFont = jsNative

        [<Import("Reddit_Mono", "next/font/google")>]
        static member Reddit_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Reddit_Sans", "next/font/google")>]
        static member Reddit_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Reddit_Sans_Condensed", "next/font/google")>]
        static member Reddit_Sans_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Redressed", "next/font/google")>]
        static member Redressed(options: obj) : LoadedFont = jsNative

        [<Import("Reem_Kufi", "next/font/google")>]
        static member Reem_Kufi(options: obj) : LoadedFont = jsNative

        [<Import("Reem_Kufi_Fun", "next/font/google")>]
        static member Reem_Kufi_Fun(options: obj) : LoadedFont = jsNative

        [<Import("Reem_Kufi_Ink", "next/font/google")>]
        static member Reem_Kufi_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Reenie_Beanie", "next/font/google")>]
        static member Reenie_Beanie(options: obj) : LoadedFont = jsNative

        [<Import("Reggae_One", "next/font/google")>]
        static member Reggae_One(options: obj) : LoadedFont = jsNative

        [<Import("Rethink_Sans", "next/font/google")>]
        static member Rethink_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Revalia", "next/font/google")>]
        static member Revalia(options: obj) : LoadedFont = jsNative

        [<Import("Rhodium_Libre", "next/font/google")>]
        static member Rhodium_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Ribeye", "next/font/google")>]
        static member Ribeye(options: obj) : LoadedFont = jsNative

        [<Import("Ribeye_Marrow", "next/font/google")>]
        static member Ribeye_Marrow(options: obj) : LoadedFont = jsNative

        [<Import("Righteous", "next/font/google")>]
        static member Righteous(options: obj) : LoadedFont = jsNative

        [<Import("Risque", "next/font/google")>]
        static member Risque(options: obj) : LoadedFont = jsNative

        [<Import("Road_Rage", "next/font/google")>]
        static member Road_Rage(options: obj) : LoadedFont = jsNative

        [<Import("Roboto", "next/font/google")>]
        static member Roboto(options: obj) : LoadedFont = jsNative

        [<Import("Roboto_Condensed", "next/font/google")>]
        static member Roboto_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Roboto_Flex", "next/font/google")>]
        static member Roboto_Flex(options: obj) : LoadedFont = jsNative

        [<Import("Roboto_Mono", "next/font/google")>]
        static member Roboto_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Roboto_Serif", "next/font/google")>]
        static member Roboto_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Roboto_Slab", "next/font/google")>]
        static member Roboto_Slab(options: obj) : LoadedFont = jsNative

