namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk28 =
    type GoogleFont with
        [<Import("Parisienne", "next/font/google")>]
        static member Parisienne(options: obj) : LoadedFont = jsNative

        [<Import("Parkinsans", "next/font/google")>]
        static member Parkinsans(options: obj) : LoadedFont = jsNative

        [<Import("Passero_One", "next/font/google")>]
        static member Passero_One(options: obj) : LoadedFont = jsNative

        [<Import("Passion_One", "next/font/google")>]
        static member Passion_One(options: obj) : LoadedFont = jsNative

        [<Import("Passions_Conflict", "next/font/google")>]
        static member Passions_Conflict(options: obj) : LoadedFont = jsNative

        [<Import("Pathway_Extreme", "next/font/google")>]
        static member Pathway_Extreme(options: obj) : LoadedFont = jsNative

        [<Import("Pathway_Gothic_One", "next/font/google")>]
        static member Pathway_Gothic_One(options: obj) : LoadedFont = jsNative

        [<Import("Patrick_Hand", "next/font/google")>]
        static member Patrick_Hand(options: obj) : LoadedFont = jsNative

        [<Import("Patrick_Hand_SC", "next/font/google")>]
        static member Patrick_Hand_SC(options: obj) : LoadedFont = jsNative

        [<Import("Pattaya", "next/font/google")>]
        static member Pattaya(options: obj) : LoadedFont = jsNative

        [<Import("Patua_One", "next/font/google")>]
        static member Patua_One(options: obj) : LoadedFont = jsNative

        [<Import("Pavanam", "next/font/google")>]
        static member Pavanam(options: obj) : LoadedFont = jsNative

        [<Import("Paytone_One", "next/font/google")>]
        static member Paytone_One(options: obj) : LoadedFont = jsNative

        [<Import("Peddana", "next/font/google")>]
        static member Peddana(options: obj) : LoadedFont = jsNative

        [<Import("Peralta", "next/font/google")>]
        static member Peralta(options: obj) : LoadedFont = jsNative

        [<Import("Permanent_Marker", "next/font/google")>]
        static member Permanent_Marker(options: obj) : LoadedFont = jsNative

        [<Import("Petemoss", "next/font/google")>]
        static member Petemoss(options: obj) : LoadedFont = jsNative

        [<Import("Petit_Formal_Script", "next/font/google")>]
        static member Petit_Formal_Script(options: obj) : LoadedFont = jsNative

        [<Import("Petrona", "next/font/google")>]
        static member Petrona(options: obj) : LoadedFont = jsNative

        [<Import("Phetsarath", "next/font/google")>]
        static member Phetsarath(options: obj) : LoadedFont = jsNative

        [<Import("Philosopher", "next/font/google")>]
        static member Philosopher(options: obj) : LoadedFont = jsNative

        [<Import("Phudu", "next/font/google")>]
        static member Phudu(options: obj) : LoadedFont = jsNative

        [<Import("Piazzolla", "next/font/google")>]
        static member Piazzolla(options: obj) : LoadedFont = jsNative

        [<Import("Piedra", "next/font/google")>]
        static member Piedra(options: obj) : LoadedFont = jsNative

        [<Import("Pinyon_Script", "next/font/google")>]
        static member Pinyon_Script(options: obj) : LoadedFont = jsNative

        [<Import("Pirata_One", "next/font/google")>]
        static member Pirata_One(options: obj) : LoadedFont = jsNative

        [<Import("Pixelify_Sans", "next/font/google")>]
        static member Pixelify_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Plaster", "next/font/google")>]
        static member Plaster(options: obj) : LoadedFont = jsNative

        [<Import("Platypi", "next/font/google")>]
        static member Platypi(options: obj) : LoadedFont = jsNative

        [<Import("Play", "next/font/google")>]
        static member Play(options: obj) : LoadedFont = jsNative

        [<Import("Playball", "next/font/google")>]
        static member Playball(options: obj) : LoadedFont = jsNative

        [<Import("Playfair", "next/font/google")>]
        static member Playfair(options: obj) : LoadedFont = jsNative

        [<Import("Playfair_Display", "next/font/google")>]
        static member Playfair_Display(options: obj) : LoadedFont = jsNative

        [<Import("Playfair_Display_SC", "next/font/google")>]
        static member Playfair_Display_SC(options: obj) : LoadedFont = jsNative

        [<Import("Playpen_Sans", "next/font/google")>]
        static member Playpen_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Playpen_Sans_Arabic", "next/font/google")>]
        static member Playpen_Sans_Arabic(options: obj) : LoadedFont = jsNative

        [<Import("Playpen_Sans_Deva", "next/font/google")>]
        static member Playpen_Sans_Deva(options: obj) : LoadedFont = jsNative

        [<Import("Playpen_Sans_Hebrew", "next/font/google")>]
        static member Playpen_Sans_Hebrew(options: obj) : LoadedFont = jsNative

        [<Import("Playpen_Sans_Thai", "next/font/google")>]
        static member Playpen_Sans_Thai(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AR", "next/font/google")>]
        static member Playwrite_AR(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AR_Guides", "next/font/google")>]
        static member Playwrite_AR_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AT", "next/font/google")>]
        static member Playwrite_AT(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AT_Guides", "next/font/google")>]
        static member Playwrite_AT_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_NSW", "next/font/google")>]
        static member Playwrite_AU_NSW(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_NSW_Guides", "next/font/google")>]
        static member Playwrite_AU_NSW_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_QLD", "next/font/google")>]
        static member Playwrite_AU_QLD(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_QLD_Guides", "next/font/google")>]
        static member Playwrite_AU_QLD_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_AU_SA", "next/font/google")>]
        static member Playwrite_AU_SA(options: obj) : LoadedFont = jsNative

