namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk19 =
    type GoogleFont with
        [<Import("Lugrasimo", "next/font/google")>]
        static member Lugrasimo(options: obj) : LoadedFont = jsNative

        [<Import("Lumanosimo", "next/font/google")>]
        static member Lumanosimo(options: obj) : LoadedFont = jsNative

        [<Import("Lunasima", "next/font/google")>]
        static member Lunasima(options: obj) : LoadedFont = jsNative

        [<Import("Lusitana", "next/font/google")>]
        static member Lusitana(options: obj) : LoadedFont = jsNative

        [<Import("Lustria", "next/font/google")>]
        static member Lustria(options: obj) : LoadedFont = jsNative

        [<Import("Luxurious_Roman", "next/font/google")>]
        static member Luxurious_Roman(options: obj) : LoadedFont = jsNative

        [<Import("Luxurious_Script", "next/font/google")>]
        static member Luxurious_Script(options: obj) : LoadedFont = jsNative

        [<Import("M_PLUS_1", "next/font/google")>]
        static member M_PLUS_1(options: obj) : LoadedFont = jsNative

        [<Import("M_PLUS_1_Code", "next/font/google")>]
        static member M_PLUS_1_Code(options: obj) : LoadedFont = jsNative

        [<Import("M_PLUS_1p", "next/font/google")>]
        static member M_PLUS_1p(options: obj) : LoadedFont = jsNative

        [<Import("M_PLUS_2", "next/font/google")>]
        static member M_PLUS_2(options: obj) : LoadedFont = jsNative

        [<Import("M_PLUS_Code_Latin", "next/font/google")>]
        static member M_PLUS_Code_Latin(options: obj) : LoadedFont = jsNative

        [<Import("M_PLUS_Rounded_1c", "next/font/google")>]
        static member M_PLUS_Rounded_1c(options: obj) : LoadedFont = jsNative

        [<Import("Ma_Shan_Zheng", "next/font/google")>]
        static member Ma_Shan_Zheng(options: obj) : LoadedFont = jsNative

        [<Import("Macondo", "next/font/google")>]
        static member Macondo(options: obj) : LoadedFont = jsNative

        [<Import("Macondo_Swash_Caps", "next/font/google")>]
        static member Macondo_Swash_Caps(options: obj) : LoadedFont = jsNative

        [<Import("Mada", "next/font/google")>]
        static member Mada(options: obj) : LoadedFont = jsNative

        [<Import("Madimi_One", "next/font/google")>]
        static member Madimi_One(options: obj) : LoadedFont = jsNative

        [<Import("Magra", "next/font/google")>]
        static member Magra(options: obj) : LoadedFont = jsNative

        [<Import("Maiden_Orange", "next/font/google")>]
        static member Maiden_Orange(options: obj) : LoadedFont = jsNative

        [<Import("Maitree", "next/font/google")>]
        static member Maitree(options: obj) : LoadedFont = jsNative

        [<Import("Major_Mono_Display", "next/font/google")>]
        static member Major_Mono_Display(options: obj) : LoadedFont = jsNative

        [<Import("Mako", "next/font/google")>]
        static member Mako(options: obj) : LoadedFont = jsNative

        [<Import("Mali", "next/font/google")>]
        static member Mali(options: obj) : LoadedFont = jsNative

        [<Import("Mallanna", "next/font/google")>]
        static member Mallanna(options: obj) : LoadedFont = jsNative

        [<Import("Maname", "next/font/google")>]
        static member Maname(options: obj) : LoadedFont = jsNative

        [<Import("Mandali", "next/font/google")>]
        static member Mandali(options: obj) : LoadedFont = jsNative

        [<Import("Manjari", "next/font/google")>]
        static member Manjari(options: obj) : LoadedFont = jsNative

        [<Import("Manrope", "next/font/google")>]
        static member Manrope(options: obj) : LoadedFont = jsNative

        [<Import("Mansalva", "next/font/google")>]
        static member Mansalva(options: obj) : LoadedFont = jsNative

        [<Import("Manuale", "next/font/google")>]
        static member Manuale(options: obj) : LoadedFont = jsNative

        [<Import("Manufacturing_Consent", "next/font/google")>]
        static member Manufacturing_Consent(options: obj) : LoadedFont = jsNative

        [<Import("Marcellus", "next/font/google")>]
        static member Marcellus(options: obj) : LoadedFont = jsNative

        [<Import("Marcellus_SC", "next/font/google")>]
        static member Marcellus_SC(options: obj) : LoadedFont = jsNative

        [<Import("Marck_Script", "next/font/google")>]
        static member Marck_Script(options: obj) : LoadedFont = jsNative

        [<Import("Margarine", "next/font/google")>]
        static member Margarine(options: obj) : LoadedFont = jsNative

        [<Import("Marhey", "next/font/google")>]
        static member Marhey(options: obj) : LoadedFont = jsNative

        [<Import("Markazi_Text", "next/font/google")>]
        static member Markazi_Text(options: obj) : LoadedFont = jsNative

        [<Import("Marko_One", "next/font/google")>]
        static member Marko_One(options: obj) : LoadedFont = jsNative

        [<Import("Marmelad", "next/font/google")>]
        static member Marmelad(options: obj) : LoadedFont = jsNative

        [<Import("Martel", "next/font/google")>]
        static member Martel(options: obj) : LoadedFont = jsNative

        [<Import("Martel_Sans", "next/font/google")>]
        static member Martel_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Martian_Mono", "next/font/google")>]
        static member Martian_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Marvel", "next/font/google")>]
        static member Marvel(options: obj) : LoadedFont = jsNative

        [<Import("Matangi", "next/font/google")>]
        static member Matangi(options: obj) : LoadedFont = jsNative

        [<Import("Mate", "next/font/google")>]
        static member Mate(options: obj) : LoadedFont = jsNative

        [<Import("Mate_SC", "next/font/google")>]
        static member Mate_SC(options: obj) : LoadedFont = jsNative

        [<Import("Matemasie", "next/font/google")>]
        static member Matemasie(options: obj) : LoadedFont = jsNative

