namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk37 =
    type GoogleFont with
        [<Import("Suez_One", "next/font/google")>]
        static member Suez_One(options: obj) : LoadedFont = jsNative

        [<Import("Sulphur_Point", "next/font/google")>]
        static member Sulphur_Point(options: obj) : LoadedFont = jsNative

        [<Import("Sumana", "next/font/google")>]
        static member Sumana(options: obj) : LoadedFont = jsNative

        [<Import("Sunflower", "next/font/google")>]
        static member Sunflower(options: obj) : LoadedFont = jsNative

        [<Import("Sunshiney", "next/font/google")>]
        static member Sunshiney(options: obj) : LoadedFont = jsNative

        [<Import("Supermercado_One", "next/font/google")>]
        static member Supermercado_One(options: obj) : LoadedFont = jsNative

        [<Import("Sura", "next/font/google")>]
        static member Sura(options: obj) : LoadedFont = jsNative

        [<Import("Suranna", "next/font/google")>]
        static member Suranna(options: obj) : LoadedFont = jsNative

        [<Import("Suravaram", "next/font/google")>]
        static member Suravaram(options: obj) : LoadedFont = jsNative

        [<Import("Suwannaphum", "next/font/google")>]
        static member Suwannaphum(options: obj) : LoadedFont = jsNative

        [<Import("Swanky_and_Moo_Moo", "next/font/google")>]
        static member Swanky_and_Moo_Moo(options: obj) : LoadedFont = jsNative

        [<Import("Syncopate", "next/font/google")>]
        static member Syncopate(options: obj) : LoadedFont = jsNative

        [<Import("Syne", "next/font/google")>]
        static member Syne(options: obj) : LoadedFont = jsNative

        [<Import("Syne_Mono", "next/font/google")>]
        static member Syne_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Syne_Tactile", "next/font/google")>]
        static member Syne_Tactile(options: obj) : LoadedFont = jsNative

        [<Import("TASA_Explorer", "next/font/google")>]
        static member TASA_Explorer(options: obj) : LoadedFont = jsNative

        [<Import("TASA_Orbiter", "next/font/google")>]
        static member TASA_Orbiter(options: obj) : LoadedFont = jsNative

        [<Import("Tac_One", "next/font/google")>]
        static member Tac_One(options: obj) : LoadedFont = jsNative

        [<Import("Tagesschrift", "next/font/google")>]
        static member Tagesschrift(options: obj) : LoadedFont = jsNative

        [<Import("Tai_Heritage_Pro", "next/font/google")>]
        static member Tai_Heritage_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Tajawal", "next/font/google")>]
        static member Tajawal(options: obj) : LoadedFont = jsNative

        [<Import("Tangerine", "next/font/google")>]
        static member Tangerine(options: obj) : LoadedFont = jsNative

        [<Import("Tapestry", "next/font/google")>]
        static member Tapestry(options: obj) : LoadedFont = jsNative

        [<Import("Taprom", "next/font/google")>]
        static member Taprom(options: obj) : LoadedFont = jsNative

        [<Import("Tauri", "next/font/google")>]
        static member Tauri(options: obj) : LoadedFont = jsNative

        [<Import("Taviraj", "next/font/google")>]
        static member Taviraj(options: obj) : LoadedFont = jsNative

        [<Import("Teachers", "next/font/google")>]
        static member Teachers(options: obj) : LoadedFont = jsNative

        [<Import("Teko", "next/font/google")>]
        static member Teko(options: obj) : LoadedFont = jsNative

        [<Import("Tektur", "next/font/google")>]
        static member Tektur(options: obj) : LoadedFont = jsNative

        [<Import("Telex", "next/font/google")>]
        static member Telex(options: obj) : LoadedFont = jsNative

        [<Import("Tenali_Ramakrishna", "next/font/google")>]
        static member Tenali_Ramakrishna(options: obj) : LoadedFont = jsNative

        [<Import("Tenor_Sans", "next/font/google")>]
        static member Tenor_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Text_Me_One", "next/font/google")>]
        static member Text_Me_One(options: obj) : LoadedFont = jsNative

        [<Import("Texturina", "next/font/google")>]
        static member Texturina(options: obj) : LoadedFont = jsNative

        [<Import("Thasadith", "next/font/google")>]
        static member Thasadith(options: obj) : LoadedFont = jsNative

        [<Import("The_Girl_Next_Door", "next/font/google")>]
        static member The_Girl_Next_Door(options: obj) : LoadedFont = jsNative

        [<Import("The_Nautigal", "next/font/google")>]
        static member The_Nautigal(options: obj) : LoadedFont = jsNative

        [<Import("Tienne", "next/font/google")>]
        static member Tienne(options: obj) : LoadedFont = jsNative

        [<Import("TikTok_Sans", "next/font/google")>]
        static member TikTok_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Tillana", "next/font/google")>]
        static member Tillana(options: obj) : LoadedFont = jsNative

        [<Import("Tilt_Neon", "next/font/google")>]
        static member Tilt_Neon(options: obj) : LoadedFont = jsNative

        [<Import("Tilt_Prism", "next/font/google")>]
        static member Tilt_Prism(options: obj) : LoadedFont = jsNative

        [<Import("Tilt_Warp", "next/font/google")>]
        static member Tilt_Warp(options: obj) : LoadedFont = jsNative

        [<Import("Timmana", "next/font/google")>]
        static member Timmana(options: obj) : LoadedFont = jsNative

        [<Import("Tinos", "next/font/google")>]
        static member Tinos(options: obj) : LoadedFont = jsNative

        [<Import("Tiny5", "next/font/google")>]
        static member Tiny5(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Bangla", "next/font/google")>]
        static member Tiro_Bangla(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Devanagari_Hindi", "next/font/google")>]
        static member Tiro_Devanagari_Hindi(options: obj) : LoadedFont = jsNative

