namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk31 =
    type GoogleFont with
        [<Import("Pochaevsk", "next/font/google")>]
        static member Pochaevsk(options: obj) : LoadedFont = jsNative

        [<Import("Podkova", "next/font/google")>]
        static member Podkova(options: obj) : LoadedFont = jsNative

        [<Import("Poetsen_One", "next/font/google")>]
        static member Poetsen_One(options: obj) : LoadedFont = jsNative

        [<Import("Poiret_One", "next/font/google")>]
        static member Poiret_One(options: obj) : LoadedFont = jsNative

        [<Import("Poller_One", "next/font/google")>]
        static member Poller_One(options: obj) : LoadedFont = jsNative

        [<Import("Poltawski_Nowy", "next/font/google")>]
        static member Poltawski_Nowy(options: obj) : LoadedFont = jsNative

        [<Import("Poly", "next/font/google")>]
        static member Poly(options: obj) : LoadedFont = jsNative

        [<Import("Pompiere", "next/font/google")>]
        static member Pompiere(options: obj) : LoadedFont = jsNative

        [<Import("Ponnala", "next/font/google")>]
        static member Ponnala(options: obj) : LoadedFont = jsNative

        [<Import("Ponomar", "next/font/google")>]
        static member Ponomar(options: obj) : LoadedFont = jsNative

        [<Import("Pontano_Sans", "next/font/google")>]
        static member Pontano_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Poor_Story", "next/font/google")>]
        static member Poor_Story(options: obj) : LoadedFont = jsNative

        [<Import("Poppins", "next/font/google")>]
        static member Poppins(options: obj) : LoadedFont = jsNative

        [<Import("Port_Lligat_Sans", "next/font/google")>]
        static member Port_Lligat_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Port_Lligat_Slab", "next/font/google")>]
        static member Port_Lligat_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Potta_One", "next/font/google")>]
        static member Potta_One(options: obj) : LoadedFont = jsNative

        [<Import("Pragati_Narrow", "next/font/google")>]
        static member Pragati_Narrow(options: obj) : LoadedFont = jsNative

        [<Import("Praise", "next/font/google")>]
        static member Praise(options: obj) : LoadedFont = jsNative

        [<Import("Prata", "next/font/google")>]
        static member Prata(options: obj) : LoadedFont = jsNative

        [<Import("Preahvihear", "next/font/google")>]
        static member Preahvihear(options: obj) : LoadedFont = jsNative

        [<Import("Press_Start_2P", "next/font/google")>]
        static member Press_Start_2P(options: obj) : LoadedFont = jsNative

        [<Import("Pridi", "next/font/google")>]
        static member Pridi(options: obj) : LoadedFont = jsNative

        [<Import("Princess_Sofia", "next/font/google")>]
        static member Princess_Sofia(options: obj) : LoadedFont = jsNative

        [<Import("Prociono", "next/font/google")>]
        static member Prociono(options: obj) : LoadedFont = jsNative

        [<Import("Prompt", "next/font/google")>]
        static member Prompt(options: obj) : LoadedFont = jsNative

        [<Import("Prosto_One", "next/font/google")>]
        static member Prosto_One(options: obj) : LoadedFont = jsNative

        [<Import("Protest_Guerrilla", "next/font/google")>]
        static member Protest_Guerrilla(options: obj) : LoadedFont = jsNative

        [<Import("Protest_Revolution", "next/font/google")>]
        static member Protest_Revolution(options: obj) : LoadedFont = jsNative

        [<Import("Protest_Riot", "next/font/google")>]
        static member Protest_Riot(options: obj) : LoadedFont = jsNative

        [<Import("Protest_Strike", "next/font/google")>]
        static member Protest_Strike(options: obj) : LoadedFont = jsNative

        [<Import("Proza_Libre", "next/font/google")>]
        static member Proza_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Public_Sans", "next/font/google")>]
        static member Public_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Puppies_Play", "next/font/google")>]
        static member Puppies_Play(options: obj) : LoadedFont = jsNative

        [<Import("Puritan", "next/font/google")>]
        static member Puritan(options: obj) : LoadedFont = jsNative

        [<Import("Purple_Purse", "next/font/google")>]
        static member Purple_Purse(options: obj) : LoadedFont = jsNative

        [<Import("Qahiri", "next/font/google")>]
        static member Qahiri(options: obj) : LoadedFont = jsNative

        [<Import("Quando", "next/font/google")>]
        static member Quando(options: obj) : LoadedFont = jsNative

        [<Import("Quantico", "next/font/google")>]
        static member Quantico(options: obj) : LoadedFont = jsNative

        [<Import("Quattrocento", "next/font/google")>]
        static member Quattrocento(options: obj) : LoadedFont = jsNative

        [<Import("Quattrocento_Sans", "next/font/google")>]
        static member Quattrocento_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Questrial", "next/font/google")>]
        static member Questrial(options: obj) : LoadedFont = jsNative

        [<Import("Quicksand", "next/font/google")>]
        static member Quicksand(options: obj) : LoadedFont = jsNative

        [<Import("Quintessential", "next/font/google")>]
        static member Quintessential(options: obj) : LoadedFont = jsNative

        [<Import("Qwigley", "next/font/google")>]
        static member Qwigley(options: obj) : LoadedFont = jsNative

        [<Import("Qwitcher_Grypen", "next/font/google")>]
        static member Qwitcher_Grypen(options: obj) : LoadedFont = jsNative

        [<Import("REM", "next/font/google")>]
        static member REM(options: obj) : LoadedFont = jsNative

        [<Import("Racing_Sans_One", "next/font/google")>]
        static member Racing_Sans_One(options: obj) : LoadedFont = jsNative

        [<Import("Radio_Canada", "next/font/google")>]
        static member Radio_Canada(options: obj) : LoadedFont = jsNative

