namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk07 =
    type GoogleFont with
        [<Import("Cardo", "next/font/google")>]
        static member Cardo(options: obj) : LoadedFont = jsNative

        [<Import("Carlito", "next/font/google")>]
        static member Carlito(options: obj) : LoadedFont = jsNative

        [<Import("Carme", "next/font/google")>]
        static member Carme(options: obj) : LoadedFont = jsNative

        [<Import("Carrois_Gothic", "next/font/google")>]
        static member Carrois_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Carrois_Gothic_SC", "next/font/google")>]
        static member Carrois_Gothic_SC(options: obj) : LoadedFont = jsNative

        [<Import("Carter_One", "next/font/google")>]
        static member Carter_One(options: obj) : LoadedFont = jsNative

        [<Import("Cascadia_Code", "next/font/google")>]
        static member Cascadia_Code(options: obj) : LoadedFont = jsNative

        [<Import("Cascadia_Mono", "next/font/google")>]
        static member Cascadia_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Castoro", "next/font/google")>]
        static member Castoro(options: obj) : LoadedFont = jsNative

        [<Import("Castoro_Titling", "next/font/google")>]
        static member Castoro_Titling(options: obj) : LoadedFont = jsNative

        [<Import("Catamaran", "next/font/google")>]
        static member Catamaran(options: obj) : LoadedFont = jsNative

        [<Import("Caudex", "next/font/google")>]
        static member Caudex(options: obj) : LoadedFont = jsNative

        [<Import("Cause", "next/font/google")>]
        static member Cause(options: obj) : LoadedFont = jsNative

        [<Import("Caveat", "next/font/google")>]
        static member Caveat(options: obj) : LoadedFont = jsNative

        [<Import("Caveat_Brush", "next/font/google")>]
        static member Caveat_Brush(options: obj) : LoadedFont = jsNative

        [<Import("Cedarville_Cursive", "next/font/google")>]
        static member Cedarville_Cursive(options: obj) : LoadedFont = jsNative

        [<Import("Ceviche_One", "next/font/google")>]
        static member Ceviche_One(options: obj) : LoadedFont = jsNative

        [<Import("Chakra_Petch", "next/font/google")>]
        static member Chakra_Petch(options: obj) : LoadedFont = jsNative

        [<Import("Changa", "next/font/google")>]
        static member Changa(options: obj) : LoadedFont = jsNative

        [<Import("Changa_One", "next/font/google")>]
        static member Changa_One(options: obj) : LoadedFont = jsNative

        [<Import("Chango", "next/font/google")>]
        static member Chango(options: obj) : LoadedFont = jsNative

        [<Import("Charis_SIL", "next/font/google")>]
        static member Charis_SIL(options: obj) : LoadedFont = jsNative

        [<Import("Charm", "next/font/google")>]
        static member Charm(options: obj) : LoadedFont = jsNative

        [<Import("Charmonman", "next/font/google")>]
        static member Charmonman(options: obj) : LoadedFont = jsNative

        [<Import("Chathura", "next/font/google")>]
        static member Chathura(options: obj) : LoadedFont = jsNative

        [<Import("Chau_Philomene_One", "next/font/google")>]
        static member Chau_Philomene_One(options: obj) : LoadedFont = jsNative

        [<Import("Chela_One", "next/font/google")>]
        static member Chela_One(options: obj) : LoadedFont = jsNative

        [<Import("Chelsea_Market", "next/font/google")>]
        static member Chelsea_Market(options: obj) : LoadedFont = jsNative

        [<Import("Chenla", "next/font/google")>]
        static member Chenla(options: obj) : LoadedFont = jsNative

        [<Import("Cherish", "next/font/google")>]
        static member Cherish(options: obj) : LoadedFont = jsNative

        [<Import("Cherry_Bomb_One", "next/font/google")>]
        static member Cherry_Bomb_One(options: obj) : LoadedFont = jsNative

        [<Import("Cherry_Cream_Soda", "next/font/google")>]
        static member Cherry_Cream_Soda(options: obj) : LoadedFont = jsNative

        [<Import("Cherry_Swash", "next/font/google")>]
        static member Cherry_Swash(options: obj) : LoadedFont = jsNative

        [<Import("Chewy", "next/font/google")>]
        static member Chewy(options: obj) : LoadedFont = jsNative

        [<Import("Chicle", "next/font/google")>]
        static member Chicle(options: obj) : LoadedFont = jsNative

        [<Import("Chilanka", "next/font/google")>]
        static member Chilanka(options: obj) : LoadedFont = jsNative

        [<Import("Chiron_GoRound_TC", "next/font/google")>]
        static member Chiron_GoRound_TC(options: obj) : LoadedFont = jsNative

        [<Import("Chiron_Hei_HK", "next/font/google")>]
        static member Chiron_Hei_HK(options: obj) : LoadedFont = jsNative

        [<Import("Chiron_Sung_HK", "next/font/google")>]
        static member Chiron_Sung_HK(options: obj) : LoadedFont = jsNative

        [<Import("Chivo", "next/font/google")>]
        static member Chivo(options: obj) : LoadedFont = jsNative

        [<Import("Chivo_Mono", "next/font/google")>]
        static member Chivo_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Chocolate_Classical_Sans", "next/font/google")>]
        static member Chocolate_Classical_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Chokokutai", "next/font/google")>]
        static member Chokokutai(options: obj) : LoadedFont = jsNative

        [<Import("Chonburi", "next/font/google")>]
        static member Chonburi(options: obj) : LoadedFont = jsNative

        [<Import("Cinzel", "next/font/google")>]
        static member Cinzel(options: obj) : LoadedFont = jsNative

        [<Import("Cinzel_Decorative", "next/font/google")>]
        static member Cinzel_Decorative(options: obj) : LoadedFont = jsNative

        [<Import("Clicker_Script", "next/font/google")>]
        static member Clicker_Script(options: obj) : LoadedFont = jsNative

        [<Import("Climate_Crisis", "next/font/google")>]
        static member Climate_Crisis(options: obj) : LoadedFont = jsNative

