namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk38 =
    type GoogleFont with
        [<Import("Tiro_Devanagari_Marathi", "next/font/google")>]
        static member Tiro_Devanagari_Marathi(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Devanagari_Sanskrit", "next/font/google")>]
        static member Tiro_Devanagari_Sanskrit(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Gurmukhi", "next/font/google")>]
        static member Tiro_Gurmukhi(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Kannada", "next/font/google")>]
        static member Tiro_Kannada(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Tamil", "next/font/google")>]
        static member Tiro_Tamil(options: obj) : LoadedFont = jsNative

        [<Import("Tiro_Telugu", "next/font/google")>]
        static member Tiro_Telugu(options: obj) : LoadedFont = jsNative

        [<Import("Tirra", "next/font/google")>]
        static member Tirra(options: obj) : LoadedFont = jsNative

        [<Import("Titan_One", "next/font/google")>]
        static member Titan_One(options: obj) : LoadedFont = jsNative

        [<Import("Titillium_Web", "next/font/google")>]
        static member Titillium_Web(options: obj) : LoadedFont = jsNative

        [<Import("Tomorrow", "next/font/google")>]
        static member Tomorrow(options: obj) : LoadedFont = jsNative

        [<Import("Tourney", "next/font/google")>]
        static member Tourney(options: obj) : LoadedFont = jsNative

        [<Import("Trade_Winds", "next/font/google")>]
        static member Trade_Winds(options: obj) : LoadedFont = jsNative

        [<Import("Train_One", "next/font/google")>]
        static member Train_One(options: obj) : LoadedFont = jsNative

        [<Import("Triodion", "next/font/google")>]
        static member Triodion(options: obj) : LoadedFont = jsNative

        [<Import("Trirong", "next/font/google")>]
        static member Trirong(options: obj) : LoadedFont = jsNative

        [<Import("Trispace", "next/font/google")>]
        static member Trispace(options: obj) : LoadedFont = jsNative

        [<Import("Trocchi", "next/font/google")>]
        static member Trocchi(options: obj) : LoadedFont = jsNative

        [<Import("Trochut", "next/font/google")>]
        static member Trochut(options: obj) : LoadedFont = jsNative

        [<Import("Truculenta", "next/font/google")>]
        static member Truculenta(options: obj) : LoadedFont = jsNative

        [<Import("Trykker", "next/font/google")>]
        static member Trykker(options: obj) : LoadedFont = jsNative

        [<Import("Tsukimi_Rounded", "next/font/google")>]
        static member Tsukimi_Rounded(options: obj) : LoadedFont = jsNative

        [<Import("Tuffy", "next/font/google")>]
        static member Tuffy(options: obj) : LoadedFont = jsNative

        [<Import("Tulpen_One", "next/font/google")>]
        static member Tulpen_One(options: obj) : LoadedFont = jsNative

        [<Import("Turret_Road", "next/font/google")>]
        static member Turret_Road(options: obj) : LoadedFont = jsNative

        [<Import("Twinkle_Star", "next/font/google")>]
        static member Twinkle_Star(options: obj) : LoadedFont = jsNative

        [<Import("Ubuntu", "next/font/google")>]
        static member Ubuntu(options: obj) : LoadedFont = jsNative

        [<Import("Ubuntu_Condensed", "next/font/google")>]
        static member Ubuntu_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Ubuntu_Mono", "next/font/google")>]
        static member Ubuntu_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Ubuntu_Sans", "next/font/google")>]
        static member Ubuntu_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Ubuntu_Sans_Mono", "next/font/google")>]
        static member Ubuntu_Sans_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Uchen", "next/font/google")>]
        static member Uchen(options: obj) : LoadedFont = jsNative

        [<Import("Ultra", "next/font/google")>]
        static member Ultra(options: obj) : LoadedFont = jsNative

        [<Import("Unbounded", "next/font/google")>]
        static member Unbounded(options: obj) : LoadedFont = jsNative

        [<Import("Uncial_Antiqua", "next/font/google")>]
        static member Uncial_Antiqua(options: obj) : LoadedFont = jsNative

        [<Import("Underdog", "next/font/google")>]
        static member Underdog(options: obj) : LoadedFont = jsNative

        [<Import("Unica_One", "next/font/google")>]
        static member Unica_One(options: obj) : LoadedFont = jsNative

        [<Import("UnifrakturCook", "next/font/google")>]
        static member UnifrakturCook(options: obj) : LoadedFont = jsNative

        [<Import("UnifrakturMaguntia", "next/font/google")>]
        static member UnifrakturMaguntia(options: obj) : LoadedFont = jsNative

        [<Import("Unkempt", "next/font/google")>]
        static member Unkempt(options: obj) : LoadedFont = jsNative

        [<Import("Unlock", "next/font/google")>]
        static member Unlock(options: obj) : LoadedFont = jsNative

        [<Import("Unna", "next/font/google")>]
        static member Unna(options: obj) : LoadedFont = jsNative

        [<Import("UoqMunThenKhung", "next/font/google")>]
        static member UoqMunThenKhung(options: obj) : LoadedFont = jsNative

        [<Import("Updock", "next/font/google")>]
        static member Updock(options: obj) : LoadedFont = jsNative

        [<Import("Urbanist", "next/font/google")>]
        static member Urbanist(options: obj) : LoadedFont = jsNative

        [<Import("VT323", "next/font/google")>]
        static member VT323(options: obj) : LoadedFont = jsNative

        [<Import("Vampiro_One", "next/font/google")>]
        static member Vampiro_One(options: obj) : LoadedFont = jsNative

        [<Import("Varela", "next/font/google")>]
        static member Varela(options: obj) : LoadedFont = jsNative

        [<Import("Varela_Round", "next/font/google")>]
        static member Varela_Round(options: obj) : LoadedFont = jsNative

