namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk02 =
    type GoogleFont with
        [<Import("Allura", "next/font/google")>]
        static member Allura(options: obj) : LoadedFont = jsNative

        [<Import("Almarai", "next/font/google")>]
        static member Almarai(options: obj) : LoadedFont = jsNative

        [<Import("Almendra", "next/font/google")>]
        static member Almendra(options: obj) : LoadedFont = jsNative

        [<Import("Almendra_Display", "next/font/google")>]
        static member Almendra_Display(options: obj) : LoadedFont = jsNative

        [<Import("Almendra_SC", "next/font/google")>]
        static member Almendra_SC(options: obj) : LoadedFont = jsNative

        [<Import("Alumni_Sans", "next/font/google")>]
        static member Alumni_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Alumni_Sans_Collegiate_One", "next/font/google")>]
        static member Alumni_Sans_Collegiate_One(options: obj) : LoadedFont = jsNative

        [<Import("Alumni_Sans_Inline_One", "next/font/google")>]
        static member Alumni_Sans_Inline_One(options: obj) : LoadedFont = jsNative

        [<Import("Alumni_Sans_Pinstripe", "next/font/google")>]
        static member Alumni_Sans_Pinstripe(options: obj) : LoadedFont = jsNative

        [<Import("Alumni_Sans_SC", "next/font/google")>]
        static member Alumni_Sans_SC(options: obj) : LoadedFont = jsNative

        [<Import("Amarante", "next/font/google")>]
        static member Amarante(options: obj) : LoadedFont = jsNative

        [<Import("Amaranth", "next/font/google")>]
        static member Amaranth(options: obj) : LoadedFont = jsNative

        [<Import("Amarna", "next/font/google")>]
        static member Amarna(options: obj) : LoadedFont = jsNative

        [<Import("Amatic_SC", "next/font/google")>]
        static member Amatic_SC(options: obj) : LoadedFont = jsNative

        [<Import("Amethysta", "next/font/google")>]
        static member Amethysta(options: obj) : LoadedFont = jsNative

        [<Import("Amiko", "next/font/google")>]
        static member Amiko(options: obj) : LoadedFont = jsNative

        [<Import("Amiri", "next/font/google")>]
        static member Amiri(options: obj) : LoadedFont = jsNative

        [<Import("Amiri_Quran", "next/font/google")>]
        static member Amiri_Quran(options: obj) : LoadedFont = jsNative

        [<Import("Amita", "next/font/google")>]
        static member Amita(options: obj) : LoadedFont = jsNative

        [<Import("Anaheim", "next/font/google")>]
        static member Anaheim(options: obj) : LoadedFont = jsNative

        [<Import("Ancizar_Sans", "next/font/google")>]
        static member Ancizar_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Ancizar_Serif", "next/font/google")>]
        static member Ancizar_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Andada_Pro", "next/font/google")>]
        static member Andada_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Andika", "next/font/google")>]
        static member Andika(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Bangla", "next/font/google")>]
        static member Anek_Bangla(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Devanagari", "next/font/google")>]
        static member Anek_Devanagari(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Gujarati", "next/font/google")>]
        static member Anek_Gujarati(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Gurmukhi", "next/font/google")>]
        static member Anek_Gurmukhi(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Kannada", "next/font/google")>]
        static member Anek_Kannada(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Latin", "next/font/google")>]
        static member Anek_Latin(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Malayalam", "next/font/google")>]
        static member Anek_Malayalam(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Odia", "next/font/google")>]
        static member Anek_Odia(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Tamil", "next/font/google")>]
        static member Anek_Tamil(options: obj) : LoadedFont = jsNative

        [<Import("Anek_Telugu", "next/font/google")>]
        static member Anek_Telugu(options: obj) : LoadedFont = jsNative

        [<Import("Angkor", "next/font/google")>]
        static member Angkor(options: obj) : LoadedFont = jsNative

        [<Import("Annapurna_SIL", "next/font/google")>]
        static member Annapurna_SIL(options: obj) : LoadedFont = jsNative

        [<Import("Annie_Use_Your_Telescope", "next/font/google")>]
        static member Annie_Use_Your_Telescope(options: obj) : LoadedFont = jsNative

        [<Import("Anonymous_Pro", "next/font/google")>]
        static member Anonymous_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Anta", "next/font/google")>]
        static member Anta(options: obj) : LoadedFont = jsNative

        [<Import("Antic", "next/font/google")>]
        static member Antic(options: obj) : LoadedFont = jsNative

        [<Import("Antic_Didone", "next/font/google")>]
        static member Antic_Didone(options: obj) : LoadedFont = jsNative

        [<Import("Antic_Slab", "next/font/google")>]
        static member Antic_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Anton", "next/font/google")>]
        static member Anton(options: obj) : LoadedFont = jsNative

        [<Import("Anton_SC", "next/font/google")>]
        static member Anton_SC(options: obj) : LoadedFont = jsNative

        [<Import("Antonio", "next/font/google")>]
        static member Antonio(options: obj) : LoadedFont = jsNative

        [<Import("Anuphan", "next/font/google")>]
        static member Anuphan(options: obj) : LoadedFont = jsNative

        [<Import("Anybody", "next/font/google")>]
        static member Anybody(options: obj) : LoadedFont = jsNative

        [<Import("Aoboshi_One", "next/font/google")>]
        static member Aoboshi_One(options: obj) : LoadedFont = jsNative

