namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk36 =
    type GoogleFont with
        [<Import("Solitreo", "next/font/google")>]
        static member Solitreo(options: obj) : LoadedFont = jsNative

        [<Import("Solway", "next/font/google")>]
        static member Solway(options: obj) : LoadedFont = jsNative

        [<Import("Sometype_Mono", "next/font/google")>]
        static member Sometype_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Song_Myung", "next/font/google")>]
        static member Song_Myung(options: obj) : LoadedFont = jsNative

        [<Import("Sono", "next/font/google")>]
        static member Sono(options: obj) : LoadedFont = jsNative

        [<Import("Sonsie_One", "next/font/google")>]
        static member Sonsie_One(options: obj) : LoadedFont = jsNative

        [<Import("Sora", "next/font/google")>]
        static member Sora(options: obj) : LoadedFont = jsNative

        [<Import("Sorts_Mill_Goudy", "next/font/google")>]
        static member Sorts_Mill_Goudy(options: obj) : LoadedFont = jsNative

        [<Import("Sour_Gummy", "next/font/google")>]
        static member Sour_Gummy(options: obj) : LoadedFont = jsNative

        [<Import("Source_Code_Pro", "next/font/google")>]
        static member Source_Code_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Source_Sans_3", "next/font/google")>]
        static member Source_Sans_3(options: obj) : LoadedFont = jsNative

        [<Import("Source_Serif_4", "next/font/google")>]
        static member Source_Serif_4(options: obj) : LoadedFont = jsNative

        [<Import("Space_Grotesk", "next/font/google")>]
        static member Space_Grotesk(options: obj) : LoadedFont = jsNative

        [<Import("Space_Mono", "next/font/google")>]
        static member Space_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Special_Elite", "next/font/google")>]
        static member Special_Elite(options: obj) : LoadedFont = jsNative

        [<Import("Special_Gothic", "next/font/google")>]
        static member Special_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Special_Gothic_Condensed_One", "next/font/google")>]
        static member Special_Gothic_Condensed_One(options: obj) : LoadedFont = jsNative

        [<Import("Special_Gothic_Expanded_One", "next/font/google")>]
        static member Special_Gothic_Expanded_One(options: obj) : LoadedFont = jsNative

        [<Import("Spectral", "next/font/google")>]
        static member Spectral(options: obj) : LoadedFont = jsNative

        [<Import("Spectral_SC", "next/font/google")>]
        static member Spectral_SC(options: obj) : LoadedFont = jsNative

        [<Import("Spicy_Rice", "next/font/google")>]
        static member Spicy_Rice(options: obj) : LoadedFont = jsNative

        [<Import("Spinnaker", "next/font/google")>]
        static member Spinnaker(options: obj) : LoadedFont = jsNative

        [<Import("Spirax", "next/font/google")>]
        static member Spirax(options: obj) : LoadedFont = jsNative

        [<Import("Splash", "next/font/google")>]
        static member Splash(options: obj) : LoadedFont = jsNative

        [<Import("Spline_Sans", "next/font/google")>]
        static member Spline_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Spline_Sans_Mono", "next/font/google")>]
        static member Spline_Sans_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Squada_One", "next/font/google")>]
        static member Squada_One(options: obj) : LoadedFont = jsNative

        [<Import("Square_Peg", "next/font/google")>]
        static member Square_Peg(options: obj) : LoadedFont = jsNative

        [<Import("Sree_Krushnadevaraya", "next/font/google")>]
        static member Sree_Krushnadevaraya(options: obj) : LoadedFont = jsNative

        [<Import("Sriracha", "next/font/google")>]
        static member Sriracha(options: obj) : LoadedFont = jsNative

        [<Import("Srisakdi", "next/font/google")>]
        static member Srisakdi(options: obj) : LoadedFont = jsNative

        [<Import("Staatliches", "next/font/google")>]
        static member Staatliches(options: obj) : LoadedFont = jsNative

        [<Import("Stack_Sans_Headline", "next/font/google")>]
        static member Stack_Sans_Headline(options: obj) : LoadedFont = jsNative

        [<Import("Stack_Sans_Notch", "next/font/google")>]
        static member Stack_Sans_Notch(options: obj) : LoadedFont = jsNative

        [<Import("Stack_Sans_Text", "next/font/google")>]
        static member Stack_Sans_Text(options: obj) : LoadedFont = jsNative

        [<Import("Stalemate", "next/font/google")>]
        static member Stalemate(options: obj) : LoadedFont = jsNative

        [<Import("Stalinist_One", "next/font/google")>]
        static member Stalinist_One(options: obj) : LoadedFont = jsNative

        [<Import("Stardos_Stencil", "next/font/google")>]
        static member Stardos_Stencil(options: obj) : LoadedFont = jsNative

        [<Import("Stick", "next/font/google")>]
        static member Stick(options: obj) : LoadedFont = jsNative

        [<Import("Stick_No_Bills", "next/font/google")>]
        static member Stick_No_Bills(options: obj) : LoadedFont = jsNative

        [<Import("Stint_Ultra_Condensed", "next/font/google")>]
        static member Stint_Ultra_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Stint_Ultra_Expanded", "next/font/google")>]
        static member Stint_Ultra_Expanded(options: obj) : LoadedFont = jsNative

        [<Import("Stoke", "next/font/google")>]
        static member Stoke(options: obj) : LoadedFont = jsNative

        [<Import("Story_Script", "next/font/google")>]
        static member Story_Script(options: obj) : LoadedFont = jsNative

        [<Import("Strait", "next/font/google")>]
        static member Strait(options: obj) : LoadedFont = jsNative

        [<Import("Style_Script", "next/font/google")>]
        static member Style_Script(options: obj) : LoadedFont = jsNative

        [<Import("Stylish", "next/font/google")>]
        static member Stylish(options: obj) : LoadedFont = jsNative

        [<Import("Sue_Ellen_Francisco", "next/font/google")>]
        static member Sue_Ellen_Francisco(options: obj) : LoadedFont = jsNative

