namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk33 =
    type GoogleFont with
        [<Import("Rochester", "next/font/google")>]
        static member Rochester(options: obj) : LoadedFont = jsNative

        [<Import("Rock_3D", "next/font/google")>]
        static member Rock_3D(options: obj) : LoadedFont = jsNative

        [<Import("Rock_Salt", "next/font/google")>]
        static member Rock_Salt(options: obj) : LoadedFont = jsNative

        [<Import("RocknRoll_One", "next/font/google")>]
        static member RocknRoll_One(options: obj) : LoadedFont = jsNative

        [<Import("Rokkitt", "next/font/google")>]
        static member Rokkitt(options: obj) : LoadedFont = jsNative

        [<Import("Romanesco", "next/font/google")>]
        static member Romanesco(options: obj) : LoadedFont = jsNative

        [<Import("Ropa_Sans", "next/font/google")>]
        static member Ropa_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Rosario", "next/font/google")>]
        static member Rosario(options: obj) : LoadedFont = jsNative

        [<Import("Rosarivo", "next/font/google")>]
        static member Rosarivo(options: obj) : LoadedFont = jsNative

        [<Import("Rouge_Script", "next/font/google")>]
        static member Rouge_Script(options: obj) : LoadedFont = jsNative

        [<Import("Rowdies", "next/font/google")>]
        static member Rowdies(options: obj) : LoadedFont = jsNative

        [<Import("Rozha_One", "next/font/google")>]
        static member Rozha_One(options: obj) : LoadedFont = jsNative

        [<Import("Rubik", "next/font/google")>]
        static member Rubik(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_80s_Fade", "next/font/google")>]
        static member Rubik_80s_Fade(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Beastly", "next/font/google")>]
        static member Rubik_Beastly(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Broken_Fax", "next/font/google")>]
        static member Rubik_Broken_Fax(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Bubbles", "next/font/google")>]
        static member Rubik_Bubbles(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Burned", "next/font/google")>]
        static member Rubik_Burned(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Dirt", "next/font/google")>]
        static member Rubik_Dirt(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Distressed", "next/font/google")>]
        static member Rubik_Distressed(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Doodle_Shadow", "next/font/google")>]
        static member Rubik_Doodle_Shadow(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Doodle_Triangles", "next/font/google")>]
        static member Rubik_Doodle_Triangles(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Gemstones", "next/font/google")>]
        static member Rubik_Gemstones(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Glitch", "next/font/google")>]
        static member Rubik_Glitch(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Glitch_Pop", "next/font/google")>]
        static member Rubik_Glitch_Pop(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Iso", "next/font/google")>]
        static member Rubik_Iso(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Lines", "next/font/google")>]
        static member Rubik_Lines(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Maps", "next/font/google")>]
        static member Rubik_Maps(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Marker_Hatch", "next/font/google")>]
        static member Rubik_Marker_Hatch(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Maze", "next/font/google")>]
        static member Rubik_Maze(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Microbe", "next/font/google")>]
        static member Rubik_Microbe(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Mono_One", "next/font/google")>]
        static member Rubik_Mono_One(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Moonrocks", "next/font/google")>]
        static member Rubik_Moonrocks(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Pixels", "next/font/google")>]
        static member Rubik_Pixels(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Puddles", "next/font/google")>]
        static member Rubik_Puddles(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Scribble", "next/font/google")>]
        static member Rubik_Scribble(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Spray_Paint", "next/font/google")>]
        static member Rubik_Spray_Paint(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Storm", "next/font/google")>]
        static member Rubik_Storm(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Vinyl", "next/font/google")>]
        static member Rubik_Vinyl(options: obj) : LoadedFont = jsNative

        [<Import("Rubik_Wet_Paint", "next/font/google")>]
        static member Rubik_Wet_Paint(options: obj) : LoadedFont = jsNative

        [<Import("Ruda", "next/font/google")>]
        static member Ruda(options: obj) : LoadedFont = jsNative

        [<Import("Rufina", "next/font/google")>]
        static member Rufina(options: obj) : LoadedFont = jsNative

        [<Import("Ruge_Boogie", "next/font/google")>]
        static member Ruge_Boogie(options: obj) : LoadedFont = jsNative

        [<Import("Ruluko", "next/font/google")>]
        static member Ruluko(options: obj) : LoadedFont = jsNative

        [<Import("Rum_Raisin", "next/font/google")>]
        static member Rum_Raisin(options: obj) : LoadedFont = jsNative

        [<Import("Ruslan_Display", "next/font/google")>]
        static member Ruslan_Display(options: obj) : LoadedFont = jsNative

        [<Import("Russo_One", "next/font/google")>]
        static member Russo_One(options: obj) : LoadedFont = jsNative

        [<Import("Ruthie", "next/font/google")>]
        static member Ruthie(options: obj) : LoadedFont = jsNative

