namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk03 =
    type GoogleFont with
        [<Import("Arapey", "next/font/google")>]
        static member Arapey(options: obj) : LoadedFont = jsNative

        [<Import("Arbutus", "next/font/google")>]
        static member Arbutus(options: obj) : LoadedFont = jsNative

        [<Import("Arbutus_Slab", "next/font/google")>]
        static member Arbutus_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Architects_Daughter", "next/font/google")>]
        static member Architects_Daughter(options: obj) : LoadedFont = jsNative

        [<Import("Archivo", "next/font/google")>]
        static member Archivo(options: obj) : LoadedFont = jsNative

        [<Import("Archivo_Black", "next/font/google")>]
        static member Archivo_Black(options: obj) : LoadedFont = jsNative

        [<Import("Archivo_Narrow", "next/font/google")>]
        static member Archivo_Narrow(options: obj) : LoadedFont = jsNative

        [<Import("Are_You_Serious", "next/font/google")>]
        static member Are_You_Serious(options: obj) : LoadedFont = jsNative

        [<Import("Aref_Ruqaa", "next/font/google")>]
        static member Aref_Ruqaa(options: obj) : LoadedFont = jsNative

        [<Import("Aref_Ruqaa_Ink", "next/font/google")>]
        static member Aref_Ruqaa_Ink(options: obj) : LoadedFont = jsNative

        [<Import("Arima", "next/font/google")>]
        static member Arima(options: obj) : LoadedFont = jsNative

        [<Import("Arimo", "next/font/google")>]
        static member Arimo(options: obj) : LoadedFont = jsNative

        [<Import("Arizonia", "next/font/google")>]
        static member Arizonia(options: obj) : LoadedFont = jsNative

        [<Import("Armata", "next/font/google")>]
        static member Armata(options: obj) : LoadedFont = jsNative

        [<Import("Arsenal", "next/font/google")>]
        static member Arsenal(options: obj) : LoadedFont = jsNative

        [<Import("Arsenal_SC", "next/font/google")>]
        static member Arsenal_SC(options: obj) : LoadedFont = jsNative

        [<Import("Artifika", "next/font/google")>]
        static member Artifika(options: obj) : LoadedFont = jsNative

        [<Import("Arvo", "next/font/google")>]
        static member Arvo(options: obj) : LoadedFont = jsNative

        [<Import("Arya", "next/font/google")>]
        static member Arya(options: obj) : LoadedFont = jsNative

        [<Import("Asap", "next/font/google")>]
        static member Asap(options: obj) : LoadedFont = jsNative

        [<Import("Asap_Condensed", "next/font/google")>]
        static member Asap_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Asar", "next/font/google")>]
        static member Asar(options: obj) : LoadedFont = jsNative

        [<Import("Asimovian", "next/font/google")>]
        static member Asimovian(options: obj) : LoadedFont = jsNative

        [<Import("Asset", "next/font/google")>]
        static member Asset(options: obj) : LoadedFont = jsNative

        [<Import("Assistant", "next/font/google")>]
        static member Assistant(options: obj) : LoadedFont = jsNative

        [<Import("Asta_Sans", "next/font/google")>]
        static member Asta_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Astloch", "next/font/google")>]
        static member Astloch(options: obj) : LoadedFont = jsNative

        [<Import("Asul", "next/font/google")>]
        static member Asul(options: obj) : LoadedFont = jsNative

        [<Import("Athiti", "next/font/google")>]
        static member Athiti(options: obj) : LoadedFont = jsNative

        [<Import("Atkinson_Hyperlegible", "next/font/google")>]
        static member Atkinson_Hyperlegible(options: obj) : LoadedFont = jsNative

        [<Import("Atkinson_Hyperlegible_Mono", "next/font/google")>]
        static member Atkinson_Hyperlegible_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Atkinson_Hyperlegible_Next", "next/font/google")>]
        static member Atkinson_Hyperlegible_Next(options: obj) : LoadedFont = jsNative

        [<Import("Atma", "next/font/google")>]
        static member Atma(options: obj) : LoadedFont = jsNative

        [<Import("Atomic_Age", "next/font/google")>]
        static member Atomic_Age(options: obj) : LoadedFont = jsNative

        [<Import("Aubrey", "next/font/google")>]
        static member Aubrey(options: obj) : LoadedFont = jsNative

        [<Import("Audiowide", "next/font/google")>]
        static member Audiowide(options: obj) : LoadedFont = jsNative

        [<Import("Autour_One", "next/font/google")>]
        static member Autour_One(options: obj) : LoadedFont = jsNative

        [<Import("Average", "next/font/google")>]
        static member Average(options: obj) : LoadedFont = jsNative

        [<Import("Average_Sans", "next/font/google")>]
        static member Average_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Averia_Gruesa_Libre", "next/font/google")>]
        static member Averia_Gruesa_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Averia_Libre", "next/font/google")>]
        static member Averia_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Averia_Sans_Libre", "next/font/google")>]
        static member Averia_Sans_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Averia_Serif_Libre", "next/font/google")>]
        static member Averia_Serif_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Azeret_Mono", "next/font/google")>]
        static member Azeret_Mono(options: obj) : LoadedFont = jsNative

        [<Import("B612", "next/font/google")>]
        static member B612(options: obj) : LoadedFont = jsNative

        [<Import("B612_Mono", "next/font/google")>]
        static member B612_Mono(options: obj) : LoadedFont = jsNative

        [<Import("BBH_Bartle", "next/font/google")>]
        static member BBH_Bartle(options: obj) : LoadedFont = jsNative

        [<Import("BBH_Bogle", "next/font/google")>]
        static member BBH_Bogle(options: obj) : LoadedFont = jsNative

