namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk30 =
    type GoogleFont with
        [<Import("Playwrite_HR_Lijeva_Guides", "next/font/google")>]
        static member Playwrite_HR_Lijeva_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_HU", "next/font/google")>]
        static member Playwrite_HU(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_HU_Guides", "next/font/google")>]
        static member Playwrite_HU_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ID", "next/font/google")>]
        static member Playwrite_ID(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ID_Guides", "next/font/google")>]
        static member Playwrite_ID_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IE", "next/font/google")>]
        static member Playwrite_IE(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IE_Guides", "next/font/google")>]
        static member Playwrite_IE_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IN", "next/font/google")>]
        static member Playwrite_IN(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IN_Guides", "next/font/google")>]
        static member Playwrite_IN_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IS", "next/font/google")>]
        static member Playwrite_IS(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IS_Guides", "next/font/google")>]
        static member Playwrite_IS_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IT_Moderna", "next/font/google")>]
        static member Playwrite_IT_Moderna(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IT_Moderna_Guides", "next/font/google")>]
        static member Playwrite_IT_Moderna_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IT_Trad", "next/font/google")>]
        static member Playwrite_IT_Trad(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_IT_Trad_Guides", "next/font/google")>]
        static member Playwrite_IT_Trad_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_MX", "next/font/google")>]
        static member Playwrite_MX(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_MX_Guides", "next/font/google")>]
        static member Playwrite_MX_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NG_Modern", "next/font/google")>]
        static member Playwrite_NG_Modern(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NG_Modern_Guides", "next/font/google")>]
        static member Playwrite_NG_Modern_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NL", "next/font/google")>]
        static member Playwrite_NL(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NL_Guides", "next/font/google")>]
        static member Playwrite_NL_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NO", "next/font/google")>]
        static member Playwrite_NO(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NO_Guides", "next/font/google")>]
        static member Playwrite_NO_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NZ", "next/font/google")>]
        static member Playwrite_NZ(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NZ_Basic", "next/font/google")>]
        static member Playwrite_NZ_Basic(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NZ_Basic_Guides", "next/font/google")>]
        static member Playwrite_NZ_Basic_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_NZ_Guides", "next/font/google")>]
        static member Playwrite_NZ_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_PE", "next/font/google")>]
        static member Playwrite_PE(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_PE_Guides", "next/font/google")>]
        static member Playwrite_PE_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_PL", "next/font/google")>]
        static member Playwrite_PL(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_PL_Guides", "next/font/google")>]
        static member Playwrite_PL_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_PT", "next/font/google")>]
        static member Playwrite_PT(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_PT_Guides", "next/font/google")>]
        static member Playwrite_PT_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_RO", "next/font/google")>]
        static member Playwrite_RO(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_RO_Guides", "next/font/google")>]
        static member Playwrite_RO_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_SK", "next/font/google")>]
        static member Playwrite_SK(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_SK_Guides", "next/font/google")>]
        static member Playwrite_SK_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_TZ", "next/font/google")>]
        static member Playwrite_TZ(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_TZ_Guides", "next/font/google")>]
        static member Playwrite_TZ_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_US_Modern", "next/font/google")>]
        static member Playwrite_US_Modern(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_US_Modern_Guides", "next/font/google")>]
        static member Playwrite_US_Modern_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_US_Trad", "next/font/google")>]
        static member Playwrite_US_Trad(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_US_Trad_Guides", "next/font/google")>]
        static member Playwrite_US_Trad_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_VN", "next/font/google")>]
        static member Playwrite_VN(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_VN_Guides", "next/font/google")>]
        static member Playwrite_VN_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ZA", "next/font/google")>]
        static member Playwrite_ZA(options: obj) : LoadedFont = jsNative

        [<Import("Playwrite_ZA_Guides", "next/font/google")>]
        static member Playwrite_ZA_Guides(options: obj) : LoadedFont = jsNative

        [<Import("Plus_Jakarta_Sans", "next/font/google")>]
        static member Plus_Jakarta_Sans(options: obj) : LoadedFont = jsNative

