namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk40 =
    type GoogleFont with
        [<Import("Yatra_One", "next/font/google")>]
        static member Yatra_One(options: obj) : LoadedFont = jsNative

        [<Import("Yellowtail", "next/font/google")>]
        static member Yellowtail(options: obj) : LoadedFont = jsNative

        [<Import("Yeon_Sung", "next/font/google")>]
        static member Yeon_Sung(options: obj) : LoadedFont = jsNative

        [<Import("Yeseva_One", "next/font/google")>]
        static member Yeseva_One(options: obj) : LoadedFont = jsNative

        [<Import("Yesteryear", "next/font/google")>]
        static member Yesteryear(options: obj) : LoadedFont = jsNative

        [<Import("Yomogi", "next/font/google")>]
        static member Yomogi(options: obj) : LoadedFont = jsNative

        [<Import("Young_Serif", "next/font/google")>]
        static member Young_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Yrsa", "next/font/google")>]
        static member Yrsa(options: obj) : LoadedFont = jsNative

        [<Import("Ysabeau", "next/font/google")>]
        static member Ysabeau(options: obj) : LoadedFont = jsNative

        [<Import("Ysabeau_Infant", "next/font/google")>]
        static member Ysabeau_Infant(options: obj) : LoadedFont = jsNative

        [<Import("Ysabeau_Office", "next/font/google")>]
        static member Ysabeau_Office(options: obj) : LoadedFont = jsNative

        [<Import("Ysabeau_SC", "next/font/google")>]
        static member Ysabeau_SC(options: obj) : LoadedFont = jsNative

        [<Import("Yuji_Boku", "next/font/google")>]
        static member Yuji_Boku(options: obj) : LoadedFont = jsNative

        [<Import("Yuji_Hentaigana_Akari", "next/font/google")>]
        static member Yuji_Hentaigana_Akari(options: obj) : LoadedFont = jsNative

        [<Import("Yuji_Hentaigana_Akebono", "next/font/google")>]
        static member Yuji_Hentaigana_Akebono(options: obj) : LoadedFont = jsNative

        [<Import("Yuji_Mai", "next/font/google")>]
        static member Yuji_Mai(options: obj) : LoadedFont = jsNative

        [<Import("Yuji_Syuku", "next/font/google")>]
        static member Yuji_Syuku(options: obj) : LoadedFont = jsNative

        [<Import("Yusei_Magic", "next/font/google")>]
        static member Yusei_Magic(options: obj) : LoadedFont = jsNative

        [<Import("ZCOOL_KuaiLe", "next/font/google")>]
        static member ZCOOL_KuaiLe(options: obj) : LoadedFont = jsNative

        [<Import("ZCOOL_QingKe_HuangYou", "next/font/google")>]
        static member ZCOOL_QingKe_HuangYou(options: obj) : LoadedFont = jsNative

        [<Import("ZCOOL_XiaoWei", "next/font/google")>]
        static member ZCOOL_XiaoWei(options: obj) : LoadedFont = jsNative

        [<Import("Zain", "next/font/google")>]
        static member Zain(options: obj) : LoadedFont = jsNative

        [<Import("Zalando_Sans", "next/font/google")>]
        static member Zalando_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Zalando_Sans_Expanded", "next/font/google")>]
        static member Zalando_Sans_Expanded(options: obj) : LoadedFont = jsNative

        [<Import("Zalando_Sans_SemiExpanded", "next/font/google")>]
        static member Zalando_Sans_SemiExpanded(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Antique", "next/font/google")>]
        static member Zen_Antique(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Antique_Soft", "next/font/google")>]
        static member Zen_Antique_Soft(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Dots", "next/font/google")>]
        static member Zen_Dots(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Kaku_Gothic_Antique", "next/font/google")>]
        static member Zen_Kaku_Gothic_Antique(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Kaku_Gothic_New", "next/font/google")>]
        static member Zen_Kaku_Gothic_New(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Kurenaido", "next/font/google")>]
        static member Zen_Kurenaido(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Loop", "next/font/google")>]
        static member Zen_Loop(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Maru_Gothic", "next/font/google")>]
        static member Zen_Maru_Gothic(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Old_Mincho", "next/font/google")>]
        static member Zen_Old_Mincho(options: obj) : LoadedFont = jsNative

        [<Import("Zen_Tokyo_Zoo", "next/font/google")>]
        static member Zen_Tokyo_Zoo(options: obj) : LoadedFont = jsNative

        [<Import("Zeyada", "next/font/google")>]
        static member Zeyada(options: obj) : LoadedFont = jsNative

        [<Import("Zhi_Mang_Xing", "next/font/google")>]
        static member Zhi_Mang_Xing(options: obj) : LoadedFont = jsNative

        [<Import("Zilla_Slab", "next/font/google")>]
        static member Zilla_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Zilla_Slab_Highlight", "next/font/google")>]
        static member Zilla_Slab_Highlight(options: obj) : LoadedFont = jsNative

