namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk27 =
    type GoogleFont with
        [<Import("Nunito_Sans", "next/font/google")>]
        static member Nunito_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Nuosu_SIL", "next/font/google")>]
        static member Nuosu_SIL(options: obj) : LoadedFont = jsNative

        [<Import("Odibee_Sans", "next/font/google")>]
        static member Odibee_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Odor_Mean_Chey", "next/font/google")>]
        static member Odor_Mean_Chey(options: obj) : LoadedFont = jsNative

        [<Import("Offside", "next/font/google")>]
        static member Offside(options: obj) : LoadedFont = jsNative

        [<Import("Oi", "next/font/google")>]
        static member Oi(options: obj) : LoadedFont = jsNative

        [<Import("Ojuju", "next/font/google")>]
        static member Ojuju(options: obj) : LoadedFont = jsNative

        [<Import("Old_Standard_TT", "next/font/google")>]
        static member Old_Standard_TT(options: obj) : LoadedFont = jsNative

        [<Import("Oldenburg", "next/font/google")>]
        static member Oldenburg(options: obj) : LoadedFont = jsNative

        [<Import("Ole", "next/font/google")>]
        static member Ole(options: obj) : LoadedFont = jsNative

        [<Import("Oleo_Script", "next/font/google")>]
        static member Oleo_Script(options: obj) : LoadedFont = jsNative

        [<Import("Oleo_Script_Swash_Caps", "next/font/google")>]
        static member Oleo_Script_Swash_Caps(options: obj) : LoadedFont = jsNative

        [<Import("Onest", "next/font/google")>]
        static member Onest(options: obj) : LoadedFont = jsNative

        [<Import("Oooh_Baby", "next/font/google")>]
        static member Oooh_Baby(options: obj) : LoadedFont = jsNative

        [<Import("Open_Sans", "next/font/google")>]
        static member Open_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Oranienbaum", "next/font/google")>]
        static member Oranienbaum(options: obj) : LoadedFont = jsNative

        [<Import("Orbit", "next/font/google")>]
        static member Orbit(options: obj) : LoadedFont = jsNative

        [<Import("Orbitron", "next/font/google")>]
        static member Orbitron(options: obj) : LoadedFont = jsNative

        [<Import("Oregano", "next/font/google")>]
        static member Oregano(options: obj) : LoadedFont = jsNative

        [<Import("Orelega_One", "next/font/google")>]
        static member Orelega_One(options: obj) : LoadedFont = jsNative

        [<Import("Orienta", "next/font/google")>]
        static member Orienta(options: obj) : LoadedFont = jsNative

        [<Import("Original_Surfer", "next/font/google")>]
        static member Original_Surfer(options: obj) : LoadedFont = jsNative

        [<Import("Oswald", "next/font/google")>]
        static member Oswald(options: obj) : LoadedFont = jsNative

        [<Import("Outfit", "next/font/google")>]
        static member Outfit(options: obj) : LoadedFont = jsNative

        [<Import("Over_the_Rainbow", "next/font/google")>]
        static member Over_the_Rainbow(options: obj) : LoadedFont = jsNative

        [<Import("Overlock", "next/font/google")>]
        static member Overlock(options: obj) : LoadedFont = jsNative

        [<Import("Overlock_SC", "next/font/google")>]
        static member Overlock_SC(options: obj) : LoadedFont = jsNative

        [<Import("Overpass", "next/font/google")>]
        static member Overpass(options: obj) : LoadedFont = jsNative

        [<Import("Overpass_Mono", "next/font/google")>]
        static member Overpass_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Ovo", "next/font/google")>]
        static member Ovo(options: obj) : LoadedFont = jsNative

        [<Import("Oxanium", "next/font/google")>]
        static member Oxanium(options: obj) : LoadedFont = jsNative

        [<Import("Oxygen", "next/font/google")>]
        static member Oxygen(options: obj) : LoadedFont = jsNative

        [<Import("Oxygen_Mono", "next/font/google")>]
        static member Oxygen_Mono(options: obj) : LoadedFont = jsNative

        [<Import("PT_Mono", "next/font/google")>]
        static member PT_Mono(options: obj) : LoadedFont = jsNative

        [<Import("PT_Sans", "next/font/google")>]
        static member PT_Sans(options: obj) : LoadedFont = jsNative

        [<Import("PT_Sans_Caption", "next/font/google")>]
        static member PT_Sans_Caption(options: obj) : LoadedFont = jsNative

        [<Import("PT_Sans_Narrow", "next/font/google")>]
        static member PT_Sans_Narrow(options: obj) : LoadedFont = jsNative

        [<Import("PT_Serif", "next/font/google")>]
        static member PT_Serif(options: obj) : LoadedFont = jsNative

        [<Import("PT_Serif_Caption", "next/font/google")>]
        static member PT_Serif_Caption(options: obj) : LoadedFont = jsNative

        [<Import("Pacifico", "next/font/google")>]
        static member Pacifico(options: obj) : LoadedFont = jsNative

        [<Import("Padauk", "next/font/google")>]
        static member Padauk(options: obj) : LoadedFont = jsNative

        [<Import("Padyakke_Expanded_One", "next/font/google")>]
        static member Padyakke_Expanded_One(options: obj) : LoadedFont = jsNative

        [<Import("Palanquin", "next/font/google")>]
        static member Palanquin(options: obj) : LoadedFont = jsNative

        [<Import("Palanquin_Dark", "next/font/google")>]
        static member Palanquin_Dark(options: obj) : LoadedFont = jsNative

        [<Import("Palette_Mosaic", "next/font/google")>]
        static member Palette_Mosaic(options: obj) : LoadedFont = jsNative

        [<Import("Pangolin", "next/font/google")>]
        static member Pangolin(options: obj) : LoadedFont = jsNative

        [<Import("Paprika", "next/font/google")>]
        static member Paprika(options: obj) : LoadedFont = jsNative

        [<Import("Parastoo", "next/font/google")>]
        static member Parastoo(options: obj) : LoadedFont = jsNative

