namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk18 =
    type GoogleFont with
        [<Import("Lexend_Mega", "next/font/google")>]
        static member Lexend_Mega(options: obj) : LoadedFont = jsNative

        [<Import("Lexend_Peta", "next/font/google")>]
        static member Lexend_Peta(options: obj) : LoadedFont = jsNative

        [<Import("Lexend_Tera", "next/font/google")>]
        static member Lexend_Tera(options: obj) : LoadedFont = jsNative

        [<Import("Lexend_Zetta", "next/font/google")>]
        static member Lexend_Zetta(options: obj) : LoadedFont = jsNative

        [<Import("Libertinus_Keyboard", "next/font/google")>]
        static member Libertinus_Keyboard(options: obj) : LoadedFont = jsNative

        [<Import("Libertinus_Math", "next/font/google")>]
        static member Libertinus_Math(options: obj) : LoadedFont = jsNative

        [<Import("Libertinus_Mono", "next/font/google")>]
        static member Libertinus_Mono(options: obj) : LoadedFont = jsNative

        [<Import("Libertinus_Sans", "next/font/google")>]
        static member Libertinus_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Libertinus_Serif", "next/font/google")>]
        static member Libertinus_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Libertinus_Serif_Display", "next/font/google")>]
        static member Libertinus_Serif_Display(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_128", "next/font/google")>]
        static member Libre_Barcode_128(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_128_Text", "next/font/google")>]
        static member Libre_Barcode_128_Text(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_39", "next/font/google")>]
        static member Libre_Barcode_39(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_39_Extended", "next/font/google")>]
        static member Libre_Barcode_39_Extended(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_39_Extended_Text", "next/font/google")>]
        static member Libre_Barcode_39_Extended_Text(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_39_Text", "next/font/google")>]
        static member Libre_Barcode_39_Text(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Barcode_EAN13_Text", "next/font/google")>]
        static member Libre_Barcode_EAN13_Text(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Baskerville", "next/font/google")>]
        static member Libre_Baskerville(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Bodoni", "next/font/google")>]
        static member Libre_Bodoni(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Caslon_Display", "next/font/google")>]
        static member Libre_Caslon_Display(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Caslon_Text", "next/font/google")>]
        static member Libre_Caslon_Text(options: obj) : LoadedFont = jsNative

        [<Import("Libre_Franklin", "next/font/google")>]
        static member Libre_Franklin(options: obj) : LoadedFont = jsNative

        [<Import("Licorice", "next/font/google")>]
        static member Licorice(options: obj) : LoadedFont = jsNative

        [<Import("Life_Savers", "next/font/google")>]
        static member Life_Savers(options: obj) : LoadedFont = jsNative

        [<Import("Lilex", "next/font/google")>]
        static member Lilex(options: obj) : LoadedFont = jsNative

        [<Import("Lilita_One", "next/font/google")>]
        static member Lilita_One(options: obj) : LoadedFont = jsNative

        [<Import("Lily_Script_One", "next/font/google")>]
        static member Lily_Script_One(options: obj) : LoadedFont = jsNative

        [<Import("Limelight", "next/font/google")>]
        static member Limelight(options: obj) : LoadedFont = jsNative

        [<Import("Linden_Hill", "next/font/google")>]
        static member Linden_Hill(options: obj) : LoadedFont = jsNative

        [<Import("Linefont", "next/font/google")>]
        static member Linefont(options: obj) : LoadedFont = jsNative

        [<Import("Lisu_Bosa", "next/font/google")>]
        static member Lisu_Bosa(options: obj) : LoadedFont = jsNative

        [<Import("Liter", "next/font/google")>]
        static member Liter(options: obj) : LoadedFont = jsNative

        [<Import("Literata", "next/font/google")>]
        static member Literata(options: obj) : LoadedFont = jsNative

        [<Import("Liu_Jian_Mao_Cao", "next/font/google")>]
        static member Liu_Jian_Mao_Cao(options: obj) : LoadedFont = jsNative

        [<Import("Livvic", "next/font/google")>]
        static member Livvic(options: obj) : LoadedFont = jsNative

        [<Import("Lobster", "next/font/google")>]
        static member Lobster(options: obj) : LoadedFont = jsNative

        [<Import("Lobster_Two", "next/font/google")>]
        static member Lobster_Two(options: obj) : LoadedFont = jsNative

        [<Import("Londrina_Outline", "next/font/google")>]
        static member Londrina_Outline(options: obj) : LoadedFont = jsNative

        [<Import("Londrina_Shadow", "next/font/google")>]
        static member Londrina_Shadow(options: obj) : LoadedFont = jsNative

        [<Import("Londrina_Sketch", "next/font/google")>]
        static member Londrina_Sketch(options: obj) : LoadedFont = jsNative

        [<Import("Londrina_Solid", "next/font/google")>]
        static member Londrina_Solid(options: obj) : LoadedFont = jsNative

        [<Import("Long_Cang", "next/font/google")>]
        static member Long_Cang(options: obj) : LoadedFont = jsNative

        [<Import("Lora", "next/font/google")>]
        static member Lora(options: obj) : LoadedFont = jsNative

        [<Import("Love_Light", "next/font/google")>]
        static member Love_Light(options: obj) : LoadedFont = jsNative

        [<Import("Love_Ya_Like_A_Sister", "next/font/google")>]
        static member Love_Ya_Like_A_Sister(options: obj) : LoadedFont = jsNative

        [<Import("Loved_by_the_King", "next/font/google")>]
        static member Loved_by_the_King(options: obj) : LoadedFont = jsNative

        [<Import("Lovers_Quarrel", "next/font/google")>]
        static member Lovers_Quarrel(options: obj) : LoadedFont = jsNative

        [<Import("Luckiest_Guy", "next/font/google")>]
        static member Luckiest_Guy(options: obj) : LoadedFont = jsNative

