namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk13 =
    type GoogleFont with
        [<Import("Google_Sans", "next/font/google")>]
        static member Google_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Google_Sans_Code", "next/font/google")>]
        static member Google_Sans_Code(options: obj) : LoadedFont = jsNative

        [<Import("Google_Sans_Flex", "next/font/google")>]
        static member Google_Sans_Flex(options: obj) : LoadedFont = jsNative

        [<Import("Gorditas", "next/font/google")>]
        static member Gorditas(options: obj) : LoadedFont = jsNative

        [<Import("Gothic_A1", "next/font/google")>]
        static member Gothic_A1(options: obj) : LoadedFont = jsNative

        [<Import("Gotu", "next/font/google")>]
        static member Gotu(options: obj) : LoadedFont = jsNative

        [<Import("Goudy_Bookletter_1911", "next/font/google")>]
        static member Goudy_Bookletter_1911(options: obj) : LoadedFont = jsNative

        [<Import("Gowun_Batang", "next/font/google")>]
        static member Gowun_Batang(options: obj) : LoadedFont = jsNative

        [<Import("Gowun_Dodum", "next/font/google")>]
        static member Gowun_Dodum(options: obj) : LoadedFont = jsNative

        [<Import("Graduate", "next/font/google")>]
        static member Graduate(options: obj) : LoadedFont = jsNative

        [<Import("Grand_Hotel", "next/font/google")>]
        static member Grand_Hotel(options: obj) : LoadedFont = jsNative

        [<Import("Grandiflora_One", "next/font/google")>]
        static member Grandiflora_One(options: obj) : LoadedFont = jsNative

        [<Import("Grandstander", "next/font/google")>]
        static member Grandstander(options: obj) : LoadedFont = jsNative

        [<Import("Grape_Nuts", "next/font/google")>]
        static member Grape_Nuts(options: obj) : LoadedFont = jsNative

        [<Import("Gravitas_One", "next/font/google")>]
        static member Gravitas_One(options: obj) : LoadedFont = jsNative

        [<Import("Great_Vibes", "next/font/google")>]
        static member Great_Vibes(options: obj) : LoadedFont = jsNative

        [<Import("Grechen_Fuemen", "next/font/google")>]
        static member Grechen_Fuemen(options: obj) : LoadedFont = jsNative

        [<Import("Grenze", "next/font/google")>]
        static member Grenze(options: obj) : LoadedFont = jsNative

        [<Import("Grenze_Gotisch", "next/font/google")>]
        static member Grenze_Gotisch(options: obj) : LoadedFont = jsNative

        [<Import("Grey_Qo", "next/font/google")>]
        static member Grey_Qo(options: obj) : LoadedFont = jsNative

        [<Import("Griffy", "next/font/google")>]
        static member Griffy(options: obj) : LoadedFont = jsNative

        [<Import("Gruppo", "next/font/google")>]
        static member Gruppo(options: obj) : LoadedFont = jsNative

        [<Import("Gudea", "next/font/google")>]
        static member Gudea(options: obj) : LoadedFont = jsNative

        [<Import("Gugi", "next/font/google")>]
        static member Gugi(options: obj) : LoadedFont = jsNative

        [<Import("Gulzar", "next/font/google")>]
        static member Gulzar(options: obj) : LoadedFont = jsNative

        [<Import("Gupter", "next/font/google")>]
        static member Gupter(options: obj) : LoadedFont = jsNative

        [<Import("Gurajada", "next/font/google")>]
        static member Gurajada(options: obj) : LoadedFont = jsNative

        [<Import("Gwendolyn", "next/font/google")>]
        static member Gwendolyn(options: obj) : LoadedFont = jsNative

        [<Import("Habibi", "next/font/google")>]
        static member Habibi(options: obj) : LoadedFont = jsNative

        [<Import("Hachi_Maru_Pop", "next/font/google")>]
        static member Hachi_Maru_Pop(options: obj) : LoadedFont = jsNative

        [<Import("Hahmlet", "next/font/google")>]
        static member Hahmlet(options: obj) : LoadedFont = jsNative

        [<Import("Halant", "next/font/google")>]
        static member Halant(options: obj) : LoadedFont = jsNative

        [<Import("Hammersmith_One", "next/font/google")>]
        static member Hammersmith_One(options: obj) : LoadedFont = jsNative

        [<Import("Hanalei", "next/font/google")>]
        static member Hanalei(options: obj) : LoadedFont = jsNative

        [<Import("Hanalei_Fill", "next/font/google")>]
        static member Hanalei_Fill(options: obj) : LoadedFont = jsNative

        [<Import("Handjet", "next/font/google")>]
        static member Handjet(options: obj) : LoadedFont = jsNative

        [<Import("Handlee", "next/font/google")>]
        static member Handlee(options: obj) : LoadedFont = jsNative

        [<Import("Hanken_Grotesk", "next/font/google")>]
        static member Hanken_Grotesk(options: obj) : LoadedFont = jsNative

        [<Import("Hanuman", "next/font/google")>]
        static member Hanuman(options: obj) : LoadedFont = jsNative

        [<Import("Happy_Monkey", "next/font/google")>]
        static member Happy_Monkey(options: obj) : LoadedFont = jsNative

        [<Import("Harmattan", "next/font/google")>]
        static member Harmattan(options: obj) : LoadedFont = jsNative

        [<Import("Headland_One", "next/font/google")>]
        static member Headland_One(options: obj) : LoadedFont = jsNative

        [<Import("Hedvig_Letters_Sans", "next/font/google")>]
        static member Hedvig_Letters_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Hedvig_Letters_Serif", "next/font/google")>]
        static member Hedvig_Letters_Serif(options: obj) : LoadedFont = jsNative

        [<Import("Heebo", "next/font/google")>]
        static member Heebo(options: obj) : LoadedFont = jsNative

        [<Import("Henny_Penny", "next/font/google")>]
        static member Henny_Penny(options: obj) : LoadedFont = jsNative

        [<Import("Hepta_Slab", "next/font/google")>]
        static member Hepta_Slab(options: obj) : LoadedFont = jsNative

        [<Import("Herr_Von_Muellerhoff", "next/font/google")>]
        static member Herr_Von_Muellerhoff(options: obj) : LoadedFont = jsNative

