namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk01 =
    type GoogleFont with
        [<Import("ABeeZee", "next/font/google")>]
        static member ABeeZee(options: obj) : LoadedFont = jsNative

        [<Import("ADLaM_Display", "next/font/google")>]
        static member ADLaM_Display(options: obj) : LoadedFont = jsNative

        [<Import("AR_One_Sans", "next/font/google")>]
        static member AR_One_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Abel", "next/font/google")>]
        static member Abel(options: obj) : LoadedFont = jsNative

        [<Import("Abhaya_Libre", "next/font/google")>]
        static member Abhaya_Libre(options: obj) : LoadedFont = jsNative

        [<Import("Aboreto", "next/font/google")>]
        static member Aboreto(options: obj) : LoadedFont = jsNative

        [<Import("Abril_Fatface", "next/font/google")>]
        static member Abril_Fatface(options: obj) : LoadedFont = jsNative

        [<Import("Abyssinica_SIL", "next/font/google")>]
        static member Abyssinica_SIL(options: obj) : LoadedFont = jsNative

        [<Import("Aclonica", "next/font/google")>]
        static member Aclonica(options: obj) : LoadedFont = jsNative

        [<Import("Acme", "next/font/google")>]
        static member Acme(options: obj) : LoadedFont = jsNative

        [<Import("Actor", "next/font/google")>]
        static member Actor(options: obj) : LoadedFont = jsNative

        [<Import("Adamina", "next/font/google")>]
        static member Adamina(options: obj) : LoadedFont = jsNative

        [<Import("Advent_Pro", "next/font/google")>]
        static member Advent_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Afacad", "next/font/google")>]
        static member Afacad(options: obj) : LoadedFont = jsNative

        [<Import("Afacad_Flux", "next/font/google")>]
        static member Afacad_Flux(options: obj) : LoadedFont = jsNative

        [<Import("Agbalumo", "next/font/google")>]
        static member Agbalumo(options: obj) : LoadedFont = jsNative

        [<Import("Agdasima", "next/font/google")>]
        static member Agdasima(options: obj) : LoadedFont = jsNative

        [<Import("Agu_Display", "next/font/google")>]
        static member Agu_Display(options: obj) : LoadedFont = jsNative

        [<Import("Aguafina_Script", "next/font/google")>]
        static member Aguafina_Script(options: obj) : LoadedFont = jsNative

        [<Import("Akatab", "next/font/google")>]
        static member Akatab(options: obj) : LoadedFont = jsNative

        [<Import("Akaya_Kanadaka", "next/font/google")>]
        static member Akaya_Kanadaka(options: obj) : LoadedFont = jsNative

        [<Import("Akaya_Telivigala", "next/font/google")>]
        static member Akaya_Telivigala(options: obj) : LoadedFont = jsNative

        [<Import("Akronim", "next/font/google")>]
        static member Akronim(options: obj) : LoadedFont = jsNative

        [<Import("Akshar", "next/font/google")>]
        static member Akshar(options: obj) : LoadedFont = jsNative

        [<Import("Aladin", "next/font/google")>]
        static member Aladin(options: obj) : LoadedFont = jsNative

        [<Import("Alan_Sans", "next/font/google")>]
        static member Alan_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Alata", "next/font/google")>]
        static member Alata(options: obj) : LoadedFont = jsNative

        [<Import("Alatsi", "next/font/google")>]
        static member Alatsi(options: obj) : LoadedFont = jsNative

        [<Import("Albert_Sans", "next/font/google")>]
        static member Albert_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Aldrich", "next/font/google")>]
        static member Aldrich(options: obj) : LoadedFont = jsNative

        [<Import("Alef", "next/font/google")>]
        static member Alef(options: obj) : LoadedFont = jsNative

        [<Import("Alegreya", "next/font/google")>]
        static member Alegreya(options: obj) : LoadedFont = jsNative

        [<Import("Alegreya_SC", "next/font/google")>]
        static member Alegreya_SC(options: obj) : LoadedFont = jsNative

        [<Import("Alegreya_Sans", "next/font/google")>]
        static member Alegreya_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Alegreya_Sans_SC", "next/font/google")>]
        static member Alegreya_Sans_SC(options: obj) : LoadedFont = jsNative

        [<Import("Aleo", "next/font/google")>]
        static member Aleo(options: obj) : LoadedFont = jsNative

        [<Import("Alex_Brush", "next/font/google")>]
        static member Alex_Brush(options: obj) : LoadedFont = jsNative

        [<Import("Alexandria", "next/font/google")>]
        static member Alexandria(options: obj) : LoadedFont = jsNative

        [<Import("Alfa_Slab_One", "next/font/google")>]
        static member Alfa_Slab_One(options: obj) : LoadedFont = jsNative

        [<Import("Alice", "next/font/google")>]
        static member Alice(options: obj) : LoadedFont = jsNative

        [<Import("Alike", "next/font/google")>]
        static member Alike(options: obj) : LoadedFont = jsNative

        [<Import("Alike_Angular", "next/font/google")>]
        static member Alike_Angular(options: obj) : LoadedFont = jsNative

        [<Import("Alkalami", "next/font/google")>]
        static member Alkalami(options: obj) : LoadedFont = jsNative

        [<Import("Alkatra", "next/font/google")>]
        static member Alkatra(options: obj) : LoadedFont = jsNative

        [<Import("Allan", "next/font/google")>]
        static member Allan(options: obj) : LoadedFont = jsNative

        [<Import("Allerta", "next/font/google")>]
        static member Allerta(options: obj) : LoadedFont = jsNative

        [<Import("Allerta_Stencil", "next/font/google")>]
        static member Allerta_Stencil(options: obj) : LoadedFont = jsNative

        [<Import("Allison", "next/font/google")>]
        static member Allison(options: obj) : LoadedFont = jsNative

