namespace NextFs

open Fable.Core

// Generated by tools/generate-google-font-bindings.mjs
// Source: next@16.2.1 package/dist/compiled/@next/font/dist/google/index.d.ts
[<AutoOpen>]
module GoogleFontChunk04 =
    type GoogleFont with
        [<Import("BBH_Hegarty", "next/font/google")>]
        static member BBH_Hegarty(options: obj) : LoadedFont = jsNative

        [<Import("BIZ_UDGothic", "next/font/google")>]
        static member BIZ_UDGothic(options: obj) : LoadedFont = jsNative

        [<Import("BIZ_UDMincho", "next/font/google")>]
        static member BIZ_UDMincho(options: obj) : LoadedFont = jsNative

        [<Import("BIZ_UDPGothic", "next/font/google")>]
        static member BIZ_UDPGothic(options: obj) : LoadedFont = jsNative

        [<Import("BIZ_UDPMincho", "next/font/google")>]
        static member BIZ_UDPMincho(options: obj) : LoadedFont = jsNative

        [<Import("Babylonica", "next/font/google")>]
        static member Babylonica(options: obj) : LoadedFont = jsNative

        [<Import("Bacasime_Antique", "next/font/google")>]
        static member Bacasime_Antique(options: obj) : LoadedFont = jsNative

        [<Import("Bad_Script", "next/font/google")>]
        static member Bad_Script(options: obj) : LoadedFont = jsNative

        [<Import("Badeen_Display", "next/font/google")>]
        static member Badeen_Display(options: obj) : LoadedFont = jsNative

        [<Import("Bagel_Fat_One", "next/font/google")>]
        static member Bagel_Fat_One(options: obj) : LoadedFont = jsNative

        [<Import("Bahiana", "next/font/google")>]
        static member Bahiana(options: obj) : LoadedFont = jsNative

        [<Import("Bahianita", "next/font/google")>]
        static member Bahianita(options: obj) : LoadedFont = jsNative

        [<Import("Bai_Jamjuree", "next/font/google")>]
        static member Bai_Jamjuree(options: obj) : LoadedFont = jsNative

        [<Import("Bakbak_One", "next/font/google")>]
        static member Bakbak_One(options: obj) : LoadedFont = jsNative

        [<Import("Ballet", "next/font/google")>]
        static member Ballet(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_2", "next/font/google")>]
        static member Baloo_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Bhai_2", "next/font/google")>]
        static member Baloo_Bhai_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Bhaijaan_2", "next/font/google")>]
        static member Baloo_Bhaijaan_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Bhaina_2", "next/font/google")>]
        static member Baloo_Bhaina_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Chettan_2", "next/font/google")>]
        static member Baloo_Chettan_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Da_2", "next/font/google")>]
        static member Baloo_Da_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Paaji_2", "next/font/google")>]
        static member Baloo_Paaji_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Tamma_2", "next/font/google")>]
        static member Baloo_Tamma_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Tammudu_2", "next/font/google")>]
        static member Baloo_Tammudu_2(options: obj) : LoadedFont = jsNative

        [<Import("Baloo_Thambi_2", "next/font/google")>]
        static member Baloo_Thambi_2(options: obj) : LoadedFont = jsNative

        [<Import("Balsamiq_Sans", "next/font/google")>]
        static member Balsamiq_Sans(options: obj) : LoadedFont = jsNative

        [<Import("Balthazar", "next/font/google")>]
        static member Balthazar(options: obj) : LoadedFont = jsNative

        [<Import("Bangers", "next/font/google")>]
        static member Bangers(options: obj) : LoadedFont = jsNative

        [<Import("Barlow", "next/font/google")>]
        static member Barlow(options: obj) : LoadedFont = jsNative

        [<Import("Barlow_Condensed", "next/font/google")>]
        static member Barlow_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Barlow_Semi_Condensed", "next/font/google")>]
        static member Barlow_Semi_Condensed(options: obj) : LoadedFont = jsNative

        [<Import("Barriecito", "next/font/google")>]
        static member Barriecito(options: obj) : LoadedFont = jsNative

        [<Import("Barrio", "next/font/google")>]
        static member Barrio(options: obj) : LoadedFont = jsNative

        [<Import("Basic", "next/font/google")>]
        static member Basic(options: obj) : LoadedFont = jsNative

        [<Import("Baskervville", "next/font/google")>]
        static member Baskervville(options: obj) : LoadedFont = jsNative

        [<Import("Baskervville_SC", "next/font/google")>]
        static member Baskervville_SC(options: obj) : LoadedFont = jsNative

        [<Import("Battambang", "next/font/google")>]
        static member Battambang(options: obj) : LoadedFont = jsNative

        [<Import("Baumans", "next/font/google")>]
        static member Baumans(options: obj) : LoadedFont = jsNative

        [<Import("Bayon", "next/font/google")>]
        static member Bayon(options: obj) : LoadedFont = jsNative

        [<Import("Be_Vietnam_Pro", "next/font/google")>]
        static member Be_Vietnam_Pro(options: obj) : LoadedFont = jsNative

        [<Import("Beau_Rivage", "next/font/google")>]
        static member Beau_Rivage(options: obj) : LoadedFont = jsNative

        [<Import("Bebas_Neue", "next/font/google")>]
        static member Bebas_Neue(options: obj) : LoadedFont = jsNative

        [<Import("Beiruti", "next/font/google")>]
        static member Beiruti(options: obj) : LoadedFont = jsNative

        [<Import("Belanosima", "next/font/google")>]
        static member Belanosima(options: obj) : LoadedFont = jsNative

        [<Import("Belgrano", "next/font/google")>]
        static member Belgrano(options: obj) : LoadedFont = jsNative

        [<Import("Bellefair", "next/font/google")>]
        static member Bellefair(options: obj) : LoadedFont = jsNative

        [<Import("Belleza", "next/font/google")>]
        static member Belleza(options: obj) : LoadedFont = jsNative

        [<Import("Bellota", "next/font/google")>]
        static member Bellota(options: obj) : LoadedFont = jsNative

