import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatorPath = path.join(repoRoot, "tools", "nextfs-entry.mjs");

async function makeWorkspace() {
  return mkdtemp(path.join(tmpdir(), "nextfs-entry-"));
}

async function writeJsonFile(filePath, value) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function writeTextFile(filePath, value) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, value, "utf8");
}

async function runGenerator(cwd, args = []) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [generatorPath, ...args], {
      cwd,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("close", (code) => {
      resolve({ code, stdout, stderr });
    });
  });
}

test("generates valid wrappers with the expected output shape", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, "source", "page.js"), "export default 1;\n");
  await writeTextFile(path.join(cwd, "src", "actions.js"), "export const createPost = () => {};\n");
  await writeTextFile(path.join(cwd, "src", "routes.js"), "export const GET = () => {};\n");

  await writeJsonFile(configPath, {
    entries: [
      {
        directive: "use client",
        from: "./source/page.js",
        to: "./source/page.wrapper.js",
        default: true,
      },
      {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        named: ["createPost", "deletePost"],
      },
      {
        from: "./src/routes.js",
        to: "./generated/routes.js",
        exportAll: true,
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(await readFile(path.join(cwd, "source", "page.wrapper.js"), "utf8"), "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nexport { default } from './page.js'\n");
  assert.equal(await readFile(path.join(cwd, "generated", "actions.js"), "utf8"), "'use server'\n\n// Generated by NextFs. Do not edit by hand.\nexport { createPost, deletePost } from '../src/actions.js'\n");
  assert.equal(await readFile(path.join(cwd, "generated", "routes.js"), "utf8"), "// Generated by NextFs. Do not edit by hand.\nexport * from '../src/routes.js'\n");
});

test("generates root-level proxy wrappers with named exports", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "proxy.js"), "export const proxy = () => {};\nexport const config = {};\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        from: "./.fable/proxy.js",
        to: "./proxy.js",
        named: ["proxy"],
        staticExports: {
          config: {
            matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
          },
        },
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "proxy.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { proxy } from './.fable/proxy.js'\nexport const config = {\n  \"matcher\": [\n    \"/((?!_next/static|_next/image|favicon.ico).*)\"\n  ]\n}\n",
  );
});

test("supports route-handler wrappers with config exports", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(
    path.join(cwd, ".fable", "App.Api.Posts.js"),
    "export const GET = () => {};\nexport const POST = () => {};\nexport const runtime = 'nodejs';\nexport const preferredRegion = 'home';\nexport const maxDuration = 15;\n",
  );
  await writeJsonFile(configPath, {
    entries: [
      {
        from: "./.fable/App.Api.Posts.js",
        to: "./app/api/posts/route.js",
        named: ["GET", "POST"],
        staticExports: {
          runtime: "nodejs",
          preferredRegion: "home",
          maxDuration: 15,
        },
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "app", "api", "posts", "route.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { GET, POST } from '../../../.fable/App.Api.Posts.js'\nexport const runtime = \"nodejs\"\nexport const preferredRegion = \"home\"\nexport const maxDuration = 15\n",
  );
});

test("generates special-file wrappers with the expected directives and exports", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "App.Error.js"), "export default function Error() {}\n");
  await writeTextFile(path.join(cwd, ".fable", "App.GlobalNotFound.js"), "export default function GlobalNotFound() {}\nexport const metadata = {};\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        directive: "use client",
        from: "./.fable/App.Error.js",
        to: "./app/error.js",
        default: true,
      },
      {
        from: "./.fable/App.GlobalNotFound.js",
        to: "./app/global-not-found.js",
        default: true,
        named: ["metadata"],
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "app", "error.js"), "utf8"),
    "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.Error.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "global-not-found.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.GlobalNotFound.js'\nexport { metadata } from '../.fable/App.GlobalNotFound.js'\n",
  );
});

test("covers the remaining special-file wrapper patterns", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  const files = [
    ["App.Default.js", "Default"],
    ["App.Forbidden.js", "Forbidden"],
    ["App.GlobalError.js", "GlobalError"],
    ["App.Loading.js", "Loading"],
    ["App.NotFound.js", "NotFound"],
    ["App.Template.js", "Template"],
    ["App.Unauthorized.js", "Unauthorized"],
  ];

  for (const [fileName, componentName] of files) {
    await writeTextFile(path.join(cwd, ".fable", fileName), `export default function ${componentName}() {}\n`);
  }

  await writeJsonFile(configPath, {
    entries: [
      {
        from: "./.fable/App.Default.js",
        to: "./app/default.js",
        default: true,
      },
      {
        from: "./.fable/App.Forbidden.js",
        to: "./app/forbidden.js",
        default: true,
      },
      {
        directive: "use client",
        from: "./.fable/App.GlobalError.js",
        to: "./app/global-error.js",
        default: true,
      },
      {
        from: "./.fable/App.Loading.js",
        to: "./app/loading.js",
        default: true,
      },
      {
        from: "./.fable/App.NotFound.js",
        to: "./app/not-found.js",
        default: true,
      },
      {
        from: "./.fable/App.Template.js",
        to: "./app/template.js",
        default: true,
      },
      {
        from: "./.fable/App.Unauthorized.js",
        to: "./app/unauthorized.js",
        default: true,
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "app", "default.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.Default.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "forbidden.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.Forbidden.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "global-error.js"), "utf8"),
    "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.GlobalError.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "loading.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.Loading.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "not-found.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.NotFound.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "template.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.Template.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "unauthorized.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App.Unauthorized.js'\n",
  );
});

test("supports nested app segments and parallel-route wrapper paths", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "App.Marketing.Template.js"), "export default function Template() {}\n");
  await writeTextFile(path.join(cwd, ".fable", "App.Dashboard.Analytics.Default.js"), "export default function Default() {}\n");
  await writeTextFile(path.join(cwd, ".fable", "App.Dashboard.Error.js"), "export default function Error() {}\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        from: "./.fable/App.Marketing.Template.js",
        to: "./app/(marketing)/template.js",
        default: true,
      },
      {
        from: "./.fable/App.Dashboard.Analytics.Default.js",
        to: "./app/dashboard/@analytics/default.js",
        default: true,
      },
      {
        directive: "use client",
        from: "./.fable/App.Dashboard.Error.js",
        to: "./app/dashboard/error.js",
        default: true,
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "app", "(marketing)", "template.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../../.fable/App.Marketing.Template.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "dashboard", "@analytics", "default.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../../../.fable/App.Dashboard.Analytics.Default.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "dashboard", "error.js"), "utf8"),
    "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nexport { default } from '../../.fable/App.Dashboard.Error.js'\n",
  );
});

test("supports named-to-default wrappers for App Router entries", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "App.Page.js"), "export function Page() {}\n");
  await writeTextFile(path.join(cwd, ".fable", "App.Layout.js"), "export function Layout() {}\nexport const metadata = {};\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        directive: "use client",
        from: "./.fable/App.Page.js",
        to: "./app/page.js",
        defaultFromNamed: "Page",
      },
      {
        from: "./.fable/App.Layout.js",
        to: "./app/layout.js",
        defaultFromNamed: "Layout",
        named: ["metadata"],
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "app", "page.js"), "utf8"),
    "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nimport { Page as __nextFsDefault } from '../.fable/App.Page.js'\nexport default __nextFsDefault\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "layout.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nimport { Layout as __nextFsDefault } from '../.fable/App.Layout.js'\nexport default __nextFsDefault\nexport { metadata } from '../.fable/App.Layout.js'\n",
  );
});

test("falls back to nested Fable output paths when dotted module specifiers do not exist", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "App", "Page.js"), "export function Page() {}\n");
  await writeTextFile(path.join(cwd, ".fable", "App", "Api", "Posts.js"), "export function GET() {}\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        directive: "use client",
        from: "./.fable/App.Page.js",
        to: "./app/page.js",
        defaultFromNamed: "Page",
      },
      {
        from: "./.fable/App.Api.Posts.js",
        to: "./app/api/posts/route.js",
        named: ["GET"],
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "app", "page.js"), "utf8"),
    "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nimport { Page as __nextFsDefault } from '../.fable/App/Page.js'\nexport default __nextFsDefault\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "app", "api", "posts", "route.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { GET } from '../../../.fable/App/Api/Posts.js'\n",
  );
});

test("supports root instrumentation entry wrappers", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "Instrumentation.js"), "export const register = () => {};\nexport const onRequestError = () => {};\n");
  await writeTextFile(path.join(cwd, ".fable", "InstrumentationClient.js"), "export const onRouterTransitionStart = () => {};\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        from: "./.fable/Instrumentation.js",
        to: "./instrumentation.js",
        named: ["register", "onRequestError"],
      },
      {
        from: "./.fable/InstrumentationClient.js",
        to: "./instrumentation-client.js",
        exportAll: true,
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "instrumentation.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { register, onRequestError } from './.fable/Instrumentation.js'\n",
  );
  assert.equal(
    await readFile(path.join(cwd, "instrumentation-client.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport * from './.fable/InstrumentationClient.js'\n",
  );
});

test("prunes stale generated wrappers but leaves non-generated files alone", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "App", "Page.js"), "export function Page() {}\n");
  await writeTextFile(
    path.join(cwd, "app", "old.js"),
    "// Generated by NextFs. Do not edit by hand.\nexport { default } from '../.fable/App/Old.js'\n",
  );
  await writeTextFile(path.join(cwd, "app", "README.md"), "# keep me\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        directive: "use client",
        from: "./.fable/App/Page.js",
        to: "./app/page.js",
        defaultFromNamed: "Page",
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  await assert.rejects(() => readFile(path.join(cwd, "app", "old.js"), "utf8"));
  assert.equal(await readFile(path.join(cwd, "app", "README.md"), "utf8"), "# keep me\n");
  assert.equal(
    await readFile(path.join(cwd, "app", "page.js"), "utf8"),
    "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nimport { Page as __nextFsDefault } from '../.fable/App/Page.js'\nexport default __nextFsDefault\n",
  );
});

test("rejects unsupported use server wrapper shapes", async () => {
  const cases = [
    {
      name: "default export",
      entry: {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        default: true,
      },
      message: 'Entry "./generated/actions.js" cannot use "default" with "use server". Export named async functions only.',
    },
    {
      name: "defaultFromNamed export",
      entry: {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        defaultFromNamed: "createPost",
      },
      message: 'Entry "./generated/actions.js" cannot use "default" with "use server". Export named async functions only.',
    },
    {
      name: "exportAll",
      entry: {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        exportAll: true,
      },
      message: 'Entry "./generated/actions.js" cannot use "exportAll" with "use server".',
    },
  ];

  for (const { name, entry, message } of cases) {
    await test(name, async () => {
      const cwd = await makeWorkspace();
      await writeTextFile(path.join(cwd, "src", "actions.js"), "export const createPost = () => {};\n");
      await writeJsonFile(path.join(cwd, "nextfs.entries.json"), { entries: [entry] });

      const result = await runGenerator(cwd, ["nextfs.entries.json"]);

      assert.notEqual(result.code, 0);
      assert.match(result.stderr, new RegExp(message.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    });
  }
});

test("rejects bad config and entry inputs", async () => {
  const cases = [
    {
      name: "missing config argument",
      args: [],
      expected: "Usage: node tools/nextfs-entry.mjs <config.json>",
    },
    {
      name: "empty entries array",
      config: { entries: [] },
      expected: 'Config must contain a non-empty "entries" array.',
    },
    {
      name: "entry is not an object",
      config: { entries: [null] },
      expected: "Each entry must be an object.",
    },
    {
      name: "entry fields are not strings",
      config: { entries: [{ from: 1, to: 2 }] },
      expected: 'Each entry must contain string fields "from" and "to".',
    },
    {
      name: "named exports must be strings",
      config: { entries: [{ from: "./src/actions.js", to: "./generated/actions.js", named: ["ok", 1] }] },
      expected: 'Field "named" must be an array of strings.',
    },
    {
      name: "unsupported directive",
      config: {
        entries: [
          {
            directive: "use potato",
            from: "./src/actions.js",
            to: "./generated/actions.js",
            named: ["ok"],
          },
        ],
      },
      expected: 'Unsupported directive "use potato". Use "use client", "use server", or omit it.',
    },
    {
      name: "default and defaultFromNamed together",
      config: {
        entries: [
          {
            from: "./src/page.js",
            to: "./app/page.js",
            default: true,
            defaultFromNamed: "Page",
          },
        ],
      },
      expected: 'Entry "./app/page.js" cannot use both "default" and "defaultFromNamed".',
    },
    {
      name: "staticExports must be an object",
      config: {
        entries: [
          {
            from: "./src/routes.js",
            to: "./app/api/posts/route.js",
            staticExports: ["runtime"],
          },
        ],
      },
      expected: 'Field "staticExports" must be an object whose values are JSON-serializable.',
    },
    {
      name: "staticExports cannot duplicate named exports",
      config: {
        entries: [
          {
            from: "./src/routes.js",
            to: "./app/api/posts/route.js",
            named: ["runtime"],
            staticExports: {
              runtime: "nodejs",
            },
          },
        ],
      },
      expected: 'Entry "./app/api/posts/route.js" cannot export "runtime" from both "named" and "staticExports".',
    },
    {
      name: "duplicate output paths",
      config: {
        entries: [
          {
            from: "./src/one.js",
            to: "./app/page.js",
            default: true,
          },
          {
            from: "./src/two.js",
            to: "./app/page.js",
            named: ["Page"],
          },
        ],
      },
      expected: 'Config contains duplicate output path "./app/page.js".',
    },
  ];

  for (const { name, config, args = ["nextfs.entries.json"], expected } of cases) {
    await test(name, async () => {
      const cwd = await makeWorkspace();

      if (config) {
        await writeJsonFile(path.join(cwd, "nextfs.entries.json"), config);
      }

      const result = await runGenerator(cwd, args);

      assert.notEqual(result.code, 0);
      assert.match(result.stderr, new RegExp(expected.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    });
  }
});
