import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatorPath = path.join(repoRoot, "tools", "nextfs-entry.mjs");

async function makeWorkspace() {
  return mkdtemp(path.join(tmpdir(), "nextfs-entry-"));
}

async function writeJsonFile(filePath, value) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function writeTextFile(filePath, value) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, value, "utf8");
}

async function runGenerator(cwd, args = []) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [generatorPath, ...args], {
      cwd,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("close", (code) => {
      resolve({ code, stdout, stderr });
    });
  });
}

test("generates valid wrappers with the expected output shape", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, "source", "page.js"), "export default 1;\n");
  await writeTextFile(path.join(cwd, "src", "actions.js"), "export const createPost = () => {};\n");
  await writeTextFile(path.join(cwd, "src", "routes.js"), "export const GET = () => {};\n");

  await writeJsonFile(configPath, {
    entries: [
      {
        directive: "use client",
        from: "./source/page.js",
        to: "./source/page.wrapper.js",
        default: true,
      },
      {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        named: ["createPost", "deletePost"],
      },
      {
        from: "./src/routes.js",
        to: "./generated/routes.js",
        exportAll: true,
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(await readFile(path.join(cwd, "source", "page.wrapper.js"), "utf8"), "'use client'\n\n// Generated by NextFs. Do not edit by hand.\nexport { default } from './page.js'\n");
  assert.equal(await readFile(path.join(cwd, "generated", "actions.js"), "utf8"), "'use server'\n\n// Generated by NextFs. Do not edit by hand.\nexport { createPost, deletePost } from '../src/actions.js'\n");
  assert.equal(await readFile(path.join(cwd, "generated", "routes.js"), "utf8"), "// Generated by NextFs. Do not edit by hand.\nexport * from '../src/routes.js'\n");
});

test("generates root-level proxy wrappers with named exports", async () => {
  const cwd = await makeWorkspace();
  const configPath = path.join(cwd, "nextfs.entries.json");

  await writeTextFile(path.join(cwd, ".fable", "proxy.js"), "export const proxy = () => {};\nexport const config = {};\n");
  await writeJsonFile(configPath, {
    entries: [
      {
        from: "./.fable/proxy.js",
        to: "./proxy.js",
        named: ["proxy", "config"],
      },
    ],
  });

  const result = await runGenerator(cwd, ["nextfs.entries.json"]);

  assert.equal(result.code, 0, result.stderr);
  assert.equal(
    await readFile(path.join(cwd, "proxy.js"), "utf8"),
    "// Generated by NextFs. Do not edit by hand.\nexport { proxy, config } from './.fable/proxy.js'\n",
  );
});

test("rejects unsupported use server wrapper shapes", async () => {
  const cases = [
    {
      name: "default export",
      entry: {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        default: true,
      },
      message: 'Entry "./generated/actions.js" cannot use "default" with "use server". Export named async functions only.',
    },
    {
      name: "exportAll",
      entry: {
        directive: "use server",
        from: "./src/actions.js",
        to: "./generated/actions.js",
        exportAll: true,
      },
      message: 'Entry "./generated/actions.js" cannot use "exportAll" with "use server".',
    },
  ];

  for (const { name, entry, message } of cases) {
    await test(name, async () => {
      const cwd = await makeWorkspace();
      await writeTextFile(path.join(cwd, "src", "actions.js"), "export const createPost = () => {};\n");
      await writeJsonFile(path.join(cwd, "nextfs.entries.json"), { entries: [entry] });

      const result = await runGenerator(cwd, ["nextfs.entries.json"]);

      assert.notEqual(result.code, 0);
      assert.match(result.stderr, new RegExp(message.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    });
  }
});

test("rejects bad config and entry inputs", async () => {
  const cases = [
    {
      name: "missing config argument",
      args: [],
      expected: "Usage: node tools/nextfs-entry.mjs <config.json>",
    },
    {
      name: "empty entries array",
      config: { entries: [] },
      expected: 'Config must contain a non-empty "entries" array.',
    },
    {
      name: "entry is not an object",
      config: { entries: [null] },
      expected: "Each entry must be an object.",
    },
    {
      name: "entry fields are not strings",
      config: { entries: [{ from: 1, to: 2 }] },
      expected: 'Each entry must contain string fields "from" and "to".',
    },
    {
      name: "named exports must be strings",
      config: { entries: [{ from: "./src/actions.js", to: "./generated/actions.js", named: ["ok", 1] }] },
      expected: 'Field "named" must be an array of strings.',
    },
    {
      name: "unsupported directive",
      config: {
        entries: [
          {
            directive: "use potato",
            from: "./src/actions.js",
            to: "./generated/actions.js",
            named: ["ok"],
          },
        ],
      },
      expected: 'Unsupported directive "use potato". Use "use client", "use server", or omit it.',
    },
  ];

  for (const { name, config, args = ["nextfs.entries.json"], expected } of cases) {
    await test(name, async () => {
      const cwd = await makeWorkspace();

      if (config) {
        await writeJsonFile(path.join(cwd, "nextfs.entries.json"), config);
      }

      const result = await runGenerator(cwd, args);

      assert.notEqual(result.code, 0);
      assert.match(result.stderr, new RegExp(expected.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    });
  }
});
