// Generated by NextFs. Do not edit by hand.
export { GET, POST } from '../../../.fable/App/Api/Posts.js'
export const runtime = "nodejs"
export const preferredRegion = "home"
export const maxDuration = 15
