#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const generatedMarker = "// Generated by NextFs. Do not edit by hand.";

function fail(message) {
  throw new Error(message);
}

function ensureArray(value, fieldName) {
  if (value === undefined) {
    return [];
  }

  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    fail(`Field "${fieldName}" must be an array of strings.`);
  }

  return value;
}

function ensureOptionalString(value, fieldName) {
  if (value === undefined) {
    return undefined;
  }

  if (typeof value !== "string" || value.length === 0) {
    fail(`Field "${fieldName}" must be a non-empty string.`);
  }

  return value;
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function ensureStaticExports(value) {
  if (value === undefined) {
    return {};
  }

  if (!isPlainObject(value)) {
    fail('Field "staticExports" must be an object whose values are JSON-serializable.');
  }

  return value;
}

function toModuleSpecifier(relativePath) {
  const normalized = relativePath.split(path.sep).join("/");
  return normalized.startsWith("./") || normalized.startsWith("../") ? normalized : `./${normalized}`;
}

function toJsLiteral(value) {
  const serialized = JSON.stringify(value, null, 2);

  if (serialized === undefined) {
    fail('Field "staticExports" contains a value that cannot be serialized to JavaScript.');
  }

  return serialized;
}

async function pathExists(candidatePath) {
  try {
    await fs.access(candidatePath);
    return true;
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return false;
    }

    throw error;
  }
}

function toNestedModulePath(sourcePath) {
  const parsed = path.parse(sourcePath);
  const nameSegments = parsed.name.split(".");

  if (nameSegments.length <= 1) {
    return undefined;
  }

  return path.join(parsed.dir, ...nameSegments) + parsed.ext;
}

async function resolveSourcePath(configDir, sourceValue) {
  const directPath = path.resolve(configDir, sourceValue);

  if (await pathExists(directPath)) {
    return directPath;
  }

  const nestedPath = toNestedModulePath(directPath);

  if (nestedPath && await pathExists(nestedPath)) {
    return nestedPath;
  }

  return directPath;
}

function buildWrapper(entry, sourceSpecifier) {
  const lines = [];
  const named = ensureArray(entry.named, "named");
  const exportAll = entry.exportAll === true;
  const exportDefault = entry.default === true;
  const defaultFromNamed = ensureOptionalString(entry.defaultFromNamed, "defaultFromNamed");
  const staticExports = ensureStaticExports(entry.staticExports);
  const directive = entry.directive;
  const staticExportNames = Object.keys(staticExports);

  if (directive !== undefined && directive !== "use client" && directive !== "use server") {
    fail(`Unsupported directive "${directive}". Use "use client", "use server", or omit it.`);
  }

  if (directive === "use server" && exportAll) {
    fail(`Entry "${entry.to}" cannot use "exportAll" with "use server".`);
  }

  if (directive === "use server" && (exportDefault || defaultFromNamed)) {
    fail(`Entry "${entry.to}" cannot use "default" with "use server". Export named async functions only.`);
  }

  if (exportDefault && defaultFromNamed) {
    fail(`Entry "${entry.to}" cannot use both "default" and "defaultFromNamed".`);
  }

  for (const exportName of staticExportNames) {
    if (named.includes(exportName)) {
      fail(`Entry "${entry.to}" cannot export "${exportName}" from both "named" and "staticExports".`);
    }
  }

  if (!exportDefault && !defaultFromNamed && !exportAll && named.length === 0 && staticExportNames.length === 0) {
    fail(`Entry "${entry.to}" must export at least one symbol.`);
  }

  if (directive) {
    lines.push(`'${directive}'`, "");
  }

  lines.push(generatedMarker);

  if (exportDefault) {
    lines.push(`export { default } from '${sourceSpecifier}'`);
  }

  if (defaultFromNamed) {
    lines.push(`import { ${defaultFromNamed} as __nextFsDefault } from '${sourceSpecifier}'`);
    lines.push("export default __nextFsDefault");
  }

  if (named.length > 0) {
    lines.push(`export { ${named.join(", ")} } from '${sourceSpecifier}'`);
  }

  if (exportAll) {
    lines.push(`export * from '${sourceSpecifier}'`);
  }

  for (const [exportName, exportValue] of Object.entries(staticExports)) {
    lines.push(`export const ${exportName} = ${toJsLiteral(exportValue)}`);
  }

  return `${lines.join("\n")}\n`;
}

async function collectFiles(rootDir) {
  const files = [];
  const entries = await fs.readdir(rootDir, { withFileTypes: true });

  for (const entry of entries) {
    const entryPath = path.join(rootDir, entry.name);

    if (entry.isDirectory()) {
      files.push(...await collectFiles(entryPath));
      continue;
    }

    files.push(entryPath);
  }

  return files;
}

async function pruneGeneratedOutputs(expectedOutputs) {
  const parentDirectories = new Set(Array.from(expectedOutputs, (outputPath) => path.dirname(outputPath)));

  for (const parentDirectory of parentDirectories) {
    try {
      const directEntries = await fs.readdir(parentDirectory, { withFileTypes: true });

      for (const directEntry of directEntries) {
        if (!directEntry.isFile()) {
          continue;
        }

        const directEntryPath = path.join(parentDirectory, directEntry.name);

        if (expectedOutputs.has(directEntryPath)) {
          continue;
        }

        const directEntryText = await fs.readFile(directEntryPath, "utf8").catch(() => undefined);

        if (typeof directEntryText === "string" && directEntryText.includes(generatedMarker)) {
          await fs.unlink(directEntryPath);
        }
      }

      const existingFiles = await collectFiles(parentDirectory);

      for (const existingFile of existingFiles) {
        if (expectedOutputs.has(existingFile)) {
          continue;
        }

        const fileText = await fs.readFile(existingFile, "utf8").catch(() => undefined);

        if (typeof fileText === "string" && fileText.includes(generatedMarker)) {
          await fs.unlink(existingFile);
        }
      }
    } catch (error) {
      if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
        continue;
      }

      throw error;
    }
  }
}

async function main() {
  const [configArg] = process.argv.slice(2);

  if (!configArg) {
    fail("Usage: node tools/nextfs-entry.mjs <config.json>");
  }

  const configPath = path.resolve(process.cwd(), configArg);
  const configDir = path.dirname(configPath);
  const configText = await fs.readFile(configPath, "utf8");
  const config = JSON.parse(configText);
  const entries = Array.isArray(config) ? config : config.entries;

  if (!Array.isArray(entries) || entries.length === 0) {
    fail('Config must contain a non-empty "entries" array.');
  }

  const expectedOutputs = new Set();

  for (const entry of entries) {
    if (!entry || typeof entry !== "object") {
      fail("Each entry must be an object.");
    }

    if (typeof entry.from !== "string" || typeof entry.to !== "string") {
      fail('Each entry must contain string fields "from" and "to".');
    }

    const sourcePath = await resolveSourcePath(configDir, entry.from);
    const outputPath = path.resolve(configDir, entry.to);

    if (expectedOutputs.has(outputPath)) {
      fail(`Config contains duplicate output path "${entry.to}".`);
    }

    expectedOutputs.add(outputPath);

    const moduleSpecifier = toModuleSpecifier(path.relative(path.dirname(outputPath), sourcePath));
    const wrapper = buildWrapper(entry, moduleSpecifier);

    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, wrapper, "utf8");
  }

  await pruneGeneratedOutputs(expectedOutputs);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
