#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

function fail(message) {
  throw new Error(message);
}

function ensureArray(value, fieldName) {
  if (value === undefined) {
    return [];
  }

  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    fail(`Field "${fieldName}" must be an array of strings.`);
  }

  return value;
}

function toModuleSpecifier(relativePath) {
  const normalized = relativePath.split(path.sep).join("/");
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function buildWrapper(entry, sourceSpecifier) {
  const lines = [];
  const named = ensureArray(entry.named, "named");
  const exportAll = entry.exportAll === true;
  const exportDefault = entry.default === true;
  const directive = entry.directive;

  if (directive !== undefined && directive !== "use client" && directive !== "use server") {
    fail(`Unsupported directive "${directive}". Use "use client", "use server", or omit it.`);
  }

  if (directive === "use server" && exportAll) {
    fail(`Entry "${entry.to}" cannot use "exportAll" with "use server".`);
  }

  if (directive === "use server" && exportDefault) {
    fail(`Entry "${entry.to}" cannot use "default" with "use server". Export named async functions only.`);
  }

  if (!exportDefault && !exportAll && named.length === 0) {
    fail(`Entry "${entry.to}" must export at least one symbol.`);
  }

  if (directive) {
    lines.push(`'${directive}'`, "");
  }

  lines.push("// Generated by NextFs. Do not edit by hand.");

  if (exportDefault) {
    lines.push(`export { default } from '${sourceSpecifier}'`);
  }

  if (named.length > 0) {
    lines.push(`export { ${named.join(", ")} } from '${sourceSpecifier}'`);
  }

  if (exportAll) {
    lines.push(`export * from '${sourceSpecifier}'`);
  }

  return `${lines.join("\n")}\n`;
}

async function main() {
  const [configArg] = process.argv.slice(2);

  if (!configArg) {
    fail("Usage: node tools/nextfs-entry.mjs <config.json>");
  }

  const configPath = path.resolve(process.cwd(), configArg);
  const configDir = path.dirname(configPath);
  const configText = await fs.readFile(configPath, "utf8");
  const config = JSON.parse(configText);
  const entries = Array.isArray(config) ? config : config.entries;

  if (!Array.isArray(entries) || entries.length === 0) {
    fail('Config must contain a non-empty "entries" array.');
  }

  for (const entry of entries) {
    if (!entry || typeof entry !== "object") {
      fail("Each entry must be an object.");
    }

    if (typeof entry.from !== "string" || typeof entry.to !== "string") {
      fail('Each entry must contain string fields "from" and "to".');
    }

    const sourcePath = path.resolve(configDir, entry.from);
    const outputPath = path.resolve(configDir, entry.to);
    const moduleSpecifier = toModuleSpecifier(path.relative(path.dirname(outputPath), sourcePath));
    const wrapper = buildWrapper(entry, moduleSpecifier);

    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, wrapper, "utf8");
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
