title: NextFs
description: Next.js App Router bindings for F#
url: https://neftedollar.github.io
baseurl: /Next.fs

remote_theme: just-the-docs/just-the-docs@v0.10.1

markdown: kramdown
highlighter: rouge

exclude:
  - README.md

aux_links:
  "GitHub":
    - "https://github.com/Neftedollar/Next.fs"
  "NuGet":
    - "https://www.nuget.org/packages/NextFs"

search_enabled: true
color_scheme: dark
